kubevirt/cluster-network-addons-operator

deploy/cluster-network-addons-operator_03_deployment.yaml

remove the command from operator yaml file and let im use the configured entrypoint from the container build
Fix issue #3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/4)

remove the command from operator yaml file.

---

README.md
config-example.yaml
data/multus/002-multus.yaml
pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
pkg/network/multus.go

Multus is not capable of creating its own config file with delegators
pointing to detected default network. Let's use this option instead
of requiring administrator to pass delegates explicitly.
With this change, testing on both OpenShift and Kubernetes will become
easier as we can use the same NetworkAddonsConfig on both. Also integration
with https://github.com/kubevirt/hyperconverged-cluster-operator should
be straightforward.

automatically detect multus configuration

---

Gopkg.lock
README.md
config-example.yaml
data/multus/002-multus.yaml
deploy/cluster-network-addons-operator_03_deployment.yaml
pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
pkg/network/image-pull-policy.go
pkg/network/linux-bridge.go
pkg/network/multus.go
pkg/network/network.go

Allow administrator to set desired ImagePullPolicy through
NetworkAddonsConfig CR. Until now, it was possible only using
operator's environment variables.
This PR will align us with KubeVirt and CDI operators.

configure ImagePullPolicy via operator CR

---

cmd/manager/main.go

I am guilty of not testing harmless #19. Turns out it broke
the operator.

fix openshift client issue

---

data/linux-bridge/002-linux-bridge.yaml

* remove the `cp -i` alias for `cp`
* copy any `*bridge` and `*tuning`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/25)

Change the linux deployment yaml

---

data/kubemacpool/001-rbac.yaml

related to this PR that was merge we need to update the rbac configuration in the operator
https://github.com/K8sNetworkPlumbingWG/kubemacpool/pull/8
Fixes #39
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/40)

Fix kubemacpool crash

---

deploy/cluster-network-addons-operator_03_deployment.yaml
pkg/controller/networkaddonsconfig/controller.go
pkg/controller/networkaddonsconfig/previous.go
pkg/names/names.go

This removes hardcoded namespace for applied config configmap. This
unblocks changing of operator's namespace just by changing its manifests.

keep applied config in the same namespace as the operator

---

data/kubemacpool/001-rbac.yaml
data/kubemacpool/004-deployment.yaml

Related to https://github.com/K8sNetworkPlumbingWG/kubemacpool/pull/10
Change the RBAC rule from statefulset to deployment
Change manager from statefulset to deployment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/45)

Change KubeMacPool RBAC rule

---

pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
pkg/network/image-pull-policy.go

Instead of a string, we should use Kubernetes Core v1 PullPolicy
type to specify image pull policy for components' pods.
This is done per request from https://github.com/kubevirt/hyperconverged-cluster-operator/pull/23#discussion_r273713084.

Use kubernetes core PullPolicy for imagePullPolicy

---

data/kubemacpool/004-deployment.yaml

For large cluster the kubemacpool gets kill by OOM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/51)

Update resource limit and request

---

data/kubemacpool/000-ns.yaml

using a label to ignore the webhook.
`kubemacpool/ignoreAdmission: "true"`
Related to https://github.com/K8sNetworkPlumbingWG/kubemacpool/pull/10/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/53)

add label for kubemacpool namespace

---

cluster/sync.sh
data/linux-bridge/002-linux-bridge.yaml
data/multus/002-multus.yaml
data/sriov/002-sriov-cni.yaml
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/network/cluster-info.go
pkg/network/cni/cni.go
pkg/network/linux-bridge.go
pkg/network/multus.go
pkg/network/network.go
pkg/network/sriov.go

With OpenShift 4, CNI config and bin directories has been moved from
/opt/cni/bin to /var/lib/cni/bin and from /etc/cni/net.d to
/etc/kubernetes/cni/net.d.
With this patch, we check whether we are running on OpenShift 4 by
looking up operator objects introduced in OpenShift 4 and making
CNI paths in components' manifests based on that.

Support OpenShift 4

---

data/sriov/002-sriov-cni.yaml

Plugin name may be changed in built images to accommodate for some
products (specifically, for Red Hat's CNV). Meaning, we would e.g. have
cnv-sriov instead of sriov, to avoid overriding the original upstream
plugin, or for other goals.
Note: current :latest upstream image is 5 months old and has sriov
binary located inside /usr/src/sriov-cni/bin instead of /usr/bin.
Current master branch of the sriov-cni repo puts the binary under
/usr/bin.  When they push an updated image to the docker repo we can
clean up the command in the manifest somewhat.

Copy *sriov to /opt/cni/bin

---

README.md
data/sriov/002-sriov-cni.yaml
data/sriov/004-sriov-network.yaml
deploy/olm-catalog/cluster-network-addons/0.0.0/cluster-network-addons-operator.v0.0.0.clusterserviceversion.yaml
deploy/operator.yaml
pkg/components/components.go
pkg/network/sriov.go

To use SR-IOV with KubeVirt, one needs to have a network attachment
definition that links back to resourceName used in SR-IOV DP config
file. This is the last missing bit in end-to-end SR-IOV integration.
I am using the `default` namespace and not `sriov` because it's assumed
that regular users will attach their pods / VMIs to the network, so
keeping it under `default` seems to make more sense. Otherwise one would
need to refer to the new network with namespace prefix included, as in:
`sriov/sriov-network` which is a bit too wordy.
Note that this PR doesn't allow to configure IPAM parameters for the
new network. I'd like to leave this piece separate from this patch.

Create sriov network attachment definition

---

Makefile
deploy/olm-catalog/cluster-network-addons/0.0.0/cluster-network-addons-operator.v0.0.0.clusterserviceversion.yaml
deploy/operator.yaml
pkg/components/components.go
tools/manifest-templator/manifest-templator.go

With this patch it is possible to build alternative operator manifests
grabbing network addons from alternative registries.
Resolves #56

make addons images configurable during `make manifests`

---

README.md

Current links are to github page, we need to link to raw content.

fix deployment manifest links in readme

---

pkg/controller/statusmanager/status_manager.go

https://github.com/openshift/cluster-network-operator/pull/143:
The easiest way to tell that a daemonset is progressing is that
UpdatedNumberScheduled is less than Desired.
Also, catch the case where the daemonset update hasn't yet been observed
by the controller.

status: catch a few more Progressing cases

---

pkg/controller/statusmanager/status_manager.go

https://github.com/openshift/cluster-network-operator/pull/136:
Since nil is used as value for having a condition as
non failing, we need to call it outside of the if
otherwise the failing condition will always set to nil.

Call syncFailing on SetNotFailing method

---

pkg/components/components.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/83)

Update the kubemacpool image to use tag v0.2.0 and not latest

---

README.md
data/linux-bridge/0004-bridge-marker-daemonset.yaml
data/linux-bridge/003-bridge-marker-rbac.yaml
pkg/components/components.go
pkg/network/linux-bridge.go
tools/manifest-templator/manifest-templator.go

This PR adds bridge-marker manifests to the linux bridge operator
```release-note
The linux bridge operator will now add the bridge-marker daemon set.
```

Add bridge-marker manifests

---

pkg/components/components.go

This pin also bumps version to the latest in upstream master. It should
work fine because we already create sriovdp configuration file and the
latest image is not broken anymore. (It was at some point broken by
alpine change, which was the original reason to pin it in
kubevirt-ansible, from where the forked image migrated to this
operator).

Pin sriovdp to specific version

---

pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/network/image-pull-policy.go
pkg/network/kubemacpool.go
pkg/network/network.go

This PR moves the range generation from the render to the fillDefaults functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/99)

Fill kubemacpool range in the fillDefaults function

---

pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go

This PR returnis error objects with stack trace.
Before this PR we called the errors.Wrapf but didn't assign
the return value into the err variable for return.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/100)

Return error with stack trace on renderObjects

---

README.md
cluster/up.sh

Now that kubernetes-nmstate is supported it needs NetworkManager to be
installed on the hosts, this patch document that and also add the
installation process at make cluster-up

Set NetworkManager as a requirement

---

data/nmstate/003-nmstated.yaml
pkg/components/components.go

We need to use fixed images version, otherwise, a change in :latest
component's image might be devastating in combination with manifests
shipped by us.

fix nmstate version to v0.1.0

---

cluster/functest.sh

Now when we added nmstate component to the operator, deployment
takes even more time and we need to increase test timeout in
order to make it pass on STD-CI.

increase timeout for functional tests

---

pkg/components/components.go

This PR update the the linux_bridge image to use cni plugin version v0.8.0
CNI plugin version v0.8.0 contains the vlan feature for linux bridge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/113)

Bump linux bridge to v0.8.0

---

Makefile
README.md
manifests/cluster-network-addons/0.9.0/cluster-network-addons-operator.0.9.0.clusterserviceversion.yaml
manifests/cluster-network-addons/0.9.0/namespace.yaml
manifests/cluster-network-addons/0.9.0/network-addons-config-example.cr.yaml
manifests/cluster-network-addons/0.9.0/network-addons-config.crd.yaml
manifests/cluster-network-addons/0.9.0/operator.yaml
manifests/cluster-network-addons/cluster-network-addons.package.yaml

This release contains:
* linux bridge version v0.8.0 using https://github.com/containernetworking/plugins/releases/tag/v0.8.0
* nmstate version v0.2.0 using https://github.com/nmstate/kubernetes-nmstate/releases/tag/v0.2.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/115)

Release 0.9.0

---

pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go

There is a bug, where after deployment of an empty NetworkAddonsConfig
Spec, we never set condition to running (that is usually done by Pod
reconciliation process after we reconcile the first monitored pod).
When however there are no pods being monitored, we never update the
status.
This patch triggers initial status update right after NodeNetworkConfig
reconciliation is done.

update status even with empty configuration

---

pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go

There is a bug where after NetworkAddonsConfig removal, we never
remove unprovisioned component pods from our tracked list. Due to
that, after recreation of NodeAddonsConfig, we fail because of missing
pods.
With this patch we make sure that during NetworkAddonsConfig removal,
we reset the list.

reset list of tracked pods after CR removal

---

pkg/controller/statusmanager/status_manager.go

With the current code, it can happen that condition Update fails
due to a collision with someone else editing NetworkAddonsConfig
object.
With this patch, we retry the Update several times until it's
successfully updated or out of tries.

retry Update of condition if needed

---

data/linux-bridge/0004-bridge-marker-daemonset.yaml

Upgrade bridge-marker daemonset's apiVersion to apps/v1. Without
this change, status_monitor cannot observe changes in its pods.

fix bridge-marker daemonset type

---

pkg/controller/statusmanager/status_manager.go

With current code, when conditions turn from Ready to Progressing,
status_manager.go defaulting doesn't overwrite Ready=True to False.
This patch fixes it.

fix ready condition defaulting

---

pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/controller/statusmanager/status_manager.go

We have to remove failures only after we add progressing condition. If
we do it the other way, we will have Ready=True for a moment before
Progressing=True takes place.

set not failing only after setting progressing

---

templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in

Without this parameter specified, CSV reports failing status:
```
requirementStatus:
- group: operators.coreos.com
kind: ClusterServiceVersion
message: CSV missing minimum kube version specification
name: cluster-network-addons-operator.0.9.0
status: NotPresent
version: v1alpha1
```

specify minKubeVersion in CSV

---

pkg/components/components.go
templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in

Let's use the default policy "IfNotPresent" in our examples. That
makes sure that users trying this out won't repull images all the
time.

use IfNotPresent pull policy in examples

---

templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in

Category should be just "Networking", this category is already available
on operatorhub.io.
For GitHub link, be more explicit and state that it is Cluster Network
Addons Operator's homepage.

fix description and category in CSV

---

Makefile
automation/test.sh

STD-CI does not understand colors in ginkgo output, let's disable it.

run tests on STD-CI without colors

---

cmd/manager/main.go
pkg/components/components.go
tools/manifest-templator/manifest-templator.go

With this patch, we keep operator version as env variable of the
operator's deployment. In this patch we print it during operator's
startup. In following patches, it will be exposed also on
NetworkAddonsConfig CR.

keep operator version as env variable

---

build/registry/Dockerfile

All manifests included in OLM bundle are automatically installed.
Therefore, we have to remove all extra manifests (e.g. namespace,
RBAC, deployment) from our bundle while building it.

drop additional manifests from bundle

---

data/sriov/004-sriov-network.yaml

Otherwise multus fails to parse the config and pass it to CNI plugin.

Added missing quotes for sriov network type and name fields

---

test/releases/releases.go

Let's not call gomega functions outside tests scope.

fix Release sort

---

data/kubemacpool/003-deployment.yaml
data/kubemacpool/003-secret.yaml
pkg/components/components.go
test/releases/0.12.0.go

This version should allow us to remove the w/a waiting for kubemacpool
https://github.com/K8sNetworkPlumbingWG/kubemacpool/releases/tag/V0.4.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/185)

Bump kubemacpool version to v0.4.0

---

pkg/components/components.go
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go

In order to fix an issue with missing
configs.imageregistry.operator.openshift.io RBAC, let's use NAO
config to identify whether running on OKD4.
Resolves #189

identify OKD4 using NAO

---

data/ovs/002-ovs-daemonset.yaml
pkg/components/components.go

This PR also remove the ocp image and copy the ovs-vsctl binary
directly from the ovs-cni image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/191)

Bump ovs to version v0.5.0

---

test/e2e/lifecycle/upgrade_test.go

This PR fix the life cycle tests.
Before this PR the upgrade test where failing.
To fix the test I added a CheckConfigVersions in the BeforeEach function to wait for the operator to change the version in the cluster object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/195)

Fix life cycle test

---

README.md

Related to https://github.com/kubevirt/cluster-network-addons-operator/pull/183
This PR add documentation about the ovs cni plugin to the README file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/196)

Add ovs documentation

---

build/operator/Dockerfile
build/operator/bin/csv-generator
tools/manifest-templator/manifest-templator.go

Every operator image that's integrated into the HCO is gaining the ability to dump a corresponding CSV file through the execution of the /usr/bin/csv-generator script/binary.
The CNA operator already has logic to generate the CSV, so this is as simple as including that logic into the operator container image. For consistency where this logic lives in all the other operator container images, the /usr/bin/csv-generator script was added as an entry point that redirects to the manifest-templator tool. 
HCO can use this to extract the corresponding CSV for a CNA operator build by executing the CNA operator's container.
**Example**
```
make docker-build-operator 
docker run --rm -it --entrypoint=/usr/bin/csv-generator quay.io/kubevirt/cluster-network-addons-operator:latest --version=1.1.1 > …
```

Add csv-generator to operator container image

---

test/e2e/lifecycle/deployment_test.go
test/e2e/lifecycle/upgrade_test.go
test/e2e/workflow/containers_test.go
test/e2e/workflow/deployment_test.go
test/e2e/workflow/version_test.go

Now when we added more components to the operator, the first deployment
of all of them will take more time. Increase the timeout accordingly.

increase test timeouts

---

tools/manifest-templator/manifest-templator.go

The csv-generator tool needs the ability to dump the operator related CRDs  as well for HCO integration.

Add csv-generator --dump-crds option

---

pkg/components/components.go
templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in

This PR bump the ovs version.
The new ovs version was builed with a static GCC and the go ssl lib.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/207)

Bump ovs version to v0.6.0

---

pkg/components/components.go
test/releases/0.12.0.go

Using https://github.com/containernetworking/plugins/releases/tag/v0.8.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/209)

Bump linux bridge cni to version v0.8.1

---

build/registry/Dockerfile

The 'latest' or '4.2.0' fails generating bundle.db at:
time="2019-08-09T07:01:21Z" level=fatal msg="could not decode contents of file
/registry/bundles.db into package:
error converting YAML to JSON: yaml: control characters are not allowed"
The error is already present at code base but was not fatal.
Looks like it's an operator-framework/registry-operator issue
https://github.com/operator-framework/operator-registry/issues/70

Pin quay.io/openshift/origin-operator-registry to 4.1.0

---

build/registry/Dockerfile

The 'latest' or '4.2.0' fails generating bundle.db at:
time="2019-08-09T07:01:21Z" level=fatal msg="could not decode contents of file
/registry/bundles.db into package:
error converting YAML to JSON: yaml: control characters are not allowed"
The error is already present at code base but was not fatal.
Issue was that initilizer is re-feeding itself with bundles.db that is not a JSON/YAML
this review move manifests to proper directory out of initializer

Fix registry Dockerfile to work with origin-registry-operator 4.2.0

---

README.md
data/ovs/002-ovs-daemonset.yaml

This mechanism only causes issues. Incompatibility with system it
is installed on, not being on PATH or read-only filesystems. Let's
drop it and replace by proper ovs.db socket based solution in
a following patch.

don't install ovs-vsctl binary

---

Makefile
README.md
manifests/cluster-network-addons/0.12.0/cluster-network-addons-operator.0.12.0.clusterserviceversion.yaml
manifests/cluster-network-addons/0.12.0/namespace.yaml
manifests/cluster-network-addons/0.12.0/network-addons-config-example.cr.yaml
manifests/cluster-network-addons/0.12.0/network-addons-config.crd.yaml
manifests/cluster-network-addons/0.12.0/operator.yaml
manifests/cluster-network-addons/cluster-network-addons.package.yaml
test/releases/0.13.0.go

* ovs component added
* added upgrade support for ovs and nmstate
* updated bridge-marker to 0.2
* updated bridge-cni to v0.8.1
* removed sr-iov (obsoleted by openshift/sriov-network-operator)
* updated nmstate to v0.8.0
* expose unified HCO conditions

Release 0.12.0

---

test/e2e/workflow/deployment_test.go

A tiny PR to add the polation test-ID
as a note above the test.

add testID to kubemacpool test

---

data/kubemacpool/003-deployment.yaml

High requested CPU resource requirement seems to cause issues, which
frequently cause the pod scheduling issue.
Signed-off-by: Lev Veyde <lveyde@redhat.com>

Reduce kubemacpool requested CPU resource and limit

---

pkg/components/components.go
test/releases/0.16.0.go

- Support untagged vlan filtering linux bridge traffic
- Increase nmstate set timeout to 60 seconds

Upgrade kubernetes-nmstate-handler container to 0.8.0

---

pkg/components/components.go
test/e2e/workflow/deployment_test.go
test/e2e/workflow/recovery_test.go
test/releases/0.16.0.go

This PR bump the kubemacpool version for our operator.
https://github.com/K8sNetworkPlumbingWG/kubemacpool/releases/tag/v0.6.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/237)

Bump kubemacpool to version v0.6.0

---

pkg/components/components.go
test/releases/0.17.0.go

This PR bump the kubemacpool version to a version that ignore errors on the pod webhook
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/241)

Bump kubemacpool to version v0.7.0

---

data/kubemacpool/003-deployment.yaml

Adding an app label to kubemacpool.
This will make it easier to identify the kubemacpool pods.

Add app label to kubemacpool

---

pkg/components/components.go
test/releases/0.19.0.go

It uses nmstate from master containing needed fixes.

bump kubernetes-nmstate to 0.11.0

---

data/linux-bridge/002-linux-bridge.yaml

Some projects (e.g. openshift/console) use cnv- prefix to distinguish between
binaries shipped by OpenShift and those shipped by KubeVirt (D/S matters).
Following two lines make sure we will provide both names when needed.

bridge cni: always deploy cnv- prefixed binaries

---

data/nmstate/003-operator.yaml

After changing limits at [1] some users has issues with
kubernets-nmstate going OOMKilled, duplicating resources
looks good enough.
[1] https://github.com/kubevirt/cluster-network-addons-operator/pull/254

Increase nmstate-handler resources

---

README.md
data/ovs/002-ovs-daemonset.yaml
pkg/components/components.go
test/releases/0.23.0.go

To include the bridge reporting fix [1]
[1] https://github.com/kubevirt/ovs-cni/pull/93

Bump ovs-cni to 0.8.0

---

data/multus/002-multus.yaml
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/network/multus.go
pkg/network/network.go
test/check/components.go
test/releases/0.25.0.go

When a change is introduced to an object's parameters during upgrade, it is sometimes not possible to perform the regular reconcile process to the newer version (such as changing a mutable name).
For this reason we need to add a Special delete functionality which should be added specifically per case when such as change occurs.
Testing this functionality is included as part of the lifecycle tests.

Handling special cases of outdated/incompatible objects during reconcile

---

components.yaml

In order to make U/S->D/S automation possible and clearer which versions are we using, we will keep them in a dedicated yaml. This file should be machine-readable, and must be updated every time a supported version of a component is changed.

Keep version of used components and their version at a single yaml file

---

components.yaml

It is simple to switch tag to a different commit and sneak into
CNAO. It is harder to do it with a commit ID.

pin specific commits in components

---

Makefile
automation/check-patch.e2e-lifecycle-k8s.sh
automation/check-patch.e2e-workflow-k8s.sh
cluster/kubevirtci.sh
test/check/check.go

There was an issue with previous version of Kubernetes where we
ran out of available IPs during lifecycle tests (with dozens of
pods being created and removed in a short period of time).
This PR is adding more logging information when one of our asserts
fail and it also bumps the used k8s version to 1.17.

bump to k8s 1.17

---

pkg/components/components.go

When SHA hashes are used instead of tags for versioning, we are not able to
fit the whole version string to annotations and that causes the operator to
fail:
NetworkAddonsConfig is degraded: could not apply (/v1, Kind=ConfigMap)
openshift-cnv/cluster-networks-addons-operator-applied-cluster: could not
create (/v1, Kind=ConfigMap)
openshift-cnv/cluster-networks-addons-operator-applied-cluster: ConfigMap
"cluster-networks-addons-operator-applied-cluster" is invalid: [metadata.labels:
Invalid value:
"sha256:7343c7089f04f1c7affab12fe9a6614f24ee62d84d0943b24c170a6e30fe374e": must
be no more than 63 characters, metadata.labels: Invalid value:
"sha256:7343c7089f04f1c7affab12fe9a6614f24ee62d84d0943b24c170a6e30fe374e": a
valid label must be an empty string or consist of alphanumeric characters, …

set max length for version string

---

pkg/components/components.go

When SHA is used for versioning, it contains character ':' which is
not allowed to be used as an annotation value. With this PR, we replace
it with '_'.

replace : in version name with _

---

Makefile
README.md
manifests/cluster-network-addons/0.26.0/cluster-network-addons-operator.0.26.0.clusterserviceversion.yaml
manifests/cluster-network-addons/0.26.0/namespace.yaml
manifests/cluster-network-addons/0.26.0/network-addons-config-example.cr.yaml
manifests/cluster-network-addons/0.26.0/network-addons-config.crd.yaml
manifests/cluster-network-addons/0.26.0/operator.yaml
manifests/cluster-network-addons/cluster-network-addons.package.yaml
test/releases/0.27.0.go

`./hack/release.sh 0.25.0 0.26.0 0.27.0 origin phoracek`
* More logging
* kubemacpool bump script
* fixed issues when SHA HASH is used as a version name

Release 0.26.0

---

test/check/check.go

With the current, kubectl describe sometimes fail to list objects that
are being removed. It is probably between listing of all objects and obtaining
of their descriptions. In any case, we can merely print both the description
and error if this helper function fails.

don't fail the test if we fail to list all objects

---

pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go

Kubernetes sometimes fails to apply objects while we remove and recreate
components, despite reporting success. In order to self-heal after these
incidents, keep requeing.

self-heal by re-reconciling

---

data/nmstate/003-operator.yaml

We dropped the webhook configuration, but forgot to disable the webhook
server. This is causing knmstate pod to fail.

disable knmstate webhook

---

Makefile
version/version.go

Wrong path was used for manifest assets.

fix release target in the makefile

---

data/multus/002-multus.yaml

With newer multus cniVersion is mandatory.

Add cniVersion to multus CNI

---

Gopkg.lock
automation/check-patch.e2e-lifecycle-k8s.sh
test/releases/releases.go

Currently we always test upgrade from all released versions to the master
branch.
That has two major issues:
The upgrade test of more than 20 versions back is ran on every PR. This takes a
lot of time and slows down the development cycle. With this PR we test upgrades
only from releases pinned to HCO on regular PRs. That should be sufficient since
we test the full upgrade on release PRs.
When releasing, we test upgrade from to-be-released version to master. That is
failing since the to-be-released version is not yet accessible in Quay. With
this PR we make sure to exclude this version from the test.
Lifecycle tests without this change take around 1h20m on a regular PR. With this change, the time was reduced to 30m. Time needed for the workflow lane is around 20m (parallel to the lifecycle …

limit versions tested in lifecycle lane

---

data/linux-bridge/0004-bridge-marker-daemonset.yaml
data/linux-bridge/002-linux-bridge.yaml
data/multus/002-multus.yaml
data/nmstate/003-operator.yaml
data/ovs/002-ovs-daemonset.yaml

There seems to be a bug in CRI-O causing pods to fail with
"lstat /proc/63538/ns/ipc: no such file or directory" when there is not enough
resources allocated to them.
With this PR we drop all the resource limitations. As long as the cluster is not
low on resources, we should not trigger the bug.
BZ: https://bugzilla.redhat.com/1776236

drop limitations of resources

---

components.yaml
hack/components.sh

Automate macvtap component generation.
By doing `make components`, the specified version of macvtap-cni is cloned, and it's manifests copied, becoming available as CNAO provisioning files.
Depends-on: #346 
Depends-on: https://github.com/kubevirt/macvtap-cni/pull/20

Make components macvtap

---

automation/check-patch.e2e-lifecycle-k8s.mounts
automation/check-patch.e2e-lifecycle-k8s.packages
automation/check-patch.e2e-lifecycle-okd.mounts
automation/check-patch.e2e-lifecycle-okd.packages
automation/check-patch.e2e-workflow-k8s.mounts
automation/check-patch.e2e-workflow-k8s.packages
automation/check-patch.e2e-workflow-okd.mounts
automation/check-patch.e2e-workflow-okd.packages
automation/check-patch.e2e.mounts

This configuration is not needed anymore. Cleaning up.
We keep .packages, so it is clear what are the dependencies to run our jobs.

drop stdci .mounts and .packages

---

test/e2e/workflow/deployment_test.go

There is a race on our CI where we sometimes don't catch Progressing state. That
can happen when the the image of a deployed component is already in registry and
therefore the start of it is swift. With this change, we run configuration
change with a little delay after we start listening for the progressing state.
This can still fail, but our chances are better. Better approach would be to
start a monitor instead of polling, that is however not yet supported in the
controller-runtime Client.

tests: try to catch progressing state more reliably

---

pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/network/network.go

We want to prevent deletion of CRs created by the user, even during removal of
the operator. Therefore, we don't set ownership reference on CRDs.
We also want to prevent deletion of CRDs during removal of a single component.

don't remove CRDs when their comonents are gone

---

components.yaml
data/nmstate/003-operator.yaml
pkg/components/components.go
test/releases/0.28.0.go

Bump kubernetes-nmstate to v0.15.5 so it handles the upgrade between CNAO installed kubernetes-nmstate and non CNAO installed kubernetes-nmstate using a lock.
```release-note
knmstate: Lock handler if another handler is running at the same node, needed for upgrades between cnao installed knmstate and non-cnao installed knmstate.
```

Bump knmstate to v0.15.5

---

hack/components.sh

We cannot use `go get` anymore due to -mod=vendor. This patch replaces it with
mere `git clone` which should be more reliable and predictable.

clone components instead of go get

---

data/nmstate/001-rbac.yaml

During refactoring, we forget to rename Namespace to HandlerNamespace in the SCC
template. Since we don't test SCCs in our automation, this was not catched in
our CI.
/kind bug
```release-note
Fix kubernetes-nmstate RBAC template
```

knmstate: fix Namespace variable in templates

---

components.yaml
data/macvtap/002-macvtap-daemonset.yaml
pkg/components/components.go

Bump macvtap-cni to 0.2.0
```release-note
Macvtap-cni now exposes all physical host links (also bonds) in each k8s node by default.
```

Bump macvtap-cni to 0.2.0

---

pkg/components/components.go

Without this setting, the json schema validation fails with:
CustomResourceDefinition.apiextensions.k8s.io "networkaddonsconfigs.networkaddonsoperator.network.kubevirt.io" is invalid: spec.validation.openAPIV3Schema.type: Required value: must not be empty at the root

add JSONSchema type to the root of our CRD

---

pkg/controller/statusmanager/status_manager.go
test/check/check.go

Currently we wait until all the pods in deployment become ready.
That is not necessary, we can turn Ready once at least one pod
in the deployment is able to serve requests.
This is needed, so we don't block when deployment uses leader
election in combination with readiness probe and only one pod is
marked as ready at the time.

status_manager: only require single ready pod for deployment

---

pkg/apply/merge.go
pkg/apply/merge_test.go

In the current code, we first transform both the current and the new
list of webhooks into a map of webhooks by names. The problem with that
is that a hashmap does not keep the original order. Due to that, the
result of the merging is inconsistent, causing tests to fail and it
would also cause us to reapply config, even when there is nothing needed
to be changed.
With this patch, we iterate the original list of webhooks without
translating it to a map, to keep the original order.

keep the order of webhooks while merging

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Similar to other kubevirt projects they include the release_note field
at the PR making easier to modify it.

Add github issue/PR templates

---

README.md
cluster/operator-push.sh

It will add DEV_IMAGE_REPOSITORY as the intermediate repo between
developer and cluster also KUBECONFIG has to be set pointing to the
external cluster
```release-note
Support for KUBEVIRT_PROVIDER=external
```

Add KUBEVIRT_PROVIDER=external support

---

.dockerignore
Makefile
build/operator/Dockerfile
hack/generate-manifests.sh
hack/install-go.sh

We are already not using multistage to run suff like vet or goimports, this PR remove it alltogether and uses a installed golang version that uses go.mod version to select it, it reduces build time and indirections.                                         
**Special notes for your reviewer**:                                            
**Release note**:                                                               
```release-note                                                                 
Golang tools vendored and multistage build removed.                                                                          
```

Replace multistage with vendored go

---

components.yaml
data/kubemacpool/kubemacpool.yaml
pkg/components/components.go
test/releases/99.0.0.go

This PR bumps kubemacpool to v0.14.0
```release-note
bump kubemacpool to v0.14.0
```

bump kubemacpool to v0.14.0

---

cluster/up.sh

If we want to run tier1 tests at CNAO u/s we need the same NetworkManager versions installed at kubernetes-nmstate master, for now that's is 1.22.
```release-note
NONE
```

Bump NetworkManager to 1.22 so we can test knmstate

---

pkg/components/components.go

Currently the cnao rbac Policy has a segment that elevates the container privileges to all resources, and all verbs.
This is too much for the cnao's needs, and also in turn changes scc to anyuid in cnv/okd clusters.
Hence, the rbac segment is removed in this commit.
```release-note
NONE
```

remove over privileged rbac from cnao manifest

---

components.yaml
data/kubemacpool/kubemacpool.yaml
pkg/components/components.go
test/releases/99.0.0.go

This patch release includes a fix for KMP disruption budget. The bug prevented nodes from being drained.
```release-note
Bump KubeMacPool to 0.14.1
```

bump kubemacpool 0.14.1

---

pkg/components/components.go

Reverts kubevirt/cluster-network-addons-operator#413
We have to rework this and allow CNAO to edit more resources. By dropping of the global role, we blocked us from creating anything on OpenShift.

Revert "remove over privileged rbac from cnao manifest"

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

This PR bumps kubemacpool to v0.14.2 it moves the finalizar creation into webhook from controllers so we are really sure that they are set.
```release-note
Bump kubemacpool to v0.14.2
```

Bumping kubemacpool to v0.14.2

---

hack/functest.sh
test/e2e/workflow/validation_test.go

Fix operator-sdk test --namespace flag. It has been changed to --operator-namespace. Using --namespace cause operator-sdk to return immediately with false positive.
```release-note
NONE
```

Fix false positive on the CI and missed bugs

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

The major difference is that this new release is built on Go 1.13 and
Kubernetes 1.18.
```release-note
bridge-marker was updated to 0.3.0
```

bump bridge marker to 0.3.0

---

pkg/components/components.go

Currently the cnao rbac Policy has a segment that elevates the container privileges to all resources, and all verbs.
This is too much for the cnao's needs, and also in turn changes scc to anyuid in cnv/okd clusters.
Hence, the rbac segment is replaced with more refined rbac rules.
```release-note
NONE
```

Fix rbac in CNAO's manifest

---

test/e2e/lifecycle/upgrade_test.go

For each release, we test upgrades from every previous release to the
newly created one. That takes a lot of time and is obviously getting
only worse.
This patch merges two of the three upgrade tests into a single one. They
are both just checking the state of the cluster, so we are not risking
too much by merging them.
This should save us 30 % of the time on the suite.
```release-note
NONE
```

merge some upgrade tests

---

pkg/components/components.go

The latest [rbac fix](https://github.com/kubevirt/cluster-network-addons-operator/pull/419) introduced a new problem with [configmap finalizer](https://bugzilla.redhat.com/show_bug.cgi?id=1848004).
This reverts commit 4435752626331963f28cfc71e3dfa9ca4a9aea2e.
Due to this, unfortunately the [anyuid BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1834839) will be reopened
```release-note
NONE
```

Revert "Fix rbac in CNAO's manifest (#419)"

---

components.yaml
data/kubemacpool/kubemacpool.yaml
pkg/components/components.go
test/releases/99.0.0.go

This version brings fixes to two serious bugs. Inability to select a leader and setting namespace of the operator as run-level: "0".
```release-note
Bump kubemacpool to v0.14.5
```

bump kubemacpool to v0.14.5

---

components.yaml
data/kubemacpool/kubemacpool.yaml
pkg/components/components.go
test/releases/99.0.0.go

This version brings fixes to two serious bugs. Inability to select a leader and setting namespace of the operator as run-level: "0".
```release-note
Bump kubemacpool to v0.14.5
```

[release-0.39] bump kubemacpool to v0.14.5

---

automation/check-patch.e2e-lifecycle-k8s.sh
automation/check-patch.e2e-workflow-k8s.sh

Disable ginkgo colors at CI run, It add garbage to prow output.
```release-note
NONE
```

Disable ginkgo colors at CI run

---

test/check/check.go

Currently CheckComponentsRemoval doesn't give enough info to debug failures.
Let's add describe all to the error to see what went wrong.
```release-note
NONE
```

add describe logs when components has failed to be fully removed

---

pkg/components/components.go
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/util/k8s/labels.go
pkg/util/k8s/labels_test.go

We started trimming the version so it can fit into labels. We will keep
that but we will stop trimming it for the use in our CRs. That way
whatever was set in CNAO deployment as a version will be exposed in its
CRs. So no unexpected results.
https://bugzilla.redhat.com/show_bug.cgi?id=1856438
```release-note
Do not trim OPERATOR_VERSION in the CR
```

Do not trim the version exposed in CR

---

data/kubemacpool/kubemacpool.yaml
data/nmstate/operator.yaml
hack/components/bump-knmstate.sh
hack/components/bump-kubemacpool.sh
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/names/names.go
test/check/components.go

In the current code, we mark all objects created by CNAO (those kept
under data/) as owned by us. As a result, they are garbage collected
upon removal of NetworkAddonsConfig.
This cause complications with objects that we do not want to remove or
that we want to be owned by other objects. The recent example of this
were KubeMacPool secrets that need to be precreated in CNAO in order to
avoid chicken-egg issues, but then handled separately.
In order to provide a generic mechanism to avoid ownership, a new
annotation `networkaddonsoperator.network.kubevirt.io/rejectOwner` was
introduced. When an object is annotated with this, we will not set the
reference.
Currently, we set owner reference of the secret to NetworkAddonsConfig.
That means that it will …

Introduce `networkaddonsoperator.network.kubevirt.io/rejectOwner` annotation and drop ownership of KMP secrets

---

components.yaml
data/nmstate/role.yaml
pkg/components/components.go
test/releases/99.0.0.go

It bumps kubernetes-nmstate to 0.23.0 this versions does not set ownership on TLS secret if it's deleted.
```release-note
Bump kubernetes-nmstate to 0.23.0
```

Bump knmstate to v0.23.0

---

data/kubemacpool/kubemacpool.yaml
hack/components/bump-kubemacpool.sh

Currently, during CNAO bump we use whatever kustomize is intalled.
Lets use the same vendored kustomize version that kubemacpool is using.
```release-note
NONE
```

use kustomize version used on kmp

---

components.yaml
data/nmstate/scc.yaml
hack/components/bump-knmstate.sh
pkg/components/components.go
test/releases/99.0.0.go

The openshift SCC was missing at the kubernetes-nmstate bumping manifests this
commit add it using the expected golang template flags to deactivate it on k8s and
activate it on openshift.
```release-note
Add SCC to kubernetes-nmstate
Bump kubernetes-nmstate to 0.25.0
```

Add kubernetes-nmstate openshift scc manifests from knmstate 0.25.0

---

.travis.yml
Makefile
hack/check.sh

Adds porcelain check, to make sure no generated uncommitted changes are left outside of a commit.
We also add bump-all on travis.yaml to make  sure the manifests weren't changed.
```release-note
NONE
```

add porcelain to check for uncommitted changes

---

pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/controller/statusmanager/status_manager.go

The StatusManager `SetFromPods` function is accesed from both the `pod_controller` and `networkaddonsconfig_controller`.
This PR adds mutex and locks sections that read/write shared variables: containers, deployments, daemonSets.
Also, writing and reading these shared variables is done together atomicallly in single locked sections (`GetAttribures` and `SetAttributes`)
Fix flaky test  https://github.com/kubevirt/cluster-network-addons-operator/issues/451
```release-note
none
```

Fix test NetworkAddonsConfig shouldn't be empty when config deployed

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

Bumps kubemacpool to 0.17.0, it uses kube-admission-webhook 0.12.0 that implements the CA overlap interval, although this interval has the expiration time value so behaviour has to be the same.
```release-note
Bump kubemacpool to 0.17.0
```

Bump kmp to 0.17.0

---

components.yaml
data/nmstate/operator.yaml
hack/components/bump-knmstate.sh
pkg/components/components.go
test/releases/99.0.0.go

It uses kube-admission-webhook 0.12.0 that implements the CA overlap interval, although this interval
has the expiration time value so behaviour has to be the same.
```release-note
Bump kubernetes-nmstate to v0.26.0
```

Bump kubernetes-nmstate to 0.26.0

---

hack/bump-version.sh

In the current state, when we bump a patch version (e.g. to 0.1.1) and
then call bump of minor version, the patch is not reset (e.g. 0.2.1).
With this patch, we will reset the patch/minor version on bump of
minor/major version respectively.
```release-note
Fix reset patch version when bumping minor
```

Fix reset patch version when bumping minor

---

test/e2e/workflow/version_test.go

Fixing by ignoring the observedVersion in the test in question, because after ConditionProgressing
is set to true, we cannot expect observedVersion to be empty, becasue it is possible that the
ConditionAvailable is reached in the meantime which as a result populates the observedVersion.
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/424/pull-e2e-cluster-network-addons-operator-workflow-k8s/1273247663738851328#1:build-log.txt%3A792
fixes test
```release-note
NONE
```

Fix test should set targetVersion and operatorVersion 

---

components.yaml
data/kubemacpool/kubemacpool.yaml
pkg/components/components.go
test/releases/99.0.0.go

This contains a critical fix preventing KMP from failing on deployment.
We have lowered the number of replicas to 1 and dropped leader election
code since it is not needed anymore.
```release-note
Bump KubeMacPool to v0.14.6
```

Bump KubeMacPool to v0.14.6

---

components.yaml
data/kubemacpool/kubemacpool.yaml
pkg/components/components.go
test/releases/99.0.0.go

This contains a critical fix preventing KMP from failing on deployment.
We have lowered the number of replicas to 1 and dropped leader election
code since it is not needed anymore.
```release-note
Bump KubeMacPool to v0.19.0
```

Bump KubeMacPool to v0.19.0

---

Makefile

Go mod expects versions to start with "v". Without that, go mod is able
to fetch the tag, but it interprets it as:
v0.3.1-0.20200811082954-d0b735298e44
With this change, we prefix release tags with "v" while keeping the
version in our CSVs with a naked version to satisfy OLM's expectations.
```release-note
Prefix version tags with "v"
```

Prefix version tag with "v"

---

tools/bumper/component_commands.go

Currently when running the bumper script,
there is no output to stdout when a component is cloned
to the temporary folder. As this may take a short while,
it could be seen as if the script is stuck.
Let's dump the clone command output to stdout,
thus making it more user-friendly.
```release-note
NONE
```

add stdout to git-clone process in bumper script

---

README.md
pkg/network/nmstate.go

Configure knmstate cert rotation parameters from the CR
It will take the config from the selfSignConfiguration field at the networkaddonsconfig CR.
```release-note
Use selfSignConfiguration to configure kubernetes-nmstate cert rotation parameters.
```

Knmstate configure cert env vars

---

hack/components/bump-bridge-marker.sh
hack/components/bump-knmstate.sh
hack/components/bump-kubemacpool.sh
hack/components/bump-linux-bridge.sh
hack/components/bump-macvtap.sh
hack/components/bump-multus.sh
hack/components/bump-ovs-cni.sh
hack/components/docker-utils.sh
pkg/components/components.go
test/releases/99.0.0.go

In order to enable deployment in disconnected environment, all the images in the CSV must be with digests instead of tag.
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
```release-note
Images in CSV are now digest instead of repo:tag
```

Use image digests instead of tags

---

pkg/components/components.go
pkg/components/components_suite_test.go
pkg/components/components_test.go
templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
tools/manifest-templator/manifest-templator.go

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>
In order to enable deployment in disconnected environment, all the images in the CSV listed under the `relatedImages` field.
```release-note
Add the relatedImages field to the CSV
```

Add the relatedImages field to the CSV

---

pkg/components/components.go

In order to comply with operator [CFC Best practice](https://docs.engineering.redhat.com/display/CFC/Best_Practices),
we set the CNAO operator deployment to 'runAsNonRoot: true'
in the cnao manifest.
```release-note
NONE
```

add 'runAsNonRoot: true' to deployment's securityContext.

---

templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
tools/manifest-templator/manifest-templator.go

Currently manifest templator created the field customresourcedefinitions.owned[0].version
using the [deprecated](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#specify-multiple-versions) crd `version` field.
Lets move to updated `versions` field.
```release-note
NONE
```

fix ClusterServiceVersion manifest to not use deprecated version

---

data/ovs/001-ovs-cni.yaml
hack/components/bump-ovs-cni.sh
pkg/network/ovs.go

Use Infra PlacementConfiguration from NetworkAddonsConfig in ovs-cni
By default, ovs-cni will be scheduled on master nodes.
This PR is dependent of PRs: #520
```release-note
NONE
```

Add placement configuration to ovs-cni

---

data/multus/001-multus.yaml
hack/components/bump-multus.sh
pkg/network/multus.go

Use Infra PlacementConfiguration from NetworkAddonsConfig in multus
By default, multus will be scheduled on master nodes.
This PR is dependent of PRs: #520
```release-note
NONE
```

Add placement configuration to multus

---

data/linux-bridge/002-linux-bridge.yaml
pkg/network/linux-bridge.go
pkg/network/network_test.go

Use Workloads PlacementConfiguration from NetworkAddonsConfig in linux-bridge
By default, linux-bridge pods will be scheduled on all nodes.
This PR depends on : #520 #526
```release-note
NONE
```

Add PlacementConfiguration for linux-bridge

---

data/linux-bridge/003-bridge-marker.yaml
hack/components/bump-bridge-marker.sh

Use Infra PlacementConfiguration from NetworkAddonsConfig in bridge-marker
By default, bridge-marker will be scheduled on master nodes.
This PR is dependent of PRs: #520 #532
```release-note
NONE
```

Add placement configuration to bridge-marker

---

components.yaml
data/nmstate/operator.yaml
hack/components/bump-knmstate.sh
pkg/components/components.go
pkg/network/nmstate.go
test/releases/99.0.0.go

__Bumping__ nmstate release version v0.31.0, to include https://github.com/nmstate/kubernetes-nmstate/pull/595
that PlacementConfiguration to be easily introduced to CNAO for nmstate-webhook and nmstate-handler pods.
__Changed__ bump-knmstate to update the template variables.
Using Infra PlacementConfiguration for nmstate-webhook and
Workloads PlacementConfiguration for nmstate-handler.
By default, nmstate-webhook will be scheduled on master nodes and nmstate-handler on all cluster nodes.
```release-note
NONE
```

Add Placement for knmstate

---

data/kubemacpool/kubemacpool.yaml
hack/components/bump-kubemacpool.sh

Currently we are using the default opt-mode
for vms and pods in release configuration of kubemacpool repo.
Specifically, vms was set to opt-out.
Since we didn't have the chance to test this
configuration enough, we want to return the vms to opt-in
```release-note
NONE
```

change kubemacpool vms to opt-in

---

components.yaml
data/macvtap/002-macvtap-daemonset.yaml
hack/components/bump-macvtap.sh
pkg/components/components.go
pkg/network/macvtap.go

Bump macvtap dep to v0.3.1
It contains the following PRs:
- Change vbom.ml/util dependency with github.com/fvbommel/util [0]
Fixes vbom dependency
- Adding quotes in macvtap.yaml.in [1]
Allows using yq to edit macvtap.yaml.in
- Fix container command quotes in macvtap.yaml.in [2]
Fixes single quotes in command list
[0] https://github.com/kubevirt/macvtap-cni/pull/25
[1] https://github.com/kubevirt/macvtap-cni/pull/24
[2] https://github.com/kubevirt/macvtap-cni/pull/27
Use Workloads PlacementConfiguration from NetworkAddonsConfig for macvtap pods.
By default, macvtap pods will are scheduled on all nodes.
This PR depends on : #520 #526
```release-note
NONE
```

Add PlacementConfiguration for macvtap

---

pkg/eventemitter/eventemitter.go

- Right now events are only emitted for the networkaddonsConfig, and
asserting nil on a runtime.Object could be dangerous, so there
is no point of taking a runtime.Object as an argument to emitEvent.
This commit changes the EmitEvent method to take networkAddonsConfig
as an argument, and emits events only for it. the name of the method
was changed accordingly
Signed-off-by: alonSadan <asadan@redhat.com>
```release-note
NONE
```

events, event-emitter: change emitter to emit only for config

---

hack/prepare-release.sh
manifests/cluster-network-addons/0.41.0/cluster-network-addons-operator.0.41.0.clusterserviceversion.yaml
manifests/cluster-network-addons/0.42.0/cluster-network-addons-operator.0.42.0.clusterserviceversion.yaml

1. commit __Fixed__ missing `v` prefix in released manifest container tags in versions v0.41.0 and v0.42.0.
2. commit __Updated__ `prepare-release.sh` to generated manifests with the prefixed CONTAINER_TAG value.
From version v0.41.0 forward, we are using v-prefixed versions in **git tags** and **CONTAINER_TAG**s
```release-note
Adds missing version prefix 'v' to manifests in released versions v0.41.0 and v0.42.0
```

Fix missing prefix 'v' for versions v0.41.0 and v0.42.0

---

test/check/check.go
test/e2e/workflow/main_test.go

add check if CNAO pod performs unexpected restart during the CI tests.
- **add check that cnao pod has not restarted**
Currently there is no chck in the tests that
the CNAO pod has gone through a restart.
Let add a check to catch those restarts as soon as they occur.
- **add cnao pod stability check ci tests**
We want to make sure that CNAO pod does not perform
unwanted restart.
To do that we add a consistency check at the end of workflow
test suite to make sure no restart have been made
during the tests.
Also , after each test we want to add a print to signal
where the pod started restarting
- **TEMP COMMIT temporarily induce the cnao pod to restart.**
the Exit was added in order to be induced in test It("should remain at Available condition") …

Check cnao pod restarts in CI tests

---

manifests/cluster-network-addons/0.41.0/cluster-network-addons-operator.0.41.0.clusterserviceversion.yaml

The releases started have v prefix just on 0.42.0
hence the v on the images isnt right.
Quay have by mistake both with and without v,
but the one without v should be used for 0.41.0
```release-note
None
```

Fix release 0.41.0 manifest

---

manifests/cluster-network-addons/0.42.0/operator.yaml

Since releases started to have "v" prefix, the opeator.yaml of v0.42.0 missed it
in the image fields.
See https://github.com/kubevirt/cluster-network-addons-operator/issues/554
```release-note
None
```

Fix release v0.42.0 operator manifest

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

This PR bumps kubemacpool to v0.20.2
```release-note
bump kubemacpool to v0.20.2
```

bump kubemacpool to v0.20.2

---

test/e2e/lifecycle/deployment_test.go
test/e2e/lifecycle/main_test.go
test/e2e/lifecycle/upgrade_test.go
test/e2e/workflow/containers_test.go
test/e2e/workflow/deployment_test.go
test/e2e/workflow/main_test.go
test/e2e/workflow/recovery_test.go
test/e2e/workflow/validation_test.go
test/e2e/workflow/version_test.go
test/operations/operations.go
test/releases/releases.go

This PR is changes config operations to support both v1, v1alpha1 NetworkAddonsConfig
- **refactor operations to accept unstructured**
Currently, functions that create/update/remove NetworkAddonsConfig type
only use the currently stored NetworkAddonsConfig version:v1
This is not an issue during upgrade tests since we're not upgrading
the crd itself, so we always support v1.
Let's support both APIs by using unstructred objects
when calling k8s client.
- **update e2e tests to use new config changes**
this commit introduces the change in config API to
all the relevant e2e tests
```release-note
NONE
```

Change config to use unstructured

---

test/check/check.go
test/e2e/lifecycle/deployment_test.go
test/e2e/lifecycle/upgrade_test.go
test/e2e/workflow/containers_test.go
test/e2e/workflow/deployment_test.go
test/e2e/workflow/recovery_test.go
test/e2e/workflow/validation_test.go
test/e2e/workflow/version_test.go
test/operations/operations.go

Following #566, this PR changes the api in check.go to use unstructured config.
- **refactor check.go to use unstructured config**
Currently, check.go api use v1 NetworkAddonsConfig only.
Let's support both v1, v1alpha1 APIs by using unstructred objects.
- **update e2e tests to use new check.go changes**
this commit introduces the change in check.go API to
all the relevant e2e tests
- **remove noisy By() prints**
GetConfig and GetConfigStatus both use By() prints
that cause much noise during e2e tests
As they are not really informative, we should remove them
```release-note
NONE
```

change check.go api to unstructured

---

test/e2e/workflow/validation_test.go

Due to a problem catching the time where a component
was removed from the spec in validation test
the wait for the available status was sometimes missed,
causing a flakiness in the test.
Currently this is solved by a sleep.
Let's improve this by waiting for the specific component removal
```release-note
NONE
```

refactor fix of flaky validation test

---

pkg/components/components.go
tools/manifest-templator/manifest-templator.go

this PR bumps apiextensions.k8s.io to v1.
v1beta1 will be [deprecated](https://github.com/kubernetes/kubernetes/issues/82022) in k8s v1.19, and remove by 1.22
Also, it's needed for #524 to work
- **bump CustomResourceDefinition to v1**
in order to run "kubectl explain crd"
we need to bump CustomResourceDefinition to v1.
Part of this change is to move the deprecated spec.validation and Subresources.status fields
to be per version in spec.versions[].schema
- **Add minimal crd validation schema**
In order for the crd to be validated,
we need to add the minimal schema, including
the cnao components.
This PR  depends on #566, #570 to be merged
```release-note
bump CustomResourceDefinition to v1
```

bump CustomResourceDefinition to v1

---

automation/check-patch.e2e-kubemacpool-functests.sh
pkg/components/components.go

This PR add a skip label to the tier1 KMP tests 
to avoid flaky tests on irrelevant opt mode Context.
- **kmp functests, skip KMP opt-mode tests not maching CNAO config**
KMP functests include tests for both opt-in and opt-out KMP webhook modes
and since CNAO deploys KMP with opt-in mode,
it is necessary to skip tests of the opposite mode (opt-out tests).
This commit adds a function that checks what is the current configuration of
KMP in the cluster and skip the relevant tests accordingly.
dependent of #565 to pass
```release-note
NONE
```

skip KMP opt-mode tests not maching CNAO config

---

automation/check-patch.e2e-kubemacpool-functests.sh

This is a manual backport of #567 
```release-note
NONE
```

[release-0.42] skip KMP opt-mode tests not maching CNAO config

---

pkg/apis/addtoscheme_networkaddonsoperator_v1.go
pkg/apis/addtoscheme_networkaddonsoperator_v1alpha1.go
pkg/apis/apis.go

We are currently using the old shceme version when
adding resources to schema.
Let's change it to use all served versions v1 and v1alpha1
```release-note
NONE
```

fix AddToScheme to add all served versions

---

README.md

Instead of using absolute path for linking manifests in
README.md, use links to released assets.
```release-note
NONE
```

Fix manifest link versioning in README.md

---

Makefile
tools/bumper/README.md

Currently running bumper script requires 2 commands.
The bumper exec output is added to the main directory
and may be mistakenly added to the project.
Let's change the command to run with 'go run',
and move it to a Makefile target for better usability
README is updated accordingly.
Also we add a link to how to produce a github token in README
Also added a link to token creation in case
of running script manually
```release-note
NONE
```

bumper, Add bumper make target

---

pkg/network/multus.go
pkg/network/network.go
pkg/network/nmstate.go

Currently, if cleanUpMultusOldName returns nil,
it gets appended to the errList, and since
len([]error{nil}) != 0, it tried to access
Error() method of nil.
Let's fix this by making sure we are not
appending nil to the list, and also by adding a
protection in errorListToMultiLineString
```release-note
NONE
```

specialCleanUp, Fix reset cause by []error{nil}

---

.gitignore

Goland creates it's config folder .idea/ in project directory, which makes the developers
remember not to `git add` this folder when preparing  a PR.
Let's ignore this folder and forget about it.
```release-note
NONE
```

Ignore .idea/ folder created by Goland IDE

---

tools/bumper/bumper.go
tools/bumper/parser.go

This PR adds logging capabilities to the bumper script
- **bumper, , Fix updateComponentsYaml log**
this commit is a minor fix in log text
in updateComponentsYaml method.
- **bumper, Change running command of bump exec**
Currently, running of 'make bump-<component>'
is only displayed if there is an error.
In order to improve logging visibility,
we want to always show the exec output.
This will improve debugging in the future.
```release-note
NONE
```

bumper, Add stdout to exec output

---

test/releases/0.16.0.go
test/releases/0.17.0.go
test/releases/0.18.0.go
test/releases/0.19.0.go
test/releases/0.20.0.go
test/releases/0.21.0.go
test/releases/0.22.0.go
test/releases/0.23.0.go
test/releases/0.24.0.go
test/releases/0.25.0.go
test/releases/0.26.0.go
test/releases/0.27.7.go
test/releases/0.28.0.go
test/releases/0.29.0.go
test/releases/0.30.0.go
test/releases/0.31.0.go
test/releases/0.32.0.go
test/releases/0.33.0.go
test/releases/0.34.0.go
test/releases/0.35.0.go
test/releases/0.35.1.go
test/releases/0.36.0.go
test/releases/0.38.0.go
test/releases/0.39.3.go
test/releases/0.40.0.go
test/releases/0.40.1.go
test/releases/0.41.0.go
test/releases/0.42.0.go
test/releases/99.0.0.go
test/releases/releases.go

Currently, after cnao is uninstalled, the crd's
of it's components are not deleted.
This causes a "downgrade" situation when
upgrade test move from 1 test to the other.
For example, in the first test, release is upgraded
from old version to current version, but in the next test
the old version is not been able to be set because the new crd's
are still there.
In order to solve this, and since CNAO is not supporting downgrades,
we are attempting to remove the crds manually after each upgrade test.
```release-note
NONE
```

crdCleanUp, Cleaning release after upgrade test

---

test/e2e/workflow/validation_test.go

This PR tries to fix issue #523 
- **validation test, Fix flaky in It("should remain at Available condition")**
The cause of the flaky is that the config status is
checked before the change is performed.
Moving to waiting on the modified event should solve this.
```release-note
NONE
```

validation test, Fix flaky in It("should remain at Available condition")

---

tools/bumper/git_fakes.go

In unit test checking getUpdatedReleaseInfo
entries sometimes failed. This is because
getUpdatedReleaseInfo assumes that the tags list
received by ListMatchingRefs is sorted by time inserted.
However fake ListMatchingRefs method doesn't explicitly
sort it, so sometimes we get different order that causes
the test to fail.
Let's sort the tag list to fix this.
A comment to keep the tags to be inserted in
alphabetic-chronological order is also added.
```release-note
NONE
```

bumper, Fix flaky in bumper unit test

---

tools/bumper/bumper.go
tools/bumper/cnao_repo_commands.go
tools/bumper/cnao_repo_commands_test.go
tools/bumper/git_fakes.go

This method will be performed on the cnaoRepo instance
between each bumping of a component, to remove any bumping residue
Since bump output files are located in specific locations,
we add an allowList, to make sure only the bumping outputs
get removed.
Also adding a final resetRepoInAllowedList after all components
got bumped to finish the bumper script with no residual files.
In order to use the resetRepo function with defer, we move the
bump operation to a function.
PR depends on #616 to merge
```release-note
NONE
```

bumper, Add resetRepoInAllowedList to remove bump outputs

---

components.yaml

Currently latest multus version v3.6 breaks CNAO pods (open issue #621 ).
until this issue is resolved let's pin multus to v3.4.2
```release-note
NONE
```

pin multus to 3.4.2 since latest version breaks CNAO

---

pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
pkg/apis/networkaddonsoperator/v1/networkaddonsconfig_types.go
pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
pkg/components/components.go
test/check/check.go
test/e2e/lifecycle/upgrade_test.go
tools/manifest-templator/manifest-templator.go

Let's make make it possible to run `kubectl explain networkaddonsconfigs`
- **add components annotations to types**
`operator-sdk generate crds` generates descriptions from the annotations added to `networkaddonsconfig_types.go`
This commit adds these annotations.
- **fix NetworkAddonsConfig scope to Cluster in api types**
Currently there is a inconsistency between the manifest templator
outputed crd manifest and the type annotations in scope field.
Altough the manifests are controlled by the manifest generator
lets fix the annotation avoid future confusion.
- **add openAPIV3Schema validation parameters**
Let's add openAPIV3Schema detail for "kubectl explain crd"
Since operator-sdk crd cannot run. this commit manually creates the openAPIV3Schema …

make it possible to run `kubectl explain crd`

---

tools/bumper/bumper.go
tools/bumper/cnao_repo_commands.go
tools/bumper/cnao_repo_commands_test.go

Adding collectModifiedToTreeList that will collect the files
generated by the bump-<component> modified+untracked files
and add them to a githubTree List for future digest in githubApi.
depends on PR #617
```release-note
NONE
```

bumper, Add collectModifiedToTreeList to collect bump files

---

tools/bumper/bumper.go
tools/bumper/cnao_repo_commands.go
tools/bumper/cnao_repo_commands_test.go
tools/bumper/component_commands.go
tools/bumper/git_fakes.go

This PR implements PR creation in the bumper script.
- **bumper, Add githubApi functions to open PR**
This commit implements the functions that create
a proper PR using githubApi.
depends on #619 to be merged, relevant commit is the last one
```release-note
NONE
```

bumper, Add githubApi functions to open PR

---

Makefile

Currently auto-bumper will fail if go is not installed
Added the go install target dependency to fix that
```release-note
NONE
```

bumper, Add go install make target dependency to auto-bumper in Makefile

---

tools/bumper/component_commands.go

This PR is meant to fix gitAction [job failing](https://github.com/kubevirt/cluster-network-addons-operator/runs/1304048168?check_suite_focus=true) on following error:
```
INFO: 2020/10/25 05:14:54 ~~~~~~~~Bumper Script~~~~~~~~
INFO: 2020/10/25 05:14:54 Exiting with Error: Failed to create github api instance: Failed to get user from github client API: GET https://api.github.com/user: 403 Resource not accessible by integration []
exit status 1
```
- **bumper, Remove unsupported command from bumper script**
Currently the bumper script gitAction fails.
This is because we attempt to get the githubAPI User
which is not supported by gitAction.
As this function is only meant to check the githubApi
valid connection, it is not necessary.
Removed from bumper …

bumper, Remove unsupported command from bumper script

---

data/linux-bridge/002-linux-bridge.yaml

Since linux-bridge manifest in created in CNAO repo
Added pod description to linux bridge pod in data/linux-bridge
manifest folder.
```release-note
NONE
```

add linux-bridge pod description

---

automation/components-functests.setup.sh
cluster/cli.sh
cluster/cluster.sh
cluster/down.sh
cluster/kubectl.sh
cluster/ssh.sh
cluster/up.sh
hack/bump-kubevirtci.sh
hack/functest.sh

This PR adds a few fixes to cluster folder, as a preliminary work for future tier1 tests PRs: #633, #634, #631.
- **cluster scripts, Fix scripts to work from remote paths**
Currently, kubectl.sh, up.sh, down.sh and cli.sh scripts cannot work
from remote paths, since they depend to be working
from CNAO's repo root path.
This was not an issue until now, since script were
only operated from Makefile targets.
This currently prevents us from running these scripts
from another folder, a functionality needed for tier1
tests.
Fixed the scripts to use the script path instead of
relative path.
- **cluster scripts, Fix ambiguous between cluster and vendored _kubevirtci folders**
Currently, both _kubecirtci/ and cluster/ scripts
use the KUBEVIRTCI_PATH var. The …

fix cluster scripts

---

pkg/network/network.go
pkg/network/placement_configuration.go
pkg/network/placement_configuration_test.go
test/check/check.go
test/e2e/workflow/deployment_test.go

Currently placement-configuration should not allow
day2 changes.
Changed to allow day2 changes
```release-note
Allow placement-configuration day2 changes
```

[release-0.42] placement-configuration, Allow day2 changes

---

pkg/network/network.go
pkg/network/placement_configuration.go
pkg/network/placement_configuration_test.go
test/check/check.go
test/e2e/workflow/deployment_test.go

Currently placement-configuration should not allow
day2 changes.
Changed to allow day2 changes
This PR depends on placement-configuration PR #640 to be merged.
```release-note
Allow placement-configuration day2 changes
```

Allow day2 placement config changes

---

automation/check-patch.e2e-ovs-cni-functests.sh

This script adds ovs-cni e2e functests on a cluster with CNAO latest changes.
This PR can only be merged after:
1. ovs-cni issues a new release with functests [PR](https://github.com/kubevirt/ovs-cni/pull/124) is mereged
2. ovs-cni is bumped
3. lane added in project infra [PR](https://github.com/kubevirt/project-infra/pull/582)
```release-note
NONE
```

tier1, add ovs-cni e2e-functests script

---

automation/check-patch.e2e-bridge-marker-functests.sh

this PR adds a script that runs bridge-marker e2e test on CNAO cluster
This PR depends on bridge-marker [PR](https://github.com/kubevirt/bridge-marker/pull/20) merger.
```release-note
NONE
```

tier1, Add bridge-marker tier1 automation test

---

.github/workflows/component-bumper.yml

Currently, if we re-run a gitAction job, it is not rebased
to the most updated master.
Added a local rebase action to fix that.
This PR may break the bumper script, but it's necessary to debug this functionality on the repo
```release-note
NONE
```

bumper, Add local git rebase action in bumper gitAction Job

---

automation/check-patch.e2e-multus-functests.sh

This PR adds a tier1 automation of multus e2e test
The test runs multus's [test-simple-macvlan1.sh](https://github.com/intel/multus-cni/blob/master/e2e/test-simple-macvlan1.sh) script
```release-note
NONE
```

tier1, Add multus tier1 automation test

---

components.yaml
data/ovs/001-ovs-cni.yaml
pkg/components/components.go
test/releases/99.0.0.go

bump ovs-cni to v0.15.0
```release-note
bump ovs-cni to v0.15.0
```

bump ovs-cni to v0.15.0

---

automation/check-patch.e2e-macvtap-cni-functests.sh

This script runs macvtap e2e test on CNAO cluster
This PR depends on [macvtap PR](https://github.com/kubevirt/macvtap-cni/pull/32) changes to be merged first
```release-note
NONE
```

tier1, Add macvtap tier1 automation test

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

bump ovs-cni to v0.15.1
```release-note
bump ovs-cni to v0.15.1
```

bump ovs-cni to v0.15.1

---

.github/workflows/component-bumper.yml
tools/bumper/README.md
tools/bumper/bumper.go
tools/bumper/cnao_repo_commands.go

This PR adds the ability to run the bumper script on other branches other than master.
- **bumper, allow bumper to bumper from non-master branches**
Currently, the bumper script assumes it is run on
master branch.
We want to also allow running this on stable branches
Change base-branch to be input parameter to bumper script
- **bumper, Change gitHubAction job to be base-branch aware**
Following the change in bumper script, we adjust the
githubAction job to specify which brnahc it run from.
**Note:** we use 2 gitActions since there is an [issue](https://github.com/actions/checkout/issues/299) with actions/checkout@v2
that we solve in this [manner](https://github.com/kubevirt/cluster-network-addons-operator/pull/637)
**Special notes for your …

bumper, Make base-branch configurable

---

components.yaml
pkg/components/components.go

bump macvtap-cni to v0.4.2
```release-note
bump macvtap-cni to v0.4.2
```

bump macvtap-cni to v0.4.2

---

.github/workflows/component-bumper.yml

The `set-env` command is deprecated and will
be disabled on November 16th.
Changed to use Environment Files, according to [1]
[1] https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```release-note
NONE
```

bumper, move from deprecated set-env function

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

bump ovs-cni to v0.16.2
```release-note
bump ovs-cni to v0.16.2
```

bump ovs-cni to v0.16.2

---

pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
test/check/check.go
test/e2e/workflow/recovery_test.go
test/e2e/workflow/validation_test.go

This PR fixes a transient situation where an object which just got deleted
is still tracked by the CNAO reconciler, thus causing a temporary failed status
This fix also stabilizes the flaky [issue](https://github.com/kubevirt/cluster-network-addons-operator/issues/650) reported in validation e2e tests. 
- **delete objects, Fix Tracking of already removed objects**
Currently, the reconciler updates the list of objects to deploy
only after any objects are removed. This causes a temporary period
where the object is declared as gone.
Changed the order of trackDeployedObjects and deleteObjects to
keep the tracked objects updated correctly.
- **expectAvaialableEvent, Change to Watch policy to since now**
In order to check Available event after object …

delete objects, Fix tracking of already removed objects

---

.github/workflows/component-bumper-master.yml

Currently bumper job fails due to
misuse of the env vars recently inserted.
Fixed env vars to githubAction standard, 
similar to how it's done on HCO githubAction Job [[1]](https://github.com/kubevirt/hyperconverged-cluster-operator/actions/runs/376928097/workflow#L45).
[1] https://github.com/kubevirt/hyperconverged-cluster-operator/actions/runs/376928097/workflow#L45
```release-note
NONE
```

bumper, fix githubAction job env vars

---

hack/components/bump-nmstate.sh

Due to changes made on the crd file names
on kubernetes-nmstate repo, we need to update
the bump-nmstate script accordingly
```release-note
NONE
```

bump-knmstate, update nmstate bump script crds

---

tools/bumper/cnao_repo_commands.go
tools/bumper/cnao_repo_commands_test.go
tools/bumper/git_fakes.go

Currently, the bumper script fails when trying to collect
deleted files for the bump PR.
Added support of deleted files in the script (using [example](https://github.com/google/go-github/blob/e4b511744f5bbb020d00e172a284468137d4e5fc/github/git_trees_test.go#L188) code).
note a [knmstate bump PR](https://github.com/kubevirt/cluster-network-addons-operator/pull/675) created by running the bumper script locally.
```release-note
NONE
```

bumper, add support of deleted files

---

tools/bumper/cnao_repo_commands.go

Currently PRs opened by the bumper script are
in draft mode. Since the script is stable we
want to move script to issue real PRs.
Removed Draft flag from created PRs
```release-note
NONE
```

bumper, Remove Draft flag from bumper generated PRs

---

.github/workflows/component-bumper-release-0.42.yml

Currently the gitAction jobs can only be
configured on the master(/base) branch
To run the bumper on the release-0.42 branch
the job is added in master branch.
```release-note
NONE
```

bumper, Add bumper githubAction job for release-0.42 branch

---

test/e2e/workflow/deployment_test.go

CNAO performs strict reconciling to make sure that un-allowed day2
changes are not done on its components.
In order to ensure this functionality does not break, we want to add
a test on a arbitrary component object.
Added a test to make sure strict-reconcile feature is preserved.
```release-note
NONE
```

strict-reconcile, Add strict-reconcile test

---

Makefile
automation/check-patch.e2e-lifecycle-k8s.sh

Currently the ci tests timeout is hardcoded to 3h. since release lifecycle
test are growing past the 3h limit, we want to make the timeout configurable.
Change the ci timeout to be configurable
Updated the lifecycle lane in release case to 4h
```release-note
NONE
```

ci, make timeout configurable

---

Makefile

make bump-linux-bridge needs to also push the image to quay.
we do this by adding the PUSH_IMAGES env var to the script.
Since we want the bumper to be able to correctly bump linux-bridge component,
we add this env var to the run in Makefile target
```release-note
NONE
```

bumper, add PUSH_IMAGES allow linux-bridge docker push

---

README.md
automation/check-patch.e2e-lifecycle-k8s.sh
automation/check-patch.e2e-workflow-k8s.sh

ci, Bump provider to k8s-1.19 on ci lanes
```release-note
NONE
```

ci, Bump provider to k8s-1.19 on ci lanes

---

.github/workflows/component-bumper-master.yml
.github/workflows/component-bumper-release-0.42.yml

when bumping linux-bridge component we need to be registered as a quay user
that has write permissions, in order to push them.
Added a step to login to quay using the "kubevirt+network" quay robot credentials.
```release-note
NONE
```

bumper, Add quay login to bumper job

---

hack/components/yaml-utils.sh

This PR should fix PR totally failing situation that we currently experience.
- **dockerized yq, Pin yq to version 3.3.4**
Currently some scripts use dockeraized yq in order to parse yamls with ease.
Recently yq issued a new version v4 that breaks former api.
Since we do not need any of the new features presented on v4, we should pin our
script to use the last working yq version 3.3.4
```release-note
NONE
```

dockerized yq, Pin yq to version 3.3.4

---

components.yaml

There is a bug that caused the wrong commit to be set on the linux-bridge component in components.yaml, resulting with the bumper job to [fail](https://github.com/kubevirt/cluster-network-addons-operator/actions/runs/433440729).
The bug is fixed on #709, and the manual fix is done on this PR:
- **components, fix linux-bridge wrong tagged commit**
Due to a bug in the bumper, the tag-sha was inserted to the commit field.
This caused the bumper script to fail linux-bridge bump-checks, as the githubApi
uses the commit sha to identify the commit.
Manually fixed the commit field.
```release-note
NONE
```

components, Fix linux-bridge wrong tagged commit

---

tools/bumper/component_commands.go
tools/bumper/component_commands_test.go
tools/bumper/git_fakes.go

Currently when using tagged update policy mode, the bumper script is returning
the annotated tag sha and not the relevant commit sha of this tag.
The sha of an annotated tag is different than the sha of it's matching commit,
whereas the sha of lightweight tag is the same as the sha of it's matching commit.
This will cause the future bump to fail, as the annotated tag is not directly connected
via the githubApi.
Moreover, the mocked listMatchingRefs routine did not catch the issue since it used git log, which
show that commit sha's and not the tags themselves in order to assemble the tag list.
Fixed to return the commit sha.
Fixed the listMatchingRefs mock to use 'show-ref --tag', and adjusted the test to catch this issue.
**Special notes for your …

bumper, fix returning annotated tag sha on tagged update-policy

---

test/check/check.go
test/check/events.go
test/e2e/workflow/validation_test.go

Currently the validation test It("should remain at Available condition") watches for an
Available event after a component's removal. Since there is a current issue with watching
for repeating events [[1]](https://github.com/kubernetes/kubernetes/issues/97367#issuecomment-747421652), the test is flaky.
Change test to watch for the absence of warning (failure) events instead.
```release-note
NONE
```

validation test, Change test look for warning events

---

components.yaml

In order for the bumper script to better track the components in
the stable release-0.44 branch, we set components.yaml to track the
stable branch in ones that have stable branches. The rest will be set
to static and will be bumped manually.
```release-note
NONE
```

[release-0.44] bumper, set components.yaml to track stable branches

---

automation/check-patch.unit-test.sh

We don't copy anything to artifacts folder during the unit test so
better remove it.
side note: should also fix the issue preventing prow ci [PR](https://github.com/kubevirt/project-infra/pull/811) to pass rehearsals
```release-note
NONE
```

unit-test, Remove copy to artifact in script

---

.github/workflows/component-bumper-release-0.44.yml

In order for the bumper to track and auto bump in the release-0.44 stable branch
we add a new workflow to track it.
This PR is pending until the PR to update release-0.44's components file is merged (#728).
```release-note
NONE
```

bumper, Add a new bumper workflow for release-0.44

---

cluster/up.sh

installation of NetworkManager during cluster-up is not needed since
it is already installed during kubeivrtci provisioning [1]
[1] https://github.com/kubevirt/kubevirtci/blob/ad214dc8732b9c8729cdfbe302c7820d3f80f26e/cluster-provision/k8s/1.19/provision.sh#L156
fixes #741 
```release-note
NONE
```

cluster-up, remove NetworkManager installation

---

tools/bumper/cnao_repo_commands.go
tools/bumper/cnao_repo_commands_test.go
tools/bumper/component_commands.go
tools/bumper/git_fakes.go

Currently isPrAlreadyOpened is only checking existance of PRs on
master branch.
Fixed to check specifically on branch
Expanded ci unit test to check isPrAlreadyOpened on branched PRs.
Should fix #739
```release-note
NONE
```

bumper, fix isPrAlreadyOpened on non master branches

---

automation/components-functests.setup.sh

This PR fixed the tier1 automation setup to run NetworkAddonsConfig with v1, which is the latest supported version
```release-note
NONE
```

automation, Update CNAO CR to v1 in tier1 setup

---

data/kubemacpool/kubemacpool.yaml
hack/components/bump-kubemacpool.sh

This PR changes kubemacpool's vm handling opt-mode to opt-out
This means that vm's created will be assigned with a mac using kubemacpool, 
unless specifically set to ignore in namespace label.
```release-note
kubemacpool to opt-out mode
```

kubemacpool, move to vm opt-out mode

---

components.yaml
hack/components/bump-linux-bridge.sh
pkg/components/components.go
test/releases/99.0.0.go

Update linux bridge CNI to the current master:   
The last release was quite a long time ago and the branch now contains
many bugfixes.
Build our own binaries for CNI plugins:   
With this we are not dependent on CNI plugins releases and can pin to
the latest patches any time.
```release-note
Bump CNI plugins to 74a6b2
```

Bump CNI plugins version

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

This is an manual cherry-pick of #773 
```release-note
bump ovs-cni to v0.18.0
```

[release-0.44] bump ovs-cni to v0.18.0

---

cluster/cluster.sh

Current kubevirtci version runs etcd in memory looks like at some
release branches we reach the ramdisk size limit also the last
kubevirtci disable etcd in memory by default. This change bumps
kubevirtci so we use the sane defaults.
kubevirtci commit that disable etcd in memory by default https://github.com/kubevirt/kubevirtci/commit/54dfc80fc5eb11d92e534f6948208fb28b7735f0
```release-note
NONE
```

Don't run etcd in memory by default

---

Makefile
README.md
manifests/cluster-network-addons/0.47.0/cluster-network-addons-operator.0.47.0.clusterserviceversion.yaml
manifests/cluster-network-addons/0.47.0/namespace.yaml
manifests/cluster-network-addons/0.47.0/network-addons-config-example.cr.yaml
manifests/cluster-network-addons/0.47.0/network-addons-config.crd.yaml
manifests/cluster-network-addons/0.47.0/operator.yaml
manifests/cluster-network-addons/cluster-network-addons.package.yaml
test/releases/0.47.0.go
version/description
version/version.go

Features:
* bump ovs-cni to v0.18.0 (#773)
* Bump CNI plugins version (#772)
* bump nmstate to v0.40.0 (#769)
Bugs:
* Don't run etcd in memory by default (#776)
```release-note
Release 0.47.0
```

Release 0.47.0

---

Makefile
README.md
manifests/cluster-network-addons/0.44.3/cluster-network-addons-operator.0.44.3.clusterserviceversion.yaml
manifests/cluster-network-addons/0.44.3/namespace.yaml
manifests/cluster-network-addons/0.44.3/network-addons-config-example.cr.yaml
manifests/cluster-network-addons/0.44.3/network-addons-config.crd.yaml
manifests/cluster-network-addons/0.44.3/operator.yaml
manifests/cluster-network-addons/cluster-network-addons.package.yaml
test/releases/0.44.3.go
version/description
version/version.go

Features:
* Bump CNI plugins version (#772) (#774)
* bump ovs-cni to v0.18.0 (#775)
* bump nmstate to v0.37.5 (#770)
Bugs:
* Don't run etcd in memory by default (#777)
* Build and push multus container to quay.io (#767)
* Add e2e tests custom reporter (#763)
* Check cnao readiness at lifecycle deployment test (#755)
```release-note
```

Release 0.44.3

---

automation/check-patch.e2e-lifecycle-k8s.sh
data/kubemacpool/kubemacpool.yaml
hack/components/bump-kubemacpool.sh

The PR adds cert default to kubemacpool's bump script and manifest, to prevent upgrade issues
- **lifecycle test, Add recent releases**
currently during non-release PR we only check old release
Until we insert something more synamic, manually removing
some of the old releases and introducing new ones.
- **certs, add cert default to kubemacpool's bump script and manifest**
add cert defaults in kubemacpool manifest so that during upgrade
the parameters are not reset.
The first commit **should fail** standalone until we introduce the cert defaults change in the second commit.
```release-note
NONE
```

certs, Add cert defaults to kubemacpool's bump script and manifest

---

test/check/check.go

Depending on the CNAO version the Secret has different annotations and
sometimes they are removed and sometimes not, this change just remove
the check since Secret is something managed by kube-admission-webhook
and not CNAO.
```release-note
NONE
```

Remove Secret leftover checks at lifecycle test

---

.github/workflows/component-bumper-master.yml
.github/workflows/component-bumper-release-0.42.yml
.github/workflows/component-bumper-release-0.44.yml

The bumper script workflow is not meant to run on forks.
To make sure this, we add a build condition to the current workflows.
```release-note
NONE
```

gitActions, Restrict bumper workflows only to non-fork repo

---

pkg/network/self_sign_configuration.go

CNAO uses different values than the ones used at HCO. This change align
both so we detect issues with that sooner.
```release-note
Use rotate cert default configuration from HCO
```

Use HCO cert rotation default values

---

pkg/network/self_sign_configuration.go
pkg/network/self_sign_configuration_test.go

If previous selfSignConfiguration is missing a field like in the case of
certOverlapInterval (it was not introduced at the beginning) then the
default values are not going to be used and the defaults from the
manifests apply so we can end up with a bad overall configuration. This
change use default values if previous ones were missing one of the
fields.
A follow up PR will be done testing that after upgrade certs are not rotated.
```release-note
NONE
```

Use default at bad old self signed conf

---

hack/deploy-kubevirt.sh

sometimes automation tests fail on kubevirt not being ready.
increasing timeout to 360s, and by that aligning to [HCO](https://github.com/kubevirt/hyperconverged-cluster-operator/blob/c8c49f989ab8ff5415dae8c4f1063fc08ff76963/tests/travis-tests/test.sh#L9) and [KMP](https://github.com/k8snetworkplumbingwg/kubemacpool/pull/283)
```release-note
NONE
```

kubevirt, Increase kubevirt deploy timeout

---

pkg/apply/merge_test.go

This PR updates admissionregistration to v1 in merge_test.go manifest
```release-note
NONE
```

test/unit, update admissionregistration to v1 in merge_test.go

---

components.yaml

This PR set the components to follow CNAO's components' stable branches.
Where there is no stable branch, we set the component to be static.
```release-note
NONE
```

auto-bumper, Set components to follow stable branches

---

.github/workflows/component-bumper-release-0.53.yml

This PR sets the auto-bumper to run hourly on the release-0.53 branch,
similarly to all the other workflows.
```release-note
NONE
```

auto-bumper, set release-0.53 workflow to hourly

---

components.yaml

This PR updates the components.yaml with macvtap-cni's new main branch
```release-note
NONE
```

[release 0.44] macvtap-cni, update repo main branch

---

automation/check-patch.unit-test.sh

Ths PR adds a missing script needed for the `pull-cluster-network-addons-operator-unit-test` lane
```release-note
NONE
```

[release-0.42] automation, add missing unit-test script

---

components.yaml

This PR updates the components.yaml with macvtap-cni's new main branch
```release-note
NONE
```

[release-0.42] macvtap-cni, update repo main branch

---

components.yaml

This PR changes kubemacpool to follow stable branch release-v0.20
```release-note
NONE
```

[release-0.42] components, Change kubemacpool to follow stable branch

---

components.yaml
data/kubemacpool/kubemacpool.yaml
pkg/components/components.go
test/releases/99.0.0.go

This PR pins kubemacpool to a specific commit and tag v0.20.2-1-gf6c5fc0d.
```release-note
NONE
```

[release-0.42] kubemacpool, bump kubemacpool to v0.20.2-1-gf6c5fc0d

---

test/check/check.go

This PR bumps deprecated MutatingWebhookConfiguration to v1 in check test
```release-note
NONE
```

ci, Bump deprecated MutatingWebhookConfiguration to v1 in check test

---

components.yaml

This PR changes ovs-cni repo to k8snetworkplumbing
```release-note
NONE
```

[release-0.53] Change ovs-cni repo to k8snetworkplumbing

---

components.yaml

This PR changes ovs-cni repo to k8snetworkplumbing
```release-note
NONE
```

[release-0.42] Change ovs-cni repo to k8snetworkplumbing

---

pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller_suite_test.go
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller_test.go
pkg/controller/networkaddonsconfig/testdata/data.yaml
pkg/names/names.go
test/check/check.go

Each component deployed by CNAO should have labels on its resources.
The labels are called relationship labels (app.kubernetes.io/*),
and are used in order to create a relationship graph in the UI.
The labels are:
`app.kubernetes.io/component`
`app.kubernetes.io/managed-by`
`app.kubernetes.io/version`
`app.kubernetes.io/part-of`
This PR adapts Render function to add those labels to all the directly deployed components.
Follow PRs on each component repository will handle its own internal deployed components.
```release-note
None
```

Add relationship labels to all directly deployed components

---

data/linux-bridge/002-linux-bridge.yaml

Add `system-cluster-critical` to `linux-bridge-plugin` DaemonSet.
Since linux bridge's pod isn't bound to a specific node,
(it mostly copies some binaries to the node)
yet its an important pod, assign `system-cluster-critical`
pc to it.
This will make the control plane less sensitive to preemption
than user workloads.
```release-note
None
```

linux-bridge, Add Priority class

---

data/multus/001-multus.yaml
hack/components/bump-multus.sh

As part of https://bugzilla.redhat.com/show_bug.cgi?id=1953482
We are adding Priority Class to each network component.
The motivation is to make the control plane pods less sensitive to preemption
than user workloads.
Add `system-cluster-critical` to multus DaemonSet.
Since multus isn't bound to a specific node,
yet its an important pod, assign `system-cluster-critical` pc to it.
```release-note
None
```

multus, Add Priority class

---

pkg/components/components.go

Add system-cluster-critical to CNAO operator.
Since CNAO operator isn't bound to a specific node,
yet its an important pod, assign system-cluster-critical
pc to it.
This will make the control plane less sensitive to preemption
than user workloads.
```release-note
None
```

operator, Add Priority class

---

components.yaml

This PR updated multus [repo url](https://github.com/k8snetworkplumbingwg/multus-cni) in components.yaml
```release-note
NONE
```

components, Update multus repo url

---

components.yaml

Since k8s-nmstate has a stable branch,
we can use tagged policy instead of static.
This way, each new release of k8s-nmstate release-0.47
will be auto consumed by CNAO bumper.
```release-note
None
```

release-0.53, Update k8s-nmstate to use tagged policy

---

components.yaml
data/macvtap/002-macvtap-daemonset.yaml
pkg/components/components.go

See https://github.com/kubevirt/macvtap-cni/releases/tag/v0.5.0
```release-note
None
```

macvtap, release-0.53, Bump to version 0.5.0

---

components.yaml

A stable branch was created on bridge-marker for
CNAO release-0.53.
Update manifest to use it.
```release-note
None
```

bridge-marker, release-0.53, Set source as tagged

---

components.yaml

A stable branch was created on ovs-cni for
CNAO release-0.53.
Update manifest to use it.
```release-note
None
```

ovs-cni, release-0.53, Set source as tagged

---

data/multus/001-multus.yaml
hack/components/bump-multus.sh

Remove resources limits for multus, as limits should not
be set for the control plane.
Update resources requests according to empiric use cases.
See https://bugzilla.redhat.com/show_bug.cgi?id=1935218
```release-note
None
```

resources, Update multus resources section

---

data/linux-bridge/002-linux-bridge.yaml

Update linux bridge resources requests according to empiric use cases.
See https://bugzilla.redhat.com/show_bug.cgi?id=1935218
```release-note
None
```

resources, Update linux bridge minimum resources request

---

pkg/components/components.go

Update cnao own resources requests according to empiric use cases.
See https://bugzilla.redhat.com/show_bug.cgi?id=1935218
```release-note
None
```

resources, Update minimum resources request

---

data/linux-bridge/002-linux-bridge.yaml
data/multus/001-multus.yaml
hack/components/bump-multus.sh
pkg/components/components.go

Cherry-pick of 
https://github.com/kubevirt/cluster-network-addons-operator/pull/920
https://github.com/kubevirt/cluster-network-addons-operator/pull/921
https://github.com/kubevirt/cluster-network-addons-operator/pull/922
https://github.com/kubevirt/cluster-network-addons-operator/pull/924
https://github.com/kubevirt/cluster-network-addons-operator/pull/925
https://github.com/kubevirt/cluster-network-addons-operator/pull/926
This PR updates minimum requests of:
- CNAO container
- multus container (also removes limits)
- linux bridge container
```release-note
None
```

[Release-0.53] resources, Update minimum resources request

---

hack/components/yaml-utils.sh

When SELinux is enabled on a build machine, running the components bump
scripts fail due to a missing re-labeling of files when mounting a
volume to a container.
This change enables re-labeling of the files in the shared volume by
adding the `Z` option to the volume mount.
```release-note
NONE
```

hack/components: Support build on SELinux enabled platforms

---

data/linux-bridge/002-linux-bridge.yaml
hack/components/bump-linux-bridge.sh

This PR is based on #595, and fixed a bug where the binaries are not deployed on the node by linux-bridge pod
- **data/linux-bridge, Change copy command to be fail-able**
Currently if one of the copy commands fail then the pod is
considered not failing.
Fix that by making sure the script fails upon copy failure.
- **bump-linux-bridge, refactor env vars**
Removed unused LINUX_BRIDGE_TAR_FILE
Used currently unused LINUX_BRIDGE_TAR_CONTAINER_DIR
- **data/linux-bridge, Fix installation of bridge and tuning CNIs**
There is a bug where the linux-bridge pods never installed the bridge
and tuning CNI, since the source address of the copy was not matching
directories used in the CNI plugins container image.
The only reason why this worked so far is that …

Fix installation of bridge and tuning CNIs

---

data/linux-bridge/002-linux-bridge.yaml

When we upgrade there is already the cnv-{bridge,tuning}
files in the node. In this case, 'cp -f' does not copy
the new binaries over the old symlinks.
To Fix that, changed the flag to '--remove-destination'
```
--remove-destination     remove each existing destination file before
attempting to open it (contrast with --force)
```
```release-note
fix symlink in linux-bridge during upgrade
```

data/linux-bridge, Fix copying over symlink

---

Makefile
cluster/up.sh
cmd/manager/main.go
data/monitoring/prom-rule.yaml
data/monitoring/rbac.yaml
data/monitoring/service.yaml
data/monitoring/service_monitor.yaml
go.mod
hack/components/yaml-utils.sh
hack/prom-rule-ci/prom-rules-tests.yaml
hack/prom-rule-ci/verify-rules.sh
pkg/components/components.go
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/monitoring/metrics.go
pkg/names/names.go
pkg/network/cluster-info.go
pkg/network/network.go
templates/cluster-network-addons/VERSION/namespace.yaml.in
test/check/check.go
test/check/components.go
test/e2e/lifecycle/main_test.go
test/e2e/workflow/deployment_test.go
test/e2e/workflow/main_test.go

This PR add infra support and basic alert `CnaoDown` to CNAO 
manually tested with CRC:
metric:
you can see that CNAO being down for >5 minutes is casuing the alert below
alert:
```release-note
NONE
```

Add alerts infra and basic alert CnaoDown

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

As an intermediate and temporary step, consume the changes posted to the
CNI bridge [1].
Once the PR is merged into the original repo, this change will be
reverted.
In case the PR will not be merged into the original repo, we will
proceed with a more formal resolution.
[1] https://github.com/containernetworking/plugins/pull/639
```release-note
Consume CNI Bridge with mac-spoof-check support.
```

components: Consume CNI Bridge with macspoofchk support

---

data/monitoring/prom-rule.yaml
go.mod
hack/prom-rule-ci/prom-rules-tests.yaml
pkg/controller/statusmanager/status_manager.go
pkg/monitoring/metrics.go
test/check/check.go
test/e2e/workflow/deployment_test.go

This PR adds the Add kubevirt_cnao_cr_ready metric and NetworkAddonsConfigNotReady alert.
```release-note
NONE
```

Add kubevirt_cnao_cr_ready metric and NetworkAddonsConfigNotReady alert

---

data/linux-bridge/002-linux-bridge.yaml
hack/components/bump-linux-bridge.sh
pkg/components/components.go
test/releases/99.0.0.go

The linux-bridge pod is mainly copying bridge and tuning
binaries to the node.
Added tier1 test that makes sure these binareis are copied.
```release-note
NONE
```

linux-bridge, Add shasum check in linux-bridge pod

---

data/linux-bridge/002-linux-bridge.yaml

The default value of maxUnavailable is 1. That serializes upgrades and
may drag for very long time. This change turns it into 10% to speed up
the upgrade process while keeping services reasonably available.
https://bugzilla.redhat.com/show_bug.cgi?id=1990065
```release-note
Set max unavailable replicas of daemonsets to 10%
```

Set max unavailable of bridge CNI to 10%

---

components.yaml

This PR sets CNAO on stable branch `release-0.58` to follow kubemacpool's stable branch `release-v0.31`
```release-note
NONE
```

components, Follow kubemacpool stable branch release-v0.31

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

Replace the source branch of the CNI Bridge with the macspoofchk
support, from the PR branch to a separate branch.
Unlike the PR branch, the new branch is not expected to change. But even
if it does (for fixes), history will be preserved.
```release-note
NONE
```

components: Update CNI Bridge with macspoofchk source

---

data/monitoring/prom-rule.yaml
hack/prom-rule-ci/prom-rules-tests.yaml

`KubeMacPoolDuplicateMacsFound` will alert when duplicate mac
addresses were found by kubemacpool.
```release-note
None
```

prometheus, Add rule for KubeMacPoolDuplicateMacsFound

---

data/monitoring/prom-rule.yaml
hack/prom-rule-ci/prom-rules-tests.yaml
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/monitoring/metrics.go
test/e2e/workflow/deployment_test.go

This PR Adds a new alert KubemacpoolDown
This alert will fire only when KMP is configured and for some reason the kubemacool-manager pod is not running.
The alert priority is set to critical, as if KMP is down, vms cannot be created/updated from the cluster.
```release-note
NONE
```

monitoring, Adding a new alert KubemacpoolDown

---

pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/controller/statusmanager/status_manager.go
pkg/monitoring/metrics.go
test/e2e/workflow/deployment_test.go

This PR does some refactoring on the TrackMonitoredComponents routing and gauge polling
Following this change, readyGauge will be polled as part of the regular reconcile loop.
```release-note
NONE
```

monitoring, Collect readyGauge during reconcile

---

components.yaml
data/nmstate/operand/nmstate.io_nodenetworkconfigurationenactments.yaml
data/nmstate/operand/nmstate.io_nodenetworkconfigurationpolicies.yaml
data/nmstate/operand/nmstate.io_nodenetworkstates.yaml
data/nmstate/operand/operator.yaml
hack/components/bump-nmstate.sh
pkg/components/components.go
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
test/releases/99.0.0.go

https://github.com/nmstate/kubernetes-nmstate/pull/802/commits/a3fe803fa42f1075bd59b762f39898144c576c3c introduces 
infraNodeSelector and infraTolerations knobs.
Sync bump-nmstate.sh script to use correct names for these.
Depends on https://github.com/nmstate/kubernetes-nmstate/pull/802/commits/a3fe803fa42f1075bd59b762f39898144c576c3c
```release-note
NONE
```

manually bump knmstate to v0.53.0

---

components.yaml
data/nmstate/operand/operator.yaml
pkg/components/components.go
pkg/network/nmstate.go
test/releases/99.0.0.go

Bump kubernetes-nmstate to v0.54.0
Also now is mandatory to have the "EnableOVS" data field for the handler manifests, this PR also add a way to control using using the environment variable NMSTATE_ENABLE_OVS.
```release-note
Bump kubernetes-nmstate to v0.54.0 and add NMSTATE_ENABLE_OVS control env var.
```

Bump kubernetes-nmstate to v0.54.0

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

The new build includes a workaround to the SELinux issue detected when
running the cnv-bridge CNI on CentOS Stream.
```release-note
NONE
```

components: Update CNI Bridge

---

pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_operators.go
pkg/controller/statusmanager/status_manager.go

When comparing statuses to see if the status has changed, there is a bug
since oldStatus is a pointer and config.Status is not, hence the
DeepEqual() will always return true
**Note** that this fix will not reduce status issues, since the heartbeat of statuses `Degraded` and `Available` are updated every reconcile.
```release-note
NONE
```

status-manager, Fix bad compare of status

---

components.yaml

set macvtap as static to v0.5.1 in components.yaml
```release-note
NONE
```

components, set macvtap as static to v0.5.1

---

components.yaml

This PR changes ovs-cni update-policy to static
```release-note
NONE
```

[release-0.58] components, change ovs-cni update-policy to static

---

cluster/cluster.sh

When testing against a cluster that is not kubevirtCI it
make sense that the cluster creadentials will be in place pointed
be the $KUBECONFIG env variable.
This commit makes the script use the cerdentials lies in $KUBECONFIG and
if not set exit with status 1.
```release-note
NONE
```

cluster, cluster.sh: add kubeconfig for external

---

cmd/manager/main.go

/kind enhancement
Now CNAO is using Recreate as the upgrade strategy so there is always
only one CNAO pod active, leader election is not needed anymore.
```release-note
Remove leader election
```

manager: Remove leader election

---

pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller_test.go

When CNAO is deployed by HCO, HCO puts managed-by label with HCO value on
networkAddonsConfig. networkAddonsConfig controller then takes this value and inherit it
to the deployed components. This cause a wrong result of a CNAO component labeled
as managed by HCO.
This commit makes that managed-by label will not be taken from networkAddonsConfig,
and test it against an example component - ovs.
Fixes #1051
This PR is initially created by @alonSadan . With his consent I took it and applied some gomega matchers changes
```release-note
NONE
```

controller, labels:don't take managed-by from CR

---

data/monitoring/prom-rule.yaml
hack/prom-rule-ci/prom-rules-tests.yaml

We want to be able to list all kubevirt alerts so we added labels to differentiate them.
Signed-off-by: assafad aadmi@redhat.com
```release-note
Added common labels into alert definitions
```

Add common labels into alert definitions

---

pkg/network/placement_configuration.go

At some environment control-plane is still not present, and nodes are
labeled with master only. This change replace toleratin + node selector
with a affinity rules that implement a fallback to master if
control-plane is not there.
```release-note
Suport "master" control-plane node labels for infra placement.
```

placement, infra: fallback to master node

---

build/operator/Dockerfile

In order to avoid docker.io rate limits,
use the official centos quay.io repository.
```release-note
None
```

dockerfile: Use quay.io instead of docker.io

---

automation/check-patch.e2e-nmstate-functests.sh

Running all the kubernetes-nmstate tests takes a lot of time and does
not bring much value. This change runs the following tests:
- Webhooks
- OVS
- NMPolicy
- default bridge and bond
```release-note
NONE
```

knmstate: Reduce the number of e2e tests

---

build/operator/Dockerfile

Signed-off-by: João Vilaça <jvilaca@redhat.com>
CentOS 7 is scheduled for EOL as stated in https://wiki.centos.org/About/Product, and already exited the Full Updates phase.
Therefore this PR updates CentOS version in Dockerfile for new builds to use CentOS Stream 9, which is in the full support phase (https://www.centos.org/centos-stream/).
```release-note
Update Dockerfile to use CentOS Stream 9
```

Update Dockerfile to use centos:stream9

---

components.yaml

At a release branch if a component has not release branch itself it has
to be marked at static at components.yaml so autobumper will ignore new
tags.
```release-note
NONE
```

0.65: Mark as static components with main

---

.github/workflows/component-bumper-main.yml
.github/workflows/component-bumper-release-0.42.yml
.github/workflows/component-bumper-release-0.44.yml
.github/workflows/component-bumper-release-0.53.yml
.github/workflows/component-bumper-release-0.58.yml

The autobumper create PRs when one of the subcomponents release a new
version but it's using github-tokens this force to put comment
/ok-to-test on those PRs to check CI. This change use a new token that
will directly run CI on those PRs.
```release-note
NONE
```

bumper: Use kubevirt-bot token

---

cluster/up.sh

Some openstack repos does not support centos 8 stream yet. This change
point directly to the centos 8 stream ovs repo.
(cherry picked from commit 152a52e78f453e766e42fb590207ec4eb90cb3fe)
```release-note
NONE
```

[release-0.58] cluster: Enable just ovs repo (#1163)

---

.github/workflows/component-bumper.yaml
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go

The autobumper was referencing the non existent env BASE_BRANCH
(cherry picked from commit aaef587ae4ccbdb7a24bb3bcb91724c469bc38ae)
```release-note
NONE
```

actions: Remove BASE_BRANCH

---

.github/workflows/component-bumper.yaml

At github actions matrix by default it fail fast, if one of the job
fails the rest of job is cancel, this does not make sense for auto
bumper.
At github actions matrix by default it fail fast, if one of the job
fails the rest of job is cancel, this does not make sense for auto
bumper.
```release-note
NONE
```

bumper: Don't cancel jobs if one fail

---

.github/workflows/prepare-version.yaml

With the new workflow_dispatch event from github is possible to put some
UI at gihub to run actions. This changes add a pair of fields to call
`make prepare-{major, minor, patch}` from github.
```release-note
NONE
```

actions: Prepare versioon from github

---

pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/names/names.go
pkg/network/network.go
pkg/util/k8s/labels.go
test/check/check.go
test/e2e/lifecycle/upgrade_test.go

CNAO labels the components it deploys with miscellaneous labels, for example relationship labels.
In case the component is in the same namespace as the CNA operator itself,
it will be labeled as well.
Since K8s logs are labeled with `kubernetes.namespace_name` according
the labels the namespace has, all the cnv logs in the namespace
would appear as their `kubernetes.io/component` equal the value CNAO sets.
Same for the other labels that CNAO adds to the namespace.
Therefore:
Do not add labels to the namespace of the operator itself.
In order to guarantee backward compatibility, CNAO will also remove
those labels from the operator namespace according to their key.
It is safe to do that, because those labels should not be added by anyone,
else the …

labels: Do not label operator namespace with unneeded labels

---

Makefile
RELEASE.md
hack/prepare-release.sh
hack/release-notes.tmpl
hack/release.sh
hack/render-release-notes.sh
hack/versions.sh
version/description

Right now the release notes comes from the commits, but the info needed
is the release-note mark from PRs since users decide if they want that
info to appear that the release notes or not.
```release-note
NONE
```

infra: Use PRs to compose release notes

---

pkg/components/components.go
test/releases/99.0.0.go

Looks like the quay.io tag for multus has being re-generated. This
changes put the SHA to the correct pointer.
```release-note
Fix multus quay.io SHA pin for v3.4.2
```

multus: Fix quay.io SHA

---

tools/bumper/component_commands.go

The last multus tag v3.8 was at commit 33 from HEAD, the autobumper uses
by default 30 commits so it were not found. This change increments it to
100.
```release-note
NONE
```

autobumper: Increase to 100 the commits lookup

---

pkg/components/components.go
test/releases/99.0.0.go

Looks like the quay.io tag for multus has being re-generated. This
changes put the SHA to the correct pointer.
```release-note
Fix multus SHA
```

[0.53] multus: Fix quay.io SHA

---

pkg/components/components.go
test/releases/99.0.0.go

Looks like the quay.io tag for multus has being re-generated. This
changes put the SHA to the correct pointer.
```release-note
Fix multus SHA
```

[0.58] multus: Fix quay.io SHA

---

data/monitoring/prom-rule.yaml
hack/prom-rule-ci/prom-rules-tests.yaml

This PR fixes a typo in `KubemacpoolDown` alert runbook url.
Signed-off-by: assafad <aadmi@redhat.com>
```release-note
None
```

Fix a typo in KubemacpoolDown runboook url

---

test/check/check.go
test/e2e/workflow/deployment_test.go

Since it might take few seconds for the end point to be ready,
we should not assert in the Eventually loop but retry
in case the end point is not ready in the first try.
Mostly seen when the endpoint is behind additional container,
so it takes time until the image of it is pulled.
This change is good as is, because it splits the logic, and use
assert in the right place.
```release-note
None
```

tests, metrics: Fix potential flakes on metrics scraping test

---

Makefile
data/kubemacpool/kubemacpool.yaml
data/monitoring/service.yaml
data/monitoring/service_monitor.yaml
hack/components/bump-kubemacpool.sh
hack/generate-manifests.sh
pkg/components/components.go
pkg/network/kubemacpool.go
test/check/check.go
test/e2e/workflow/deployment_test.go
test/kubectl/kubectl.go
test/releases/99.0.0.go
test/releases/releases.go
test/reporter/writers.go
tools/manifest-templator/manifest-templator.go

CNAO uses controller runtime which creates an http
end point for /metrics.
In order to support https, we deploy rbac-proxy container
in the same pod of CNAO.
The new container exposes https end point,
and connects internally to the http end point.
It is self signed, and protected with rbac rules.
The reporter was updated to report all containers for each pod.
CSV generator was updated to include a new variable
`kube-rbac-proxy-image`, in order to be able to provide the required
kube-rbac-proxy image when using CSV.
Depends on https://github.com/k8snetworkplumbingwg/kubemacpool/pull/353
KMP bump
https://github.com/kubevirt/cluster-network-addons-operator/pull/1236
Fixes …

metrics: Use https instead of http

---

automation/check-patch.e2e-multus-functests.sh
components.yaml
data/multus/001-multus.yaml
hack/components/bump-multus.sh
pkg/components/components.go
test/releases/99.0.0.go

Multus project has change a little:
- They don't have a manifests pert arch since they are using multiarch
registry.
- They have bump golang to 1.17
- The CNI binary is not able to acess apiserver if daemonset is not there https://github.com/k8snetworkplumbingwg/multus-cni/issues/592.
This change moves away golang origin builder since there is non for
1.17
Closes #1230 
```release-note
Bump multus to v3.8
```

multus: Bump to 3.8

---

data/nmstate/operator/nmstate.io_v1_nmstate_cr.yaml
hack/components/bump-nmstate.sh

```release-note
CNAO no longer owns NMState CR created when knmstate-operator is present
```

Annotate NMState CR with rejectOwner annotation

---

automation/check-patch.e2e-nmstate-functests.sh
cluster/up.sh

Now that kubernetes-nmstate is not handled by CNAO the automation to run
the prow job can be removed and the installation of NetworkManager can
be cleaned up from cluster/up.sh.
```release-note
NONE
```

knmstate: Remove automation and cleanup cluster/up

---

data/multus/001-multus.yaml
hack/components/bump-multus.sh

/kind bug
When multus is deleted the CNI resolution has to be forced for already
present pods or they will not be able to be removed. This change remove
the CNI cache before deleting the multus daemonset. This is related to
[1]
[1] https://github.com/kubevirt/cluster-network-addons-operator/pull/1219/commits/07036046c82b1f902a60ae4c058be61612e51f0d
```release-note
Delete CNI cache /var/lib/cni/* at multus delete, the cache should be reconstructed by the CRI if it's using libcni.
```

multus: Delete cni cache at preStop

---

data/nmstate/operator/nmstate.io_v1beta1_nmstate_cr.yaml
hack/components/bump-nmstate.sh

cherry-pick of https://github.com/kubevirt/cluster-network-addons-operator/pull/1247
```release-note
CNAO no longer owns NMState CR created when knmstate-operator is present
```

[release-0.58] Annotate NMState CR with rejectOwner annotation

---

cluster/cluster.sh

This PR bumps CNAO KUBEVIRTCI_TAG to [2203021427-243853c](https://github.com/kubevirt/kubevirtci/releases/tag/2203021427-243853c)
```release-note
NONE
```

kubevirtci_tag, Bump to 2203021427-243853c

---

data/nmstate/operator/nmstate.io_v1_nmstate_cr.yaml
hack/components/bump-nmstate.sh
pkg/network/nmstate.go

When users migrate from CNAO to standalone kubernetes-nmstate operator,
their placementConfiguration specified in cluster network addons is lost.
This PR propagates this configuration to the NMState CR.
This depends on kubernetes-nmstate having affinity fields in NMState CRD
https://github.com/nmstate/kubernetes-nmstate/pull/1003
```release-note
propagate placementConfiguration to nmstate CR
```

[release-0.65] nmstate: propagate placementConfiguration to NMState CR

---

pkg/apply/apply.go

Currently the "Handling deletion of X" is printed even if the object is
not owned, This may lead to misleading log data when running on HCO.
Moving the log to after object is filtered for ownership
```release-note
NONE
```

DeleteOwnedObject, Change Delete handling log location

---

components.yaml

components, fix linux bridge primary branch to main
```release-note
NONE
```

[release-0.42] components, fix linux bridge primary branch to main

---

components.yaml

linux-bridge primary branch has changed to main.
Updating components.yaml accordingly
```release-note
NONE
```

[release-0.44] components, fix linux bridge primary branch to main

---

components.yaml

linux-bridge primary branch has changed to main.
Updating components.yaml accordingly
```release-note
NONE
```

[release-0.53] components, fix linux bridge primary branch to main

---

data/kubemacpool/kubemacpool.yaml
hack/components/bump-kubemacpool.sh
pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
pkg/apis/networkaddonsoperator/shared/zz_generated.deepcopy.go
pkg/components/components.go
pkg/network/kubemacpool.go
pkg/network/tlsSecurityProfile.go
pkg/network/tlsSecurityProfile_test.go

This PR adds API for configuration of TLSSecurityProfile to NAC custom resource.
TLS configuration is passed via ENV variables to kubemacpool certificate manager pods.
```release-note
Add API for TLSSecurityProfile
```

Add TLS Security Profile API to NAC

---

test/e2e/monitoring/alerts_test.go
test/e2e/monitoring/rules_test.go

This PR adds a new module for prometheus rules tests and adds new tests cases for alert definitions. We expect to see "runbook_url" annotations in alerts and those urls must be accessible.
Signed-off-by: assafad aadmi@redhat.com
```release-note
None
```

Add test cases for runbook URLs 

---

.github/workflows/component-bumper.yaml

As we support only last 2 stable branches, this PR is removing old workflows
```release-note
NONE
```

gitActions, Remove unsupported workflows

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

This release bump holds [fixes](https://github.com/k8snetworkplumbingwg/ovs-cni/releases/tag/v0.26.1) to CNAO ovs-cni teir1 ci
```release-note
NONE
```

[release-0.65] components, Bump ovs-cni to v0.26.1

---

pkg/components/components.go
pkg/components/tlsProfiles.go
pkg/components/tlsProfiles_test.go

Sort tlsProfiles alphabetically, so that generated CRD is always the same
```release-note
NONE
```

crds: sort tlsProfiles to generate deterministic crd

---

test/e2e/monitoring/endpoints_test.go
test/e2e/workflow/deployment_test.go

This PR syntactically moves the test as is to the monitoring lane
```release-note
NONE
```

monitoring, e2e, Move endpoints test to monitoring lane

---

pkg/network/tlsSecurityProfile.go
pkg/network/tlsSecurityProfile_test.go

/kind bug
When no TLS is specified at openshift the Intermediate profile is
selected [1]. This changes copy that behaviour at CNAO.
[1] https://github.com/openshift/library-go/blob/master/pkg/operator/configobserver/apiserver/observe_tlssecurityprofile.go#L81-L84
Closes https://bugzilla.redhat.com/show_bug.cgi?id=2069388
```release-note
Use intermediate TLS profile by default
```

tls: Use intermediate TLS profile by default

---

cluster/operator-install.sh

In order to investigate https://github.com/kubevirt/cluster-network-addons-operator/issues/1320, Adding more info to `cluster-sync`
```release-note
NONE
```

operator-install, Add info in case of a timeout

---

pkg/controller/statusmanager/status_manager.go
test/e2e/workflow/recovery_test.go

This PR aims to block upgrade if still using CNAO to deploy nmstate by Setting NetworkAddonsConfig Degraded Status to true.
HCO will reconcile it and see that the NAC status is degraded, consequently it will set it's status upgradeable to false.
See HCO: https://github.com/kubevirt/hyperconverged-cluster-operator/blob/main/controllers/hyperconverged/hyperconverged_controller.go#L740
That will block upgrade until user installs KNO (Kubernetes Nmstate Operator).
HCO change:
- https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1847
```release-note
Block CNV upgrade if still using CNAO to deploy nmstate
```

Set degraded if nmstate is requested in networkAddonsConfig

---

pkg/network/nmstate.go

As part of adding Self Sign certificate configuration to NMState API, we've moved setting the defaults
to the operator code, instead of the yaml, since other default values are specified in the operator as well.
- https://github.com/nmstate/kubernetes-nmstate/pull/1029
This PR adds the change to CNAO.
```release-note
NONE
```

[release-0.65] nmstate: define Self Sign onfiguration defaults in operator code

---

pkg/controller/statusmanager/status_manager.go
test/e2e/workflow/recovery_test.go

HCO will reconcile and see that the NAC status is degraded
and in turn set it's status upgradeable to false.
That will block upgrade until user installs KNO
```release-note
Block CNV upgrade if on OCP 4.11 and still using CNAO to deploy nmstate
```

[release-0.65] Set degraded if nmstate is requested in networkAddonsConfig on OCP 4.11 or later

---

data/nmstate/operator/nmstate.io_v1_nmstate_cr.yaml
hack/components/bump-nmstate.sh

When creating NMState CR for kubernetes-nmstate operator, propagate selfSignConfiguration.
```release-note
selfSignConfiguration is passed to NMState CR when deploying nmstate via standalone kubernetes-nmstate operator
```

[release-0.65] Propagate selfsign conf

---

pkg/controller/statusmanager/status_manager.go

Value of Upgradeable/Available condition propagates to HCO operator.
Since we want to only express we want to block an upgrade when nmstate
is enabled in CNAO, it's more accurate to only set Upgradeable condition
instead of setting Availabe condition to False.
With this change, HCO will set Upgradeable condition to False, but will
remain Available, which describes the situation better.
See the following snippets of networkaddonsconfig spec and status:
```yaml
spec:
imagePullPolicy: IfNotPresent
kubeMacPool: {}
linuxBridge: {}
macvtap: {}
multus: {}
nmstate: {}
ovs: {}
status:
conditions:
- lastTransitionTime: "2022-04-20T07:01:30Z"
status: "False"
type: Degraded
- lastTransitionTime: "2022-04-20T07:01:50Z"
status: "False"
type: Progressing
- lastTransitionTime: "2022-04-20T07:01:50Z" …
```

Set Upgradeable instead of Available condition when nmstate deployed

---

components.yaml

This PR changes components to not follow relevant stable branches, and where there
is no stable branch, set to static.
```release-note
NONE
```

[release-0.76] components.yaml, statify components on release-0.76

---

.github/workflows/prepare-release-branch.yaml

Add checkout to main branch on 'Run make update-release-branch-workflows' job
Remove unneeded pushBranch input option.
```release-note
NONE
```

workflows, Fix jobs in prepare-release-branch workflow

---

.github/workflows/prepare-release-branch.yaml

peter-evans/create-pull-request build parameter needs to be different
from the existing branch.
```release-note
NONE
```

workflows, Fix branch names on peter-evans/create-pull-request

---

pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/controller/statusmanager/status_manager.go

When CNAO hands over knmstate deployment to KNO,
NMstate remains in networkAddonsConfig spec.
For that, we need to check whether KNO is present
to make sure the Not Upgradeable condition is removed,
when KNO is installed.
```release-note
NONE
```

Set Not upgradeable only when KNO is not found

---

pkg/controller/statusmanager/status_manager.go
test/e2e/workflow/recovery_test.go

This check is not needed anymore, as nmstate is not valid field in
NetworkAddonsConfig spec.
This reverts commit 575bdd5ede5e79ac73fd4d43ed0aac015b80df66.
```release-note
NONE
```

Revert "Set degraded if nmstate is deployed on OCP 4.11 or later

---

test/check/conditions.go
test/e2e/workflow/deployment_test.go

This PR adds E2E test for 
1) when nmstate is deployed with CNAO, Upgradeable condition is set to False
2) when nmstate is deployed with CNAO and then KNO is installed, Upgradeable condition is removed
after nmstate is handed over from CNAO to KNO
```release-note
NONE
```

e2e: nac upgradeable condition for nmstate deployment

---

data/nmstate/operand/cluster_role.yaml
hack/components/bump-nmstate.sh
pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
pkg/network/cluster-info.go
pkg/network/nmstate.go
test/e2e/workflow/deployment_test.go

When using Openshift, in case cluster-reader
ClusterRole exists,
Users of cluster-readers group should be able to
access k8s nmstate crds, such as nns, nncp and nnce.
Add a ClusterRole that allows it in case
cluster-reader exists.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2087091
Only if k8s-nmstate is deployed by CNAO, the logic is added.
For standalone operator the support of cluster-reader is
done at https://github.com/nmstate/kubernetes-nmstate/pull/1052 onwards.
```release-note
None
```

[release-0.65] rbac: Add missing cluster-reader verbs

---

data/linux-bridge/001-rbac.yaml
data/linux-bridge/003-bridge-marker.yaml
data/multus/001-multus.yaml
hack/components/bump-bridge-marker.sh
hack/components/bump-multus.sh

According to [openshift's API specification](https://docs.openshift.com/container-platform/4.10/rest_api/security_apis/securitycontextconstraints-security-openshift-io-v1.html) the following
attributes are required:
- allowHostDirVolumePlugin
- allowHostIPC
- allowHostNetwork
- allowHostPID
- allowHostPorts
- allowPrivilegedContainer
- readOnlyRootFilesystem
This commits adds the required parameters to the SCCs that were missing
them.
Furthermore, there's this [openshift documentation bug](https://bugzilla.redhat.com/show_bug.cgi?id=2079224), in which the `volumes`
attribute is missing from the API.
```release-note
Add the required attributes to comply with the openshift SCC API.
```

config, sccs: add required parameters

---

components.yaml

A stable branch was created on bridge-marker. Let's use it to receive fixes.
```release-note
NONE
```

[release-0.65] Pin CNAO to bridge-markers stable branch

---

cluster/cluster.sh
cluster/up.sh

This PR fixes the issue where cluster up is broken on this stable branch
We do this by bumping to a more up to date kubevirtci tag, one that does not need a separate networkmanager installation.
```release-note
NONE
```

[release-0.58] Remove nmcli 1.34 from cluster-up

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

Tag 0.9.2 was spoiled due to change in Go version dependency. This patch
pins marker back to 0.9.1 and sets the source branch to be stable
release-0.9.1.
```release-note
NONE
```

[release-0.58] Pin bridge-marker to stable branch of 0.9.1

---

automation/check-patch.e2e-ovs-cni-functests.sh

Default is 10m which isn't enough.
Use 20m as OVS repo e2e tests are using.
This fixes the problem we saw after bumping ovs, but it isn't due to the bump
this problem exists even on clean main.
```release-note
None
```

e2e ovs: Increase timeout

---

automation/check-patch.e2e-ovs-cni-functests.sh
cluster/operator-push.sh
cluster/up.sh

For some reason pushing to localhost registry doesn't work.
It does work using 127.0.0.1
A possible reason is
https://bugzilla.redhat.com/show_bug.cgi?id=2038634
(investigated as part of https://github.com/kubevirt/kubevirt/pull/6958)
It started since https://github.com/kubevirt/project-infra/pull/1616
More details on
https://github.com/kubevirt/containerized-data-importer/pull/2113
Additional changes:
Remove deprecated kubevirtci providers support
Fix comment.
```release-note
None
```

deploy scripts: Use 127.0.0.1 instead localhost

---

hack/bump-kubevirtci.sh

It was outdated.
Fixed in a way that automation can use it:
In case fatal happens return error code.
In case all is good, determine if there was a change
according non empty stdout.
```release-note
None
```

kubevirtci: Fix bump script

---

pkg/components/components.go

When deployed at some clusters based on k8s 1.25 the operator get the following error 
```
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (containers "cluster-network-addons-operator", "kube-rbac-proxy" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (containers "cluster-network-addons-operator", "kube-rbac-proxy" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or containers "cluster-network-addons-operator", "kube-rbac-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```
To fix that the pod and container security context for the operator is fixed following instructions at …

operator: Adapt to k8s-1.25 security restrictions

---

pkg/components/components.go

Signed-off-by: Enrique Llorente <ellorent@redhat.com>
Cherry pick from https://github.com/kubevirt/cluster-network-addons-operator/pull/1401
```release-note
Fix operator pod and container security context for k8s-1.25
```

release-0.65, operator: Adapt to k8s-1.25 security restrictions

---

components.yaml
data/ovs/001-ovs-cni.yaml
hack/components/bump-ovs-cni.sh
pkg/components/components.go
pkg/network/ovs.go
test/releases/99.0.0.go
tools/manifest-templator/manifest-templator.go

Since https://github.com/k8snetworkplumbingwg/ovs-cni/pull/244 OVS CNI is shipping all its binaries in a single container image and deploying all CNI plugins via a single init container.
This PR adapts to that change.
```release-note
NONE
```

Bump OVS CNI to 0.29.1 and adapt to OVS CNI based on a single image

---

hack/render-release-notes.sh

Latest releas-notes tool is using golang 1.19 and is using new golang features so the tool does not compile with go1.17 from CNAO project. This change pin it to latest go1.17 version v0.13.0.
```release-note
NONE
```

release-notes: Ping the tool to v0.13.0

---

components.yaml

We don't want to merge a new major release of a component by mistake. The policy can be set back to tagged only once stable branches are created on these components.
```release-note
NONE
```

Stop automatic bumps of components

---

automation/check-patch.e2e-multus-functests.sh
components.yaml
data/multus/001-multus.yaml
hack/components/bump-multus.sh
pkg/components/components.go
test/releases/99.0.0.go

The multus bump script was updated to:
- use a different multus manifest - `multus-daemonset-thick.yml`
- ignore comments in the manifest file. Comments in the manifests broke the `yaml-utils::split_yaml_by_seperator` function.
```release-note
Consume multus v4, which operates as a thick plugin.
```

multus: bump to multus-v4 (thick plugin)

---

pkg/network/multus_dynamic_networks_controller.go
pkg/network/multus_dynamic_networks_controller_test.go
pkg/network/network.go

The `multusDynamicNetworks` feature **depends** on multus; as such, ensure the multus dependency is present whenever the `multusDynamicNetworks` is requested.
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
The `multusDynamicNetworks` feature **depends** on multus; as such,
ensure the multus dependency is present whenever the `multusDynamicNetworks`
is requested.
```release-note
Ensure the CNAO configuration also features `multus` whenever the `multusDynamicNetworks` feature is requested.
```

multus dynamic networks: validate configuration

---

pkg/components/components.go

In order to notify pod-security.kubernetes.io that we intent to create (potentially privileged) SCCs, so it labels us as "privileged", we have to explicitly request "use" verb for scc.
With this change, CNAO's namespace is marked as `pod-security.kubernetes.io/enforce: priviledged` even before we deploy any of our privileged components. This assures that CNAO does not show up in audit logs.
```release-note
Resolve audit warnings.
```

Explicitly request "use" verb on SCC

---

data/multus/001-multus.yaml
hack/components/bump-multus.sh

This provides a work-around for an [opened multus issue](https://github.com/k8snetworkplumbingwg/multus-cni/issues/971) reporting its integration w/ istio was broken on multus-v4.
By setting the multus CNI conf dir to whatever istio expects, the integration works.
Multus does not care about this parameter since we are using [automatically generated multus configurations](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/how-to-use.md), which output this auto-generated configuration [elsewhere](https://github.com/kubevirt/cluster-network-addons-operator/blob/146462ca6ada7935aec4d4a318558567543969a8/data/multus/001-multus.yaml#L148).
```release-note
Make multus comply w/ istio's …
```

multus-v4: set generated config to whatever istio expects

---

test/check/components.go
test/e2e/workflow/deployment_test.go

This PR adds the multus dynamic networks controller to CNAO's workflow deployment e2e tests.
Fixes: #1463 
Depends-on: #1462 
```release-note
NONE
```

Integrate dynamic networks controller deployment tests

---

Makefile

This way it will be checked as part of the unit test lane that runs the bump-all target.
We need to support auto detection imo.
```release-note
None
```

makefile: Add missing component to bump-all target

---

pkg/network/nmstate.go
test/e2e/workflow/deployment_test.go

When k-nmstate was deployed with CNAO and then the k-nmstate operator is installed the CNAO k-nmstate was being replaced by removing the one at the CNAO namespace but the PDB was missing on the removal, that show some alearts since the nmstate-webhook is gone. This change remove the PDB as part of the upgrade to operator process.
Closes https://bugzilla.redhat.com/show_bug.cgi?id=2139697
```release-note
nmstate: Remove PDB at operator install
```

nmstate: Remove PDB at operator install

---

Makefile

Auto detect all bump*.* files and run them
as part of bump-all.
This way we need less to maintain once we add a component.
```release-note
None
```

makefile: Generalize bump-all

---

README.md
components.yaml
hack/components/bump-multus-dynamic-networks.sh
pkg/components/components.go
test/releases/99.0.0.go

This PR pull the multus dynamic networks controller from the `k8snetworkplumbingwg` org repo URL.
As a side effect, bump to v0.2.0, which is the first tagged release under that org's name.
```release-note
Bump multus dynamic networks controller to v0.2.0
```

multus-dynamic-networks: point to the k8snetworkplumbingwg org URL

---

automation/check-patch.e2e-kube-secondary-dns-functests.sh
components.yaml
hack/components/bump-kube-secondary-dns.sh
pkg/components/components.go
test/releases/99.0.0.go

Bump KubeSecondaryDNS manually (v0.0.7), since auto-bumper has problems.
See https://github.com/kubevirt/cluster-network-addons-operator/pull/1474
Beside that:
* Install kubevirt before running KSD e2e tests.
* Fix bump script (use set instead of update, because strings might be empty).
```release-note
None
```

ksd: Bump manually to v0.0.7

---

automation/components-functests.setup.sh

`KUBEVIRT_PROVIDER` is already exported at the sourced `cluster.sh`, 
no need to override it.
It just confuse and harder to maintain because it will ignore the `cluster.sh` value
which is the main one we use.
```release-note
None
```

components: Remove double export

---

pkg/network/network.go

The current config was used instead of the previous.
In the current config it is empty, we need to pass the previous config, 
so in case the component was configured in the previous config it will render its 
object and add it to the delete list.
```release-note
NONE
```

Fix undeploy components

---

components.yaml
data/kube-secondary-dns/secondarydns.yaml
pkg/components/components.go
test/releases/99.0.0.go

Bump KubeSecondaryDNS to [v0.0.8](https://github.com/kubevirt/kubesecondarydns/releases/tag/v0.0.8)
```release-note
NONE
```

ksd: Bump to v0.0.8

---

data/monitoring/prom-rule.yaml
hack/prom-rule-ci/prom-rules-tests.yaml
test/e2e/monitoring/rules_test.go

Signed-off-by: assafad <aadmi@redhat.com>
This PR adds to each of CNAO alerts a label named `operator_health_impact`, which indicates how the alerts impact the operator health. This will enable us filtering alerts based on their impact on the operator health, and to later have an operator health metric, which will tell the user what is the aggregated operator health.
This label gets one of the following values:
- `critical` indicates that the alert fires due to an issue that impacts the operator's functionality badly, and an action must be taken immediately in order to solve it.
-  `warning` indicates that the alert fires due to an issue that soon might impact the operator's functionality badly, and the user should be warned in order to solve the …

Add `operator_health_impact` label to CNAO alerts

---

data/kube-secondary-dns/secondarydns.yaml
hack/components/bump-kube-secondary-dns.sh
pkg/network/kube_secondary_dns_controller.go

In order to make ksd pod to work with restricted psa policy it should have `runAsNonRoot: true`.
However, once the pod's securityContext has `runAsNonRoot: true` it should also have a specific `rusAsUser`.
Having a specific user is problematic on Openshift since it may configure a range of valid ids (example of a possible error - `spec.containers[0].securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000670000, 1000679999]`).
According to "What happens if I use runAsUser in my workloads?" section in https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/1417 the suggested solution is - 
```
If you are unable to change the image, for Openshift distributions you MUST leave the RunAsUser and RunAsNonRoot …
```

[ksd] Parameterize "runAsNonRoot" in the yaml

---

components.yaml
data/kube-secondary-dns/secondarydns.yaml
pkg/components/components.go
test/releases/99.0.0.go

See https://github.com/kubevirt/kubesecondarydns/releases/tag/v0.0.9
```release-note
None
```

KSD: Bump to v0.0.9

---

go.mod
go.sum
vendor/modules.txt

Address https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-4238.
Manual backport of https://github.com/kubevirt/cluster-network-addons-operator/pull/1504.
```release-note
NONE
```

[release-0.79] Pin goutils to v1.1.1

---

go.mod
go.sum
vendor/github.com/Masterminds/goutils/cryptorandomstringutils.go
vendor/github.com/Masterminds/goutils/randomstringutils.go
vendor/github.com/Masterminds/goutils/stringutils.go
vendor/modules.txt

Address https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-4238.
Manual backport of https://github.com/kubevirt/cluster-network-addons-operator/pull/1504.
```release-note
NONE
```

[release-0.65] Pin goutils to v1.1.1

---

pkg/network/nmstate.go

Fixes https://bugzilla.redhat.com/2152529.
This patch also unifies naming of nmstate cleanup functions.
```release-note
NONE
```

Clean up nmstate service if standalone nmstate is installed

---

pkg/network/nmstate.go
test/e2e/workflow/deployment_test.go

The original code was using a wrong API group. With this patch, the group is fixed and a test is added.
```release-note
NONE
```

Fix nmstate service cleanup

---

pkg/network/placement_configuration.go

Currently the default toleration for pods is to evict a node after 5 minutes that the node is not-ready/unschedulable.
In pods running on master nodes, this eviction needs to be faster in order to not delay a node's reboot.
This PR is adding infra tolerations that allows a pod to evict after 1 minute in case the node it is scheduled on is not-ready/unschedulable. 
As currently the only component using infra placement is Kubemacpool, this is the only component that will be affected.
```release-note
NONE
```

placement-configuration: Add infra tolerations

---

components.yaml

This PR sets all components to not follow non-stable branches.
```release-note
NONE
```

[release-0.85] components: Freeze bumps for stable branch

---

components.yaml
data/macvtap/002-macvtap-daemonset.yaml
pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
pkg/components/components.go
pkg/network/macvtap.go
pkg/network/macvtap_test.go
pkg/network/network.go
test/e2e/workflow/deployment_test.go

This PR allows users to define the macvtap-cni device-plugin configuration instead of using link auto-discovery (i.e. all links available in the host would be allowed as macvtap lower devices).
For that, we need macvtap-cni [v.0.11.0](https://github.com/kubevirt/macvtap-cni/releases/tag/v0.11.0), which templates the name of the config map holding the device plugin configuration.
Fixes: #1512 
```release-note
Allows overriding the macvtap-cni device plugin configuration.
```

macvtap: allows overriding the macvtap device plugin configuration

---

hack/components/bump-kube-secondary-dns.sh

Add the missing CoreDNS to KSD bump script.
In case we change the image on KSD, it will be reflected on CNAO as well.
Use the original manifest because the updated one is parameterized already,
and isn't split to yamls (so can't use yaml-utils).
Note that sed won't fail in case `CORE_DNS_IMAGE` isn't found,
we can improve it on the future, it isn't since it doesn't change a lot.
It is the same case for the rest of the images.
```release-note
None
```

ksd: Update bump to include CoreDNS as well

---

data/kubemacpool/kubemacpool.yaml
hack/components/bump-kubemacpool.sh
test/check/check.go
test/e2e/workflow/deployment_test.go

The cert-manager deployment from kubemacpool was missing the placement ocnfiguration. This change add that to the manifets.
/kind bug
/closes https://bugzilla.redhat.com/show_bug.cgi?id=2181997
```release-note
Add placement configuration to kubemacpool cert-manager
```

kmp: Add placement to cert-manager

---

hack/components/bump-linux-bridge.sh

Whenever we bump the CNI source code, we need to build the
`cni-default-plugins` image locally and push it to the quay repo.
Not everyone has permissions to push to that repo; thus, we point the
user towards someone with enough permissions to push to it.
```release-note
Label a maintainer in the `cni-default-plugins` container image.
```

Add cni plugins img maintainer info

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

This introduces bug fixes resolving issues with VLAN 1 leakage and performance issues of MAC spoof filtering [2].
[1] https://github.com/containernetworking/plugins/issues/667
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2173485
Generated by referencing the latest plugins commit  from `components.yaml`, running `PUSH_IMAGES=yes make bump-linux-bridge` and replacing tags with digests.
```release-note
Fix PVID bug and performance issues of the bridge CNI 
```

Bump linux bridge CNI

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

**This is a manual cherry pick.**
This introduces bug fixes resolving issues with VLAN 1 leakage and performance issues of MAC spoof filtering [2].
[1] https://github.com/containernetworking/plugins/issues/667
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2173485
Signed-off-by: Petr Horacek <hrck@protonmail.com>
(cherry picked from commit 755a53eb1bcb5d3e47d8213278da3d1188c9ea5b)
```release-note
NONE
```

Bump linux bridge CNI (#1535)

---

components.yaml
data/multus/001-multus.yaml
hack/components/bump-multus.sh
pkg/components/components.go
test/releases/99.0.0.go

Also, from now on, track the tagged multus releases, instead of using a pinned version.
This PR consumes a tagged version of multus, instead of a pinned version.
It also updates the multus component update policy to track any multus releases.
```release-note
Consume multus-cni v4.0.1, thick plugin mode
```

 multus: bump imgs to v4.0.1

---

cluster/operator-push.sh

Return can't be used unless in a function or sourced script. Use exit instead.
```release-note
None
```

operator-push: Fix script in case of external provider

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

This introduces a bug fix resolving an issue where deleting pods took too long when there were many rules / chains in the kubernetes node [0].
[0] - https://bugzilla.redhat.com/show_bug.cgi?id=2175041
Unfortunately, this time, there were (at least one) feature merged in container-networking CNI project: https://github.com/containernetworking/plugins/pull/829
```release-note
Address performance issues of bridge-cni when deleting pods
```

[release-0.85] Bump linux bridge CNI

---

automation/check-patch.e2e-kubemacpool-functests.sh
components.yaml
data/kubemacpool/kubemacpool.yaml
hack/components/bump-kubemacpool.sh
pkg/components/components.go
test/releases/99.0.0.go

Latest kubemacpool has some changes that breaks autobumper, this change adapt autobumper and do a manual bump.
```release-note
Bump kubemacpool to v0.41.0
```

kubemacpool: Bump to v0.41.0

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

See https://github.com/kubevirt/kubesecondarydns/pull/59
```release-note
None
```

KSD: Bump to v0.0.11

---

pkg/components/components.go

Saw during running lifecycle tests on a release PR locally in the audit logs.
Addon to https://github.com/kubevirt/cluster-network-addons-operator/pull/1550
```release-note
None
```

rbac: Add missing verb

---

automation/check-patch.e2e-lifecycle-k8s.sh
hack/components/bump-kube-secondary-dns.sh
test/releases/0.83.0.go
test/releases/0.83.1.go
test/releases/0.84.0.go
test/releases/0.85.0.go
test/releases/99.0.0.go

Since the CoreDNS image might change, it can't use
the variable which exists only on the latest candid 99.0.0,
but should have an hardcoded value per each release.
Fix the KSD bump script to update the 99.0.0 file when bumping.
Beside that, add v0.85.x so we can test this fix without
a release PR, which checks update to all the versions beside the
pending release.
Took v0.85.0 even that we already have v0.85.2 because just this one has a file under `test/releases`.
It allows the non release PR to test the CoreDNS image as well.
Note: not related to this PR but once `KubeRbacProxyImageDefault` changes, 
we will need to do the same for that as well.
```release-note
None
```

tests: Fix expected CoreDNS image

---

data/kubemacpool/kubemacpool.yaml
hack/components/bump-kubemacpool.sh
pkg/network/kubemacpool.go
pkg/network/network.go

In order to make kubemacpool pods work with restricted psa policy it should have runAsNonRoot: true.
However, once the pod's securityContext has runAsNonRoot: true it should also have a specific rusAsUser.
Having a specific user is problematic on Openshift since it may configure a range of valid ids (example of a possible error - spec.containers[0].securityContext.runAsUser: Invalid value: 127: must be in the ranges: [1000670000, 1000679999]).
(issue [here](https://issues.redhat.com/browse/CNV-29823))
According to "What happens if I use runAsUser in my workloads?" section in https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/1417 the suggested solution is -
```
If you are unable to change the image, for Openshift …
```

Kubemacpool: Parameterize "runAsNonRoot" in the yaml

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

This bump brings in https://github.com/containernetworking/plugins/pull/875
This change is required to improve the VLAN isolation done by bridge CNI. This bump is unorthodox since it does not only cherry-pick the bug fix, but also a few other patches. This is due to the lack of a stable branch in CNI plugins. We reviewed the parasiting patches that are introduced by this bump and evaluated that they are not disruptive to our typical use of the bridge CNI.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2209318
```release-note
Bump bridge CNI.
```

[release-0.79] Bump Bridge CNI to fix VLAN leakage

---

data/monitoring/prom-rule.yaml
hack/prom-rule-ci/prom-rules-tests.yaml

Currently, [KubemacpoolDown alert](https://github.com/kubevirt/cluster-network-addons-operator/blob/main/data/monitoring/prom-rule.yaml#L57) has a runbook with the name `KubeMacPoolDown`. This PR, https://github.com/kubevirt/monitoring/pull/187 and https://github.com/openshift/runbooks/pull/128 are fixing it.
```release-note
None
```

fix KubemacpoolDown runbook

---

data/linux-bridge/002-linux-bridge.yaml

Some Kubernetes vendors deploy their own bridge and tuning CNI binaries.
In such cases, CNAO can just rely on these binaries instead of deploying
(and maintaining its own).
In case an existing binary is found, create a soft link between
bridge and cnv-bridge. Otherwise build and deploy cnv-bridge.
Soft link it to bridge.
With this change, we maintain backwards compatibility, while avoiding the
need to support bridge and tuning CNIs where we don't have to.
```release-note
None
```

linux bridge: Consolidate CNIs

---

pkg/components/components.go
tools/manifest-templator/manifest-templator.go

The Multus component requires an a powerful cluster-wide role to
operate:
```
- apiGroups:
- k8s.cni.cncf.io
resources:
- '*'
verbs:
- '*'
```
At the same time, Multus is an optional component.
As part of an effort to limit CNAO to the least amount of privileges it
must posses, this patch introduces a new flag to the CNAO manifest
generator, allowing to omit the Multus RBAC from the CNAO RBAC. Default
value of the flag is true, in this case Multus RBAC will be included.
* If this new flag is set to false and Multus is never deployed, it
limits the possible attack surface.
* If this flag is set to false and a user attempts to deploy Multus,
CNAO will turn into a degraded state, unable to deploy Multus because
of missing RBAC permissions.
Typically, …

Allow restriction of Multus RBAC

---

data/linux-bridge/002-linux-bridge.yaml

The soft link should point to the real path on the host, 
not to the mount path of the container.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2228240
```release-note
None
```

linux bridge: Fix softlink path

---

pkg/network/macvtap.go
pkg/network/network.go

We don't support Macvtap on Openshift.
It is better to fail with explicit error in case it is part of the CR.
```release-note
Block deploying Macvtap on Openshift because it is not supported.
```

macvtap: Block deployment on Openshift

---

.github/workflows/check_hashicorp_modules.yaml

Due to [1] we need to make sure not to use BSL modules.
Luckily the current we use have not changed.
The ones that are not changed are SDK/API and general Go libraries.
"HashiCorp APIs, SDKs, and almost all other libraries will remain MPL 2.0." [1] [2]
This commit creates a github action which whitelists them.
Any other module of hashicorp will be rejected, 
and will need to be manually examined if it uses MPL (or other non restrictive license) or BSL.
[1] https://www.hashicorp.com/blog/hashicorp-adopts-business-source-license
[2] https://github.com/cncf/foundation/issues/617#issuecomment-1675803976
```release-note
None
```

go modules: Allowlist specific hashicorp modules

---

test/e2e/monitoring/rules_test.go

This PR improves the alerts rules test readability and maintainability. In addition, it adds a check to the alerts rules test, which verifies that the alerts `runbook_url` annotations have a suffix with the alerts names.
**Which issue(s) this PR fixes**: https://issues.redhat.com/browse/CNV-30798
```release-note
None
```

Improve alert rules sanity test

---

pkg/network/placement_configuration.go
pkg/network/placement_configuration_test.go

In order to allow running on ARM, remove "kubernetes.io/arch": "amd64" node selectors
from default placement.
Replace them with simple "kubernetes.io/os": "linux", which is part of the default selector if none.
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2238723
* Bridge market repo itself also have this selector, but it doesn't affect CNAO, because CNAO
replace it when bumping bridge market.
```release-note
None
```

arm: Remove amd64 node selector

---

.github/workflows/check_hashicorp_modules.yaml
go.mod

According [1] we need to look on go.mod only because we have "go 1.17" in go.mod.
Adapt git actions accordingly.
All the 3 modules whitelisted on this PR are approved by GB exception, example [2]
More reading about it [3]
(we might want to update the quick tip about it)
[1] https://github.com/cncf/foundation/issues/617#issuecomment-1681189207
[2] https://github.com/cncf/foundation/blob/e8bd39f52b9b577a0ba2fcb2bfa8e68b35ebc1e8/license-exceptions/cncf-exceptions-2022-04-12.json#L80
[3] https://github.com/cncf/foundation/issues/617#issuecomment-1695913854
```release-note
None
```

modules: Amend hashicorp filtering

---

OWNERS

I would like to nominate Or Shoval for the role of CNAO maintainer. Or has been consistently contributing to the project since 2020 and he has been a de facto maintainer for some time now.
Some of his recent contributions were licensing compliance, RBAC audit, or placement API.
Or is also caring for the integration of our adjacent project into CNAO. He understands how CNAO fits into HCO and how it is registered in project-infra. He is an active contributor of kubevirtci which we use to power CNAO's CI.
In the past few months, we have been working closely together, covering all the maintainer duties and I'm fully confident in him taking the responsibility over CNAO.
CC @RamLavi @qinqon @oshoval  …

Nominate Or Shoval for the maintainer role

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

Manual cherry-pick of 
https://github.com/kubevirt/cluster-network-addons-operator/pull/1608
in order to include https://github.com/kubevirt/kubesecondarydns/pull/61
```release-note
None
```

release-0.89: bump kube-secondary-dns to v0.0.12

---

go.mod
pkg/apis/networkaddonsoperator/v1/group_info.go
pkg/apis/networkaddonsoperator/v1alpha1/group_info.go
test/e2e/workflow/recovery_test.go

This PR is bumping the go.mod go version to 1.19
```release-note
NONE
```

go.mod: Bump go version to 1.19

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

Manual cherry-pick of https://github.com/kubevirt/cluster-network-addons-operator/pull/1629
```release-note
None
```

[release-0.89] bump kube-secondary-dns to v0.0.13

---

components.yaml

This PR changes the components.yaml to follow the kubemacpool `release-0.41` stable branch
```release-note
NONE
```

[release-0.89] components, kubemacpool: Follow release-0.41 stable branch

---

components.yaml
hack/components/git-utils.sh
pkg/components/components.go
test/releases/99.0.0.go

Manual cherry-pick of https://github.com/kubevirt/cluster-network-addons-operator/pull/1629
Also includes:
git-utils: Set tag size explicitly
```release-note
None
```

[release-0.85] bump kube-secondary-dns to v0.0.13

---

.github/workflows/component-bumper.yaml

CNAO will auto bump only the stable branches that are set on the workflow branch matrix.
Updating the supported branches.
```release-note
NONE
```

workflows, auto-bumper: Update supported stable branches

---

components.yaml

This PR changes the components.yaml to follow the ovs-cni `release-0.31` stable branch
```release-note
None
```

[release-0.89] components, ovs-cni: Follow release-0.31 stable branch

---

components.yaml

This PR changes the components.yaml to follow the ovs-cni `release-0.31` stable branch
```release-note
None
```

[release-0.85] components, ovs-cni: Follow release-0.31 stable branch

---

components.yaml

This PR changes the components.yaml to follow the kubemacpool `release-0.40` stable branch
```release-note
NONE
```

[release-0.85] components, Kubemacpool: Follow release-0.40 stable branch

---

components.yaml

This PR changes the components.yaml to follow the ovs-cni `release-0.26` stable branch
```release-note
None
```

[release-0.65] components, ovs-cni: Follow release-0.26 stable branch

---

cluster/up.sh
hack/components/git-utils.sh

Fixes [1]
Openvswitch is already installed in kubevirtci, and NA when trying to dnf install it again.
Remove it to overcome the problem, as it is not necessary.
See https://github.com/kubevirt/cluster-network-addons-operator/pull/1482
[1] https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1644/pull-e2e-cnao-ovs-cni-functests-release-0.76/1719701128226017280
```release-note
None
```

[release-0.76] cluster-up: Fix cluster-up flow

---

components.yaml

This PR changes the components.yaml to follow the ovs-cni `release-0.26` stable branch
```release-note
None
```

[release-0.76] components, ovs-cni: Follow release-0.26 stable branch

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

[release-0.85] components: Bump bridge-marker to 0.11.0

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

[release-0.79] components: Bump bridge-marker to 0.11.0

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

[release-0.89] components: Bump bridge-marker to 0.11.0

---

hack/components/bump-kube-secondary-dns.sh
pkg/components/components.go
test/releases/0.83.0.go
test/releases/0.83.1.go
test/releases/0.84.0.go
test/releases/0.85.0.go
test/releases/0.85.1.go
test/releases/0.85.2.go
test/releases/0.85.3.go
test/releases/99.0.0.go

This PR updates the coreDNS image sha on the bump script and all the relevant test manifests.
```release-note
NONE
```

[release-0.85] Update coredns container and image SHAs

---

automation/release.sh

Stops the /automation/release.sh script from running so that release reverts PRs won't cause false image pushes.
```release-note
NONE
```

automation/release.sh: Temporarily disable release script

---

automation/release.sh

Reverts kubevirt/cluster-network-addons-operator#1692
This PR re-enabled the ability to issue releases on this repo on main branch

Revert "automation/release.sh: Temporarily disable release script"

---

automation/release.sh

Stops the /automation/release.sh script from running so that release reverts PRs won't cause false image pushes.
```release-note
NONE
```

[release-0.89] automation/release.sh: Temporarily disable release script

---

pkg/components/components.go
test/releases/0.76.0.go
test/releases/0.76.3.go
test/releases/0.77.0.go
test/releases/0.78.0.go
test/releases/0.79.0.go
test/releases/0.79.1.go
test/releases/0.79.2.go
test/releases/0.80.0.go
test/releases/0.81.0.go
test/releases/0.82.0.go
test/releases/0.83.0.go
test/releases/0.83.1.go
test/releases/0.84.0.go
test/releases/0.85.0.go
test/releases/0.85.1.go
test/releases/0.85.2.go
test/releases/0.85.3.go
test/releases/0.86.0.go
test/releases/0.86.1.go
test/releases/0.87.0.go
test/releases/0.88.0.go
test/releases/0.89.0.go
test/releases/0.90.0.go
test/releases/0.90.1.go
test/releases/99.0.0.go

Includes https://github.com/openshift/kube-rbac-proxy/pull/80
Affects CNAO and KMP.
`KubeRbacProxyImageDefault` was updated manually to a version
that contains the mention fix (we don't have automation, nor need atm for kube-rbac-proxy).
Before this PR we used `baedb268ac66456018fb30af395bb3d69af5fff3252ff5d549f0231b1ebb6901`
everywhere (via variable).
This PR did the following:
1. Changed from using variable to use static hash, because it is wrong to use variable which exists only at 
`pkg/components/components.go` but might be different between versions.
Since the image might change, it can't use the variable which exists only on `pkg/components/components.go`,
but should have an hard coded value per each release.
See …

Bump kube-rbac-proxy

---

pkg/components/components.go
pkg/components/components_test.go
pkg/network/tlsSecurityProfile.go
pkg/network/tlsSecurityProfile_test.go

The enum "ciphers" contains duplicated entries, since it's Json Schema it should have all unique elements:
https://json-schema.org/understanding-json-schema/reference/enum
The bug has been discovered by @iocanel in https://github.com/fabric8io/kubernetes-client/pull/5611
```release-note
Fixed incorrect generation of ciphers to prevent duplicated enum values.
```

Avoid to emit duplicates for enum fileds

---

components.yaml

This PR is setting CNAO to follow [kubemacpool release-0.42](https://github.com/k8snetworkplumbingwg/kubemacpool/tree/release-0.42) stable branch.
```release-note
NONE
```

[release-0.91] components/kubemacpool: Follow release-0.42 stable branch

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

Update the linux-bridge component to latest in order to bridge the latest changes of bridge CNI that include the new `disableContainerInterface` option https://github.com/containernetworking/plugins/pull/997 
Since there is no tagged version of container network plugins yet, consume that latest version from main branch  https://github.com/containernetworking/plugins/commit/14bdce598f9d332303c375c35719c4a158f1e7db
```release-note
NONE
```

Update linux-bridge component

---

Makefile
automation/check-patch.unit-test.sh

Apply [monitoringlinter](https://github.com/kubevirt/monitoring/tree/main/monitoringlinter) that was implemented in https://github.com/kubevirt/monitoring/pull/221, and was designed to enforce https://github.com/kubevirt/community/pull/219.
This linter ensures that all monitoring-related practices are implemented within the `pkg/monitoring` directory using [operator-observability](https://github.com/machadovilaca/operator-observability/tree/main) methods. It verifies that all metrics, alerts and recording rules registrations are centralized in this directory, and restricts the direct use of [Prometheus registration methods](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#Registerer).
Example for a message reported by the linter: …

Apply monitoring linter

---

go.mod
go.sum
pkg/monitoring/rules/rules_suite_test.go
pkg/monitoring/rules/rules_test.go
vendor/github.com/grafana/regexp/.gitignore
vendor/github.com/grafana/regexp/LICENSE
vendor/github.com/grafana/regexp/README.md
vendor/github.com/grafana/regexp/backtrack.go
vendor/github.com/grafana/regexp/exec.go
vendor/github.com/grafana/regexp/onepass.go
vendor/github.com/grafana/regexp/regexp.go
vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_custom_validations.go
vendor/github.com/machadovilaca/operator-observability/pkg/testutil/alert_validation.go
vendor/github.com/machadovilaca/operator-observability/pkg/testutil/linter.go
vendor/github.com/machadovilaca/operator-observability/pkg/testutil/problem.go
vendor/github.com/machadovilaca/operator-observability/pkg/testutil/recording_rule_validation.go
vendor/modules.txt

Add [operator-observability rules unit test](https://github.com/machadovilaca/operator-observability/tree/main/pkg/testutil), which ensures that alerts and recording rules definitions are following the monitoring best practices, e.g. alerts have all the required annotations and labels with expected values, recording rules have expressions, etc.
Fixes https://issues.redhat.com/browse/CNV-36763
Other PRs references: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/2827, https://github.com/kubevirt/kubevirt/pull/11454
/cc @machadovilaca, @oshoval
```release-note
None
```

Add operator-observability rules unit test

---

Makefile
README.md
manifests/cluster-network-addons/0.92.0/cluster-network-addons-operator.0.92.0.clusterserviceversion.yaml
manifests/cluster-network-addons/0.92.0/namespace.yaml
manifests/cluster-network-addons/0.92.0/network-addons-config-example.cr.yaml
manifests/cluster-network-addons/0.92.0/network-addons-config.crd.yaml
manifests/cluster-network-addons/0.92.0/operator.yaml
manifests/cluster-network-addons/cluster-network-addons.package.yaml
test/releases/0.92.0.go
version/version.go

This is a manual release PR for v0.92.0 since automation is taking v0.90.1 and generating v0.91.0 which is wrong since latest release branch is release-v0.91.0
Closes https://github.com/kubevirt/cluster-network-addons-operator/issues/1792
Generated harcoding these https://github.com/kubevirt/cluster-network-addons-operator/blob/main/hack/prepare-release.sh#L6-L7 with v0.91.0 and v0.92.0, also after finish modified version/version.go
```release-note
NONE
```

release: v0.92.0

---

components.yaml

This Pr sets KMP to follow its relevant stable branch
```release-note
NONE
```

[release-0.93] components: Follow kubemacpool stable branch

---

tools/bumper/component_commands.go
tools/bumper/git_fakes.go

This PR expands the commits range used to find the latest tag when bumping using "tagged" update policy
Fixes https://github.com/kubevirt/cluster-network-addons-operator/issues/1813
```release-note
NONE
```

bumper: Paginate over commits on tagged update policy

---

pkg/network/kubevirt_ipam_controller.go
pkg/network/network.go

Since Kubevirt ipam controller resource names were renamed [1]
since 0.94.0, we introduce the special remove that in case the old named
objects exist, will remove them.
This allows the lifecycle lane to pass, as it checks for leftovers,
which otherwise exists.
[1] https://github.com/kubevirt/cluster-network-addons-operator/pull/1816
```release-note
None
```

KIC: Cleanup of old named resources

---

components.yaml
hack/components/bump-ovs-cni.sh
pkg/components/components.go
test/releases/99.0.0.go

Since the image repository was changed, the scripts had to be updated.
bump ovs-cni to v0.34.0
```release-note
bump ovs-cni to v0.34.0
```

ovs: Fix ovs cni bumper and bump ovs-cni

---

test/check/check.go

Wrong type (ClusterRole) was checked twice.
```release-note
None
```

e2e: Fix leftover check

---

automation/check-patch.e2e-lifecycle-k8s.sh
automation/check-patch.e2e-monitoring-k8s.sh
automation/check-patch.e2e-workflow-k8s.sh
cluster/cluster.sh
hack/bump-kubevirtci.sh

Bump kubevirtci and cleanup unrequired exports.
Allow pinning specific kubevirtci per lane.
It will allow decoupling kubevirtci tag version between the lanes.
```release-note
None
```

kubevirtci: Bump version

---

pkg/network/kubevirt_ipam_controller.go
pkg/network/network.go

Since Certificate and Issuer are not deployed on OpenShift, 
trying to clean them will fail and block the whole flow. 
Filter them out from the cleaning on OpenShift.
```release-note
None
```

ipam: Skip cleanup for non OpenShift types on OpenShift

---

test/e2e/monitoring/rules_test.go

What this PR does / why we need it:
Fix runbook_url test to not expect the alert name as the URL suffix, as in some installations the alert name is not the URL suffix.
e.g. in openshift the runbooks are in https://github.com/openshift/runbooks/tree/master/alerts/openshift-virtualization-operator, and the suffix is `<alert-name>.md`.
```release-note
None
```

Fix runbook_url test

---

tools/manifest-templator/manifest-templator.go

Command line variables of manifest generator should have `_image` suffix for the image related ones.
Also `passtBindingCNIImage` variable was missing "Image" suffix.
In order to be backward compatible, lets first add those variables, use them, and then
we would able to drop the older ones, and the related code that was added for this reason.
The logic is if the old var is set, use that, else use the newer one.
```release-note
None
```

manifest templator: Fix var names

---

.github/workflows/kubevirt-ipam-controller.yaml
automation/components-functests.setup.sh

Since we are using git actions, the resources are limited.
We saw out of space errors, fix them by cleaning the container before
deploying the pods.
Also don't deploy some components to free more memory resources.
Fixes #1844 
```release-note
None
```

kubevirt: Fix deploying kubevirt on git actions

---

data/kubevirt-ipam-controller/004-primary-udn-kubevirt-binding-networkattachdef.yaml

the NAD type introduced to support primary UDN is using
the binary deployed by passt-binding-cni daemonset to the 
node. therefore, the type name should match the binary.
Matching the binary name.
```release-note
NONE
```

primary-udn: Match NAD type to binary name

---

test/check/check.go

Fixes this nil ptr deref
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1850/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1821941283426406400#1:build-log.txt%3A871
Should fix https://github.com/kubevirt/cluster-network-addons-operator/pull/1850#issuecomment-2282653440
Same fix might need to be applied for `isNotSupportedKind`,
but for now the tests didnt trigger it, as they dont reach this case.
```release-note
None
```

tests: Fix isKindNotFound

---

components.yaml
data/kubevirt-ipam-controller/001-kubevirtipamcontroller.yaml
pkg/components/components.go
test/releases/99.0.0.go

Bumped kubevirt ipam controller and added the rbacs also to CNAO,
as CNAO grants those, it should also have them itself.
For more info please see https://github.com/kubevirt/ipam-extensions/pull/54
Required for kubevirt ipam controller bump
`bump kubevirt-ipam-controller to v0.1.5-alpha`
https://github.com/kubevirt/cluster-network-addons-operator/pull/1855#issuecomment-2283498944
```release-note
None
```

Add missing RBACS for kubevirt-ipam-controller

---

README.md
automation/check-patch.e2e-lifecycle-k8s.sh
manifests/cluster-network-addons/0.89.3/cluster-network-addons-operator.0.89.3.clusterserviceversion.yaml
manifests/cluster-network-addons/0.89.3/namespace.yaml
manifests/cluster-network-addons/0.89.3/network-addons-config-example.cr.yaml
manifests/cluster-network-addons/0.89.3/network-addons-config.crd.yaml
manifests/cluster-network-addons/0.89.3/operator.yaml
manifests/cluster-network-addons/0.91.1/cluster-network-addons-operator.0.91.1.clusterserviceversion.yaml
manifests/cluster-network-addons/0.91.1/namespace.yaml
manifests/cluster-network-addons/0.91.1/network-addons-config-example.cr.yaml
manifests/cluster-network-addons/0.91.1/network-addons-config.crd.yaml
manifests/cluster-network-addons/0.91.1/operator.yaml
test/releases/0.89.3.go
test/releases/0.91.1.go

Remove old versions (keep 3 versions + release candid).
Update outdated version to use latest release of each minor.
Add missing releases.
Created this helper script, it will make this process less prone for mistakes
https://github.com/kubevirt/cluster-network-addons-operator/pull/1872
```release-note
None
```

lifecycle: Update RELEASES_SELECTOR

---

components.yaml

This PR set CNAO to follow the latest commit of the kubmacpool relevant stable branch.
```release-note
NONE
```

components/kmp: Follow stable branch

---

hack/update_releases.sh

Also fetches required missing test/releases files.
Helps in creating PRs such as https://github.com/kubevirt/cluster-network-addons-operator/pull/1869
Can be improved to read `RELEASES_SELECTOR` directly from
`automation/check-patch.e2e-lifecycle-k8s.sh`.
Can also be improved to purge non supported versions according
lowest `RELEASES_SELECTOR` element.
Script assumes that if the manifests exists, then the test/releases file also exists
(can be improved later according needs).
Script assumes last element is `99.0.0` so it skips it (it is prerequisite).
We can't make it part of the automation (and not even sanity check due to the following reasons)
because sometimes small changes are needed
for the test/releases …

lifecycle: Add helper script to fetch missing manifests

---

.github/workflows/kubevirt-ipam-controller.yaml

When kubevirt-bot creates PRs, it will trigger the IPAM lane twice, because both
`push` and `pull_request` events occur (the bot creates a branch on main, hence `push` event happens).
The IPAM lane also runs after a PR is merged, because it triggers `push`.
In order to reduce this noise, lets remove the `push` event.
The `pull_request` is enough as long as PRs are used 
(and not direct pushes which aren't encouraged, nor monitored anyhow).
```release-note
None
```

ipam: Reduce git actions noise

---

automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh

When testing ipam on kind, the `guest-console-log` readiness flakes.
It is not related to IPAM lane, and it is also disabled on OVN-K8s repo once kubevirt is deployed and tested.
Disable it also when deploying kubevirt via helper scripts on CNAO.
Worth to raise it to the virt team in parallel, atm lets just line up as OVN-K8s repo does.
```release-note
None
```

ipam,e2e: Add disableSerialConsoleLog

---

automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh
components.yaml
pkg/components/components.go
test/releases/99.0.0.go

Beside the bump, adapt the automation script for this bump:
Since https://github.com/kubevirt/ipam-extensions/pull/60
allows custom kubeconfig, we should set the line before cluster-up,
so it won't take the value set by automation/components-functests.setup.sh
which is correct only for kubevirtci providers, not for external ones.
Hence set it just before cluster-up.
```release-note
bump kubevirt-ipam-controller to v0.1.7-alpha
```

bump kubevirt-ipam-controller to v0.1.7-alpha

---

tools/bumper/cnao_repo_commands.go
tools/bumper/cnao_repo_commands_test.go

In the bumper logic, in case either currentReleaseVersion or latestReleaseVersion are in virtual-tag format (i.e. v0.44.1-1-g4cd33665) - then the bump should be initiated. However the logic implementing it is wrong.
Fixing logic, adding unit tests.
```release-note
NONE
```

tools/bumper: Fix latest vtag check

---

tools/bumper/cnao_repo_commands.go
tools/bumper/cnao_repo_commands_test.go

The bumper currently assumes that virtual tags consists of eight sha
characters after the "g" (for example: v0.39.0-32-g12345678).
This is not the default configuration (which is seven).
As this number of sha characters is configurable, this PR is changing the
regex in isVtagFormat to accept any number of character (bigger than
four which is what 'git describe --abbrev=X' accepts) as a valid vtag
format.
Also, fixing unit tests to use character aligned to the default and
adding more to check the above logic.
```release-note
NONE
```

tools/bumper: Allow general vtag format.

---

Makefile

This target needs that the necessary tooling is available beforehand.
**What this PR does / why we need it**: makefile minor fixes
```release-note NONE
```

fix: dependency in prom-rules-verify make target

---

Makefile

This update is beneficial for enabling multiarch support. By default, some tooling is downloaded specifically for amd64. Even with changes in the scripts, the tool does not get updated.
**What this PR does / why we need it**: s390x enablement
```release-note NONE
```

feat: clean task in Makefile

---

README.md
cluster/cluster.sh

This PR bumps KUBEVIRT_PROVIDER and KUBEVIRTCI_TAG to more updated values.
```release-note
NONE
```

Bump k8s provider to 1.30

---

pkg/components/components.go
test/releases/99.0.0.go

architecture. This change deploys an image that is multi arch supported.
The origin-kube-rbac-proxy image is not compatible with the s390x architecture. 
This change deploys an image that is multi arch supported and this will enable
CNAO on s390x architecture to get started and test CNAO supported CNI plugins
proposed image(https://quay.io/repository/brancz/kube-rbac-proxy/manifest/sha256:e6a323504999b2a4d2a6bf94f8580a050378eba0900fd31335cf9df5787d9a9b) is built from parent repo of https://github.com/openshift/kube-rbac-proxy.
```release-note
None
```

The origin-kube-rbac-proxy image is not compatible with the s390x

---

tools/prom-rule-ci/verify-rules.go

As of version 2.15.2, there is no available container image for s390x. However, version 2.25.2 does provide support for this architecture. This update enables the checks to run on s390x.
**What this PR does / why we need it**: s390x enablement
```release-note NONE
```

feat: enable s390x prometheus check

---

pkg/controller/statusmanager/status_manager.go

CNAO is emitting  config 'Availabe' event after each reconcile even when nothing changes, this add noise to users. This change emits the event only if Available changes from false to true.
Some test suites like openshift tests fail if it sees too many duplicated events during a period of times, so it's fair to fix that by not sending events when the state didn't change.
```release-note
events: Remove duplicated 'Available' events
```

events: Remove duplicated 'Available' events

---

.dockerignore
Makefile
build/operator/Dockerfile
hack/build-operator-docker.sh
hack/build-operator-podman.sh
hack/init-buildx.sh

These changes enable building and pushing CNAO operator image for multiple platforms (amd64, s390x, arm64) from a single Dockerfile. Enhanced multi-platform support in the build process by adding a PLATFORMS argument in the Makefile for amd64, s390x, and arm64 architectures. Updated the docker-build-operator target to support builds with docker buildx and podman, and added new targets for creating Docker Buildx builders and pushing multi-platform images.
The existing CNAO operator ([link](https://quay.io/repository/kubevirt/cluster-network-addons-operator?tab=tags&tag=latest)) currently supports only the amd64 architecture. These changes extend multi-platform support to include arm64 and s390x architectures, enabling broader compatibility for the …

Enable multi-platform support for operator image builds

---

.github/workflows/kubevirt-ipam-controller.yaml

It has been observed that build actions, such as free disk space, are broken with ubuntu-latest, which now points to Ubuntu 24.04. To resolve this, we are switching to the ubuntu-22.04 tag, which was previously used by ubuntu-latest.
ubuntu-latest now uses Ubuntu 24.04, while it used to use 22.04. 
To unblock Github CI in  the short term, we can switch to ubuntu-22.04,
Error log with ubuntu-latest is available at : https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4914
```release-note
None
```

Update workflow to use Ubuntu 22.04

---

hack/build-operator-podman.sh
hack/components/bump-linux-bridge.sh

These updates allow the building and pushing of Linux Bridge container images for multiple platforms (e.g., amd64, s390x) using a single Dockerfile. Multi-platform build support is provided for both Docker and Podman container runtimes.
"The upstream **cni-default-plugins** image ([[link](https://quay.io/repository/kubevirt/cni-default-plugins?tab=tags&tag=latest)](https://quay.io/repository/kubevirt/cni-default-plugins?tab=tags&tag=latest)) currently supports only the amd64 architecture. The proposed changes in this PR enable multi-platform support for the **linux-bridge** image, broadening its compatibility to include additional architectures like s390x."
Multi-platform build support is enabled for both Docker …

Enable support for multiple platforms in the Linux Bridge CNI.

---

automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh
components.yaml
data/kubevirt-ipam-controller/001-kubevirtipamcontroller.yaml
pkg/components/components.go
test/releases/99.0.0.go

Bump kubevirt-ipam-controller to v0.1.9-alpha
Adapt to support IPAM UDN tests with managedTap binding on CNAO.
```release-note
NONE
```

Bump ipam to v0.1.9-alpha and enable managed tap

---

.github/workflows/kubevirt-ipam-controller.yaml

Build actions, including free disk space, are broken on ubuntu-latest, which now points to Ubuntu 24.04. To resolve this, we have removed the non-existent package from ubuntu-latest.
We are making these changes to align with the updates in OVN-Kubernetes, as seen in https://github.com/ovn-kubernetes/ovn-kubernetes/pull/4920.
```release-note
None
```

Remove non-existent package msbuild from latest ubuntu images.

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

multus-dynamic-networks v0.3.5 is breaking. Pin to latest successful version until the issue is resolved
```release-note
NONE
```

components/multus-dynamic-networks: Pin to v0.3.4

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

These changes will allow us to bump the linux-bridge component whenever a new tag is available.
Bump the commit to use the tag [[v1.5.1](https://github.com/containernetworking/plugins/releases/tag/v1.5.1)](https://github.com/containernetworking/plugins/releases/tag/v1.5.1).
Please note that or the latest tags, [v1.6.0](https://github.com/containernetworking/plugins/releases/tag/v1.6.0) and [v1.6.1](https://github.com/containernetworking/plugins/releases/tag/v1.6.1), we need Go version 1.23.
I have created a PR for the changes mentioned above: [[PR #1953](https://github.com/kubevirt/cluster-network-addons-operator/pull/1953)](https://github.com/kubevirt/cluster-network-addons-operator/pull/1953). Once this PR is …

Update linux-bridge component commit to plugin v1.5.1

---

hack/bumper.sh

Ease go package bumping.
```release-note
None
```

Add bumper script

---

cluster/cert-manager-install.sh

Right now if cert-manager deployments fail - we do not know. 
Adding appropriate waits.
```release-note
NONE
```

cluster/cert-manager-install: Wait for deployments to be ready

---

components.yaml

This PR changes the update-policy of multus-dynamic-networks to tagged.
```release-note
NONE
```

components, multus-dynamic-networks: update_policy to tagged

---

hack/components/bump-linux-bridge.sh

We encountered an unexpected failure in the job pull-cluster-network-addons-operator-unit-test-release-0.97(in pr: https://github.com/kubevirt/cluster-network-addons-operator/pull/1983) while performing a multi-architecture build for the Linux bridge. As a result, to unblock, we have adjusted the default build process to target the host architecture rather than building for all architectures by default.
```release-note
None
```

set default platform based on host-architecture for linux bridge build.

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

This PR is a manual bump of multus-dynamic-networks to v0.3.6
```release-note
NONE
```

[Release 0.97] bump multus-dynamic-networks v0.3.6

---

automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh
components.yaml
data/kubevirt-ipam-controller/001-kubevirtipamcontroller.yaml
pkg/components/components.go
test/releases/99.0.0.go

This PR pins kubevirt-ipam-controller to v0.2.0
```release-note
NONE
```

vendor: Pin kubevirt-ipam-controller to v0.2.0

---

data/kube-secondary-dns/secondarydns.yaml
data/kubemacpool/kubemacpool.yaml
data/kubevirt-ipam-controller/001-kubevirtipamcontroller.yaml
data/kubevirt-ipam-controller/003-passtbindingcni.yaml
data/linux-bridge/002-linux-bridge.yaml
data/linux-bridge/003-bridge-marker.yaml
hack/components/bump-bridge-marker.sh
hack/components/bump-kube-secondary-dns.sh
hack/components/bump-kubemacpool.sh
hack/components/bump-kubevirt-ipam-controller.sh

This PR adds the `required-scc` annotation to the CNAO components.
It's an harmless annotation, and simplifies the code. Given the urgency of this, we do not try to add the annotation only when deploying on an OpenShift cluster; this should/could be done in a follow-up.
```release-note
Adds the `openshift.io/required-scc` annotation to all CNAO components.
```

Use OpenShift's required-scc annotation on components

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

This is s manual bump of ovs to v0.38.0
```release-note
NONE
```

vendor: Pin ovs-cni to v0.38.0

---

tools/bumper/cnao_repo_commands_test.go
tools/bumper/component_commands_test.go

This PR is refactoring the bumper unit tests to use DeferCleanup, following a [discussion](https://github.com/kubevirt/cluster-network-addons-operator/pull/1971#discussion_r1905430675) in anotherPR
```release-note
NONE
```

tools/bumper: Refactor using DeferCleanup

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

This reverts commit 27a3e85372bf86929ffc62ea1fe954375e24e4ba.
```release-note
NONE
```

[release-0.97] Revert "vendor: Pin ovs-cni to v0.38.0 (#1995)"

---

Makefile

This pr is upgrading the metrics linter to latest version which [bumps go to 1.23](https://github.com/kubevirt/monitoring/pull/283) and fix the type issue, see https://github.com/kubevirt/cluster-network-addons-operator/issues/2005#issuecomment-2662343204
Fixes #2005
```release-note
none
```

Upgrade monitoring linter to latest

---

data/kubevirt-ipam-controller/003-passtbindingcni.yaml
hack/components/bump-kubevirt-ipam-controller.sh
pkg/network/kube_secondary_dns_controller.go
pkg/network/kubevirt_ipam_controller.go
pkg/network/kubevirt_ipam_controller_test.go
pkg/network/placement_configuration.go

The components installed by CNAO should follow the kind of placement configuration done by HCO components by default so features like node drain work similar.
In this case CNAO was configuring deployments that are part of the controlplane as part of the Workload this means that they will run at workers and that they will not evict after drain (they should not since they are not daemonsets), this PR move those to Infra placemnt and also remove invalid tolerationsn from Infra.
Closes https://issues.redhat.com/browse/CNV-56947
```release-note
Move control plane deployments to infra placement
```

Align placement with HCO components

---

automation/check-patch.unit-test.sh

This PR adds a vendor check before `make check`, so that we can make sure that the go files are aligned.
```release-note
NONE
```

automation/unit-test: Add vendor check

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

Used `CNAO_VERSION=99.0.0 ./hack/components/bump-bridge-marker.sh`
Since it is static, had to do it manually (we don't have branches on bridge marker).
```release-note
None
```

[release-0.97] bridge marker: Bump to 0.12.1

---

Makefile

In order to protect us from bumping either manually or by Renovate bot, 
go toolchain / lang higher than allowed for stable branches, guard was added to Makefile.
Notes:
1. The guard doesn't protect from bumping higher than allowed Z stream, only X.Y.
2. The guard should be added once the go.mod file has the highest allowed, or at least to know that if you add it as is, you need to update both in case you update go.mod.
3. The guard will disregard toolchain line if such doesn't exists.
4. For simplicity the guard protects the that max normalized (without Z) allowed version match both language level and toolchain, but it is allowed basically that the toolchain will be higher than the lang level on go.mod, so this is extra safty that we might want to remove.
Tried to keep it simple for …

Makefile: Enforce max allowed version

---

components.yaml

CNAO main branch should follow the latest changes on kubemacpool, and if necessary - fail fast in order to fix fast.
```release-note
NONE
```

components/kmp: Follow latest main branch

---

components.yaml

Following the increase in traffic, limiting kubmacpool bumps to only tagged versions on the stable branch
```release-note
NONE
```

[release-0.95] components/kmp: Follow tagged releases

---

components.yaml

Following the increase in traffic, limiting kubmacpool bumps to only tagged versions on the stable branch
```release-note
NONE
```

[release-0.97] components/kmp: Follow tagged releases

---

.dockerignore
.gitignore
automation/check-patch.setup.sh
test/check/check.go
test/e2e/lifecycle/main_test.go
test/e2e/workflow/main_test.go
test/reporter/reporter.go
test/reporter/writers.go

Currently when a test fails on CNAO main lanes, the logs are printed to the screen, which makes it hard to debug. Moreover, there is no guarantee that the cleanup hasn't already commenced - giving a false picture of the cluster when the test failed.
Refactor the reporter to write the logs to files.
Refactor to use ginkgo's JustAfterEach to ensure that the cleanup is not yet started.
Examples of artifacts collected using this change:
- [lifecycle lane](https://gcsweb.ci.kubevirt.io/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/2168/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1904825531044466688/artifacts/)
- [workflow lane](https://gcsweb.ci.kubevirt.io/gcs/kubevirt-prow/pr-logs …

e2e: log failed tests to artifacts

---

test/check/check.go

Currently e2e checkForComponentRemoval does not check removal of deployments and Daemonsets. This can cause cross-talk noise between tests, especially in workflow and lifecycle lanes.
This PR is adding checks that Daemonset and Deployments are removed.
```release-note
NONE
```

e2e/check: Verify Deamonset, Deployment removal

---

.github/workflows/component-bumper.yaml

This PR removes unsupported branches from the auto bumper gitActions.
```release-note
NONE
```

gitActions, bumper: Remove unsupported branches

---

components.yaml

OVS-CNI is to follow tagged releases on stable branch.
```release-note
NONE
```

[release-0.97] components, ovs-cni: Follow tagged

---

test/check/check.go
test/e2e/workflow/deployment_test.go

Currently checkConfigChange waiting on the transient status condition of
the CNAO CR, in order to make sure that the component is properly
deployed.
This is raceful by design, as if the component deployment moved "too
fast" to ConditionProgressing=TRUE then the test will fail.
Also, there is another race where the Available condition might change before the operator changed the status to in progress. 
This PR is changing the test to fix these two races.
Fix #626
```release-note
NONE
```

e2e/workflow: Fix race waiting for components

---

cluster/cluster.sh

updating the KubeVirt CI tags to the latest version: [KubeVirt CI Tags](https://github.com/kubevirt/kubevirtci/tags).
The latest tag, 2503281142-a291de27, is now multi-architecture supported(We can't create kubevirtci cluster other than amd64 platform with existing tag(https://github.com/ashokpariya0/cluster-network-addons-operator/blob/2edc8b58f002438464e33576454b229d7bd6d5ea/cluster/cluster.sh#L16)), and you can find more details here: [KubeVirt CI Multi-Arch Tag](https://quay.io/repository/kubevirtci/gocli?tab=tags&tag=latest).
```release-note
None
```

Bump kubevirtci to use a tag with multi-architecture support

---

.github/workflows/kubevirtci-bumper.yaml

This PR introduces a gitActions that will run the kubevirtci bumper every 3 months, in order to keep CNAO up to date.
```release-note
NONE
```

gitActions: Add workflow to bump kubevirtci

---

test/reporter/reporter.go
test/reporter/writers.go

This PR adds more logs when an e2e test fails. These will assist in future debugging.
Example [artifacts](https://gcsweb.ci.kubevirt.io/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/2230/pull-e2e-cluster-network-addons-operator-workflow-k8s/1909193081664573440/artifacts/)
```release-note
NONE
```

e2e, reporter: Enhance debugging logs

---

.gitignore
tools/vendor/golang.org/x/tools/cmd/goimports/doc.go
tools/vendor/golang.org/x/tools/cmd/goimports/goimports.go
tools/vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
tools/vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go
vendor/golang.org/x/tools/cmd/goimports/doc.go
vendor/golang.org/x/tools/cmd/goimports/goimports.go
vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go

Fix vendoring of golang.org/x/tools/cmd/goimports

---

automation/test-nightly-build.sh

The nightly test failed with:
```
/automation/test-nightly-build.sh: line 37: cnao_bucket: unbound variable
```
This PR fixes this failure by moving the assigning of the `cnao_bucket` environment variable, before the first use of it.
```release-note
None
```

Fix the nightly build

---

.gitignore
vendor/golang.org/x/tools/cmd/goimports/doc.go
vendor/golang.org/x/tools/cmd/goimports/goimports.go
vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go

[release-0.97] Fix vendoring of golang.org/x/tools/cmd/goimports

---

.gitignore
vendor/golang.org/x/tools/cmd/goimports/doc.go
vendor/golang.org/x/tools/cmd/goimports/goimports.go
vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go

[release-0.95] Fix vendoring of golang.org/x/tools/cmd/goimports

---

.gitignore
vendor/golang.org/x/tools/cmd/goimports/doc.go
vendor/golang.org/x/tools/cmd/goimports/goimports.go
vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go

[release-0.91] Fix vendoring of golang.org/x/tools/cmd/goimports

---

.gitignore
vendor/golang.org/x/tools/cmd/goimports/doc.go
vendor/golang.org/x/tools/cmd/goimports/goimports.go
vendor/golang.org/x/tools/cmd/goimports/goimports_gc.go
vendor/golang.org/x/tools/cmd/goimports/goimports_not_gc.go

[release-0.93] Fix vendoring of golang.org/x/tools/cmd/goimports

---

automation/test-nightly-build.sh

At the end of the nightly build, the automation/test-nightly-build.sh script copies the artifact files to a gcp bucket using the gsutil. The script, as currently implemented, copies the files to the a file named the build date, overriding the last copied file, instaed of to a directory with the name of the build date.
e.g.
```shell
curl https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/cluster-network-addons-operator/20250502
```
returns the network-addons-config-example.cr.yaml file, while
```shell
curl https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/cluster-network-addons-operator/20250502/network-addons-config-example.cr.yaml
```
returns 404.
And all the other files are not there, because they …

Fix nightly build

---

automation/test-nightly-build.sh

On nightly build, create and publish the `commit` file, with the current git commit.
This will allow linking the specific build with the corresponding commit.
```release-note
None
```

Nightly build: publish the commit file

---

automation/test-nightly-build.sh

The script failed because of a redundent characture '.' (a leftover).
This PR removes the redundent characture.
```release-note
None
```

fix the test-nightly-build.sh script

---

automation/test-nightly-build.sh

The nightly build fails to push images to quay.io
login to quay.io before trying to push the image.
```release-note
None
```

nightly: login to quay.io

---

pkg/components/components.go

To comply with best practices, all the containers in all the pods, must set the TerminationMessagePolicy field to FallbackToLogsOnError [0]
[0]
https://github.com/redhat-best-practices-for-k8s/certsuite/blob/main/CATALOG.md#observability-termination-policy
```release-note
NONE
```

Set container's TerminationMessagePolicy to FallbackToLogsOnError

---

test/check/check.go
test/check/components.go

When running a CNAO CR, CNAO creates a prev config of the last applied configuration, in order to ensure persistent reconfiguration in case a re-install took place on an existing CR. For example, if kubemacpool was redeployed, it will remember the ranges.
This however creates a test race when checking that removing the CNAO CR recreates the kubemacpool ranges when redeployed after CR deletion. 
This PR is adding a check to ensure the configmap was removed after CR deletion, in order to fix this race.
Fix #2202 
```release-note
NONE
```

tests: Check for configMap deploy and removal

---

components.yaml
pkg/components/components.go
test/releases/99.0.0.go

This PR is a manual bump of KMP to [v0.47.0](https://github.com/k8snetworkplumbingwg/kubemacpool/releases/tag/v0.47.0)
PR is issued manually because auto bumper cannot  bump due to an open issue #2278 .
```release-note
NONE
```

components: Bump kubemacpool to v0.47.0

---

components.yaml

This PR sets CNAO to follow KMP's stable branch [release-0.47](https://github.com/k8snetworkplumbingwg/kubemacpool/tree/release-0.47)
```release-note
NONE
```

[release-0.99] Follow kubemacpool stable branch

---

automation/check-patch.e2e-workflow-k8s.sh

Some of the components deployed in the deployments e2e test require kubevirt (ipam-ext, ksd, kubemacpool). Without it, they may restart, causing instability in the networkAddonsConfig CR status.
This PR is deploying kubevirt as a pre-step to the workflow automation in order to provide stability in the e2e runs.
```release-note
NONE
```

automation/workflow: Pre-install kubevirt

---

automation/test-nightly-build.sh

The nightly build is failing when trying to push the CSV file, as it's name is wrong.
This PR fixes the CSV file name to allow pushing it to the remote storage.
```release-note
None
```

Fix failure in nightly build

---

pkg/components/components.go

Enable CNAO create read/write NetwrokPolicy objects.
This permissions is require for CNAO to deploy the components network-policy objects.
Enable CNAO create read/write NetwrokPolicy objects.
This permissions is require for CNAO to deploy the components
network-policy objects.
This PR changes should fix https://github.com/kubevirt/cluster-network-addons-operator/pull/2295 failures on CI, for example https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/2295/pull-e2e-cluster-network-addons-operator-br-marker-functests/1924377354927345664#1:build-log.txt%3A952
```release-note
rbac: Allow read/write network-policy objects
```

components,rbac: Grant permissions for r/w network-policies

---

tools/bumper/bumper.go
tools/bumper/cnao_repo_commands.go
tools/bumper/cnao_repo_commands_test.go

In the case where component follows **latest** of branch, and that branch issues a release (=tag), then the auto bumper needs to prefer the new tag over the virtual tag and initiate a bump. It is needed in order to refresh the component's image sha256 using the new tag.
This PR change bumper code to prefer real tags.
Fixes https://github.com/kubevirt/cluster-network-addons-operator/issues/2278
```release-note
NONE
```

tools/bumper: Initiate bump after branch following latest is tagged

---

automation/test-nightly-build.sh

To align with KubeVirt and CDI nightly builds, move the CNAO image from quay.io/kubevirtci registry, to quay.io/kubevirt, and remove the `"nb_"` prefix from the image tag.
```release-note
Move the nightly build images to the quay.io/kubevirt registry
```

Move the nightly build images to quay.io/kubevirt

---

data/kube-secondary-dns/secondarydns.yaml
hack/components/bump-kube-secondary-dns.sh

kube-secondary-dns introduce network-policy since v0.0.22.
Installing KSD network-policy allow it to operate when network restrictions in form of default deny-all network-policy is in place.
This PR extend the bump-kube-secondary-dns automation to consume the project network-policy manifests.
And make CNAO install KSD network-policy, when KSD is installed.
```release-note
CNAO install kube-secondary-dns network-policy
```

Consume and install kube-seconday-dns network-policy

---

data/kube-secondary-dns/secondarydns.yaml
data/kubemacpool/kubemacpool.yaml
data/kubevirt-ipam-controller/001-kubevirtipamcontroller.yaml
hack/components/bump-kube-secondary-dns.sh
hack/components/bump-kubemacpool.sh
hack/components/bump-kubevirt-ipam-controller.sh
pkg/components/components.go

Enable CNAO operator and its operands pors operate when network restrictions in form of defaultl deny-all network-policy is in place, when managed by HCO.
The hco-bundle should provide network-policies allowing its operands work when network restrictions are in place.
In order to opt-in pods for the provided network-policies pods should be labeled with the following labels:
1. `hco.kubevirt.io/allow-access-cluster-services`
Allow access the cluster API and DNS.
This is a fundamental requirement for a k8s controller to oprate, it is requiremd for the following compoents:
- kubemacpool
-  ipam-extentions
- kube-secondary-dns
2. `hco.kubevirt.io/allow-prometheus-access` 
Allow Prometheus pods ingress the metrics endpoint
Required by CNAO opreator pods, …

Opt-in for network-policies provided by hco-bundle for CNAO and its components pods

---

data/linux-bridge/001-rbac.yaml
data/linux-bridge/002-linux-bridge.yaml

This pull request improves the security posture of the linux-bridge SecurityContextConstraints (SCC) by introducing two changes:
1. **Restrict SELinux context** to `MustRunAs` with `spc_t` type.
2. **Restrict allowed volume types** to only `hostPath`, `configMap`, and `secret`.
To anticipate reviewers request, [commented](https://github.com/kubevirt/cluster-network-addons-operator/pull/2331#issuecomment-2943335474) on the PR why I did NOT remove other SCCs.
```release-note
reduce linux bridge SCC
```

Linux bridge:  Harden SCC by restricting SELinux context and allowed volume types

---

automation/check-patch.e2e-kube-secondary-dns-functests.sh
automation/check-patch.e2e-kubemacpool-functests.sh
automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh
automation/check-patch.e2e-monitoring-k8s.sh
automation/check-patch.e2e-workflow-k8s.sh
hack/install-network-policy.sh

Following recent work for allowing CNAO pods operate in network restricted environment 
this PR add test coverage by simulating network restrictions on the project namespace.
The automation install default deny-all network-policy with the following exceptions:
1. Allow egress to cluster API and DNS for pods who labeled with `hco.kubevirt.io/allow-access-cluster-services`
2. Allow ingress to metrics endpoint to pods who labeled with `hco.kubevirt.io/allow-prometheus-access`
The additional network-policies allowing the above exceptions provider verify 
opt-in for network-policy provided by hco using labels works and CNAO pods can operate.
The affected CI jobs are as follows:
- `pull-e2e-cluster-network-addons-operator-workflow-k8s`
- …

CI: Add test coverage for network-policies by simulate network restrictions

---

automation/test-nightly-build.sh

Following #2348 the nightly-build job was missing out.
This PR add test coverage for network-policies in the nightly build job.
```release-note
NONE
```

CI: Add test coverage for network-policies in nightly-build jobs
