- cluster/sync.sh
Change the sed command to find quay.io/kubevirt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/6)
> Fix the cluster_sync

- build/Dockerfile
Several bugs were introduced with multi-stage dockerfile PR. This PR should fix them.
> fix dockerfile

- cmd/manager/main.go
cmd/manager/main.go:98: Println call has possible formatting directive %v
> Fixed build warning

- pkg/network/sriov.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/24)
> Fix image pull policy for sriov

- README.md
- config-example.yaml
- data/kubemacpool/000-ns.yaml
- data/kubemacpool/001-rbac.yaml
- data/kubemacpool/002-configmap.yaml
- data/kubemacpool/003-secret.yaml
- data/kubemacpool/004-statefulset.yaml
- deploy/cluster-network-addons-operator_03_deployment.yaml
- pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
- pkg/network/kubemacpool.go
- pkg/network/network.go
This PR add the kubemacpool into the operator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/8)
> add kubemacpool to the operator

- data/linux-bridge/002-linux-bridge.yaml
Revert in order to fix some unresolved comments.
> Revert "Change the linux deployment yaml"

- README.md
> Document that SR-IOV network is not created by the operator

- README.md
We forgot to update some parts of the README with added features. Let's fix it.
> update README with some forgotten fields

- README.md
- deploy/crds/network-addons-config-example.cr.yaml
- pkg/components/components.go
- pkg/network/kubemacpool.go
generate a range using a prefix of {0x02,<random>,<random>} if the range was not provided by the administrator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/50)
> Generate macpool range

- build/operator/Dockerfile
Images we use have known issues in their packages, make sure to upgrade
on build.
> upgrade base image packages while building images

- pkg/components/components.go
- tools/manifest-templator/manifest-templator.go
We need this change to integrate with HCO.
> allow namespace adjustment during manifests build

- README.md
- data/kubemacpool/002-configmap.yaml
- data/kubemacpool/004-deployment.yaml
- manifests/cluster-network-addons/0.3.0/cluster-network-addons-operator.v0.3.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.4.0/cluster-network-addons-operator.0.4.0.clusterserviceversion.yaml
- pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
- pkg/components/components.go
- pkg/network/kubemacpool.go
- templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
changed startPoolRange to startRange and endPoolRange to endRange,
since it is obvious that it is the pool range.
> startPoolRange and endPoolRange Name changed

- Makefile
- README.md
- automation/check-patch.k8s-1.11.0.mounts
- automation/check-patch.k8s-1.11.0.packages
- automation/check-patch.k8s-1.11.0.sh
- automation/check-patch.os-3.11.0.mounts
- automation/check-patch.os-3.11.0.packages
- automation/check-patch.os-3.11.0.sh
- automation/check-patch.packages
- automation/check-patch.sh
- automation/test.sh
- cluster/functest.sh
- hack/build-manifests.sh
- stdci.yaml
This test deploys operator, creates its config CR and waits until
all components are successfully deployed.
>  run basic functional test on STD-CI

- README.md
- hack/release.sh
> add helper script to make releasing easier

- .gitignore
- build/Dockerfile
I also add build/_output to the .gitignore file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/88)
> Fix operator-sdk generate command

- pkg/components/components.go
Pin network components for the operator.
After this PR I will open another one to make a release of version 0.6.0 for the operator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/92)
> Pin components version

- Makefile
- README.md
- manifests/cluster-network-addons/0.6.0/cluster-network-addons-operator.0.6.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.6.0/namespace.yaml
- manifests/cluster-network-addons/0.6.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.6.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.6.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
This release include the linux bridge marker image
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/95)
> Release 0.6.0

- pkg/components/components.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/96)
> Bump kubemacpool version to v0.3.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.7.0/cluster-network-addons-operator.0.7.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.7.0/namespace.yaml
- manifests/cluster-network-addons/0.7.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.7.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.7.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
This release update the kubemacpool to version v0.3.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/97)
> Release 0.7.0

- templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
We forgot to update our templates.
> update manifests templates with nmstate changes

- Makefile
- README.md
- manifests/cluster-network-addons/0.8.0/cluster-network-addons-operator.0.8.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.8.0/namespace.yaml
- manifests/cluster-network-addons/0.8.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.8.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.8.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- adds nmstate component
- fixes kubemacpool bug that was failing re-applying of operator CR
> Release 0.8.0

- pkg/components/components.go
It contains fixes to startup linux bridges
> Bump nmstate to v0.2.0

- pkg/apply/apply_suite_test.go
- pkg/apply/merge_test.go
Tests are copied from [1], just transformed to Gomega.
[1] https://github.com/openshift/cluster-network-operator/blob/master/pkg/apply/merge_test.go
> test merge.go module

- pkg/network/image-pull-policy_test.go
- pkg/network/linux-bridge_test.go
- pkg/network/multus.go
- pkg/network/multus_test.go
- pkg/network/network_test.go
- pkg/network/nmstate_test.go
- pkg/network/sriov_test.go
Finish test coverage for pkg/network. This patch also fixes a bug in multus
validation where we tried to compared bool pointers.
> test network package

- build/operator/Dockerfile
Let's align it with the rest of stuff here
Signed-off-by: Quique Llorente <quique.llorente@gmail.com>
> Compile operator with 1.11

- templates/cluster-network-addons/VERSION/cluster-network-addons-operator.VERSION.clusterserviceversion.yaml.in
We have to expose CRD group in the CSV, otherwise we will fail.
> expose NetworkAddonsConfig CRD group in CSV

- pkg/apis/networkaddonsoperator/v1alpha1/networkaddonsconfig_types.go
- pkg/components/components.go
- pkg/controller/statusmanager/status_manager.go
- test/check/check.go
- test/e2e/main_test.go
- test/e2e/version_test.go
- tools/manifest-templator/manifest-templator.go
Let's report operator version and version of deployed components set
in Status portion on NetworkAddonsConfig.
> report version in Status

- test/e2e/deployment_test.go
Let's make tests faster by reusing already pulled images.
> don't use PullAlways in tests

- test/e2e/deployment_test.go
KubeMacPool is known to restart shortly after first started, skip
this initial restart.
https://github.com/kubevirt/cluster-network-addons-operator/issues/141
> include KubeMacPool in functional tests

- test/check/check.go
- test/e2e/workflow/version_test.go
Nobody wants to read goroutines while going through tests.
> add keep checking while test helper

- hack/release.sh
> fix generating of release modules in release.sh [2]

- Makefile
- README.md
- manifests/cluster-network-addons/0.10.0/cluster-network-addons-operator.0.10.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.10.0/namespace.yaml
- manifests/cluster-network-addons/0.10.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.10.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.10.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.11.0.go
:fireworks: 
* Improved test coverage of the whole project
* Fixed OLM integration
* Improved status reporting, including upgrade monitoring
* SR-IOV CNI config fix
> Release 0.10.0

- Makefile
> Refactor VERSION in Makefile

- test/check/check.go
- test/e2e/lifecycle/upgrade_test.go
Test upgrades from previous releases to the current one.
> add upgrade tests to lifecycle suite

- Makefile
> Install vendor tools before using them

- Makefile
- README.md
- manifests/cluster-network-addons/0.11.0/cluster-network-addons-operator.0.11.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.11.0/namespace.yaml
- manifests/cluster-network-addons/0.11.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.11.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.11.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.12.0.go
Generated by ./hack/release.sh 0.10.0 0.11.0 0.12.0 upstream origin
> Release 0.11.0

- test/check/check.go
- test/e2e/workflow/deployment_test.go
-test that after kubemacpool re-installation a new range is been
generated.
> add func-test for kubemacpool

- Makefile
This PR add the test folder in the fmt and vet commands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/184)
> Add the fmt and vet functionality to test folder

- pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
- pkg/controller/statusmanager/status_manager.go
- test/e2e/workflow/validation_test.go
This change is needed to follow HCO's standard for conditions [1].
[1] https://github.com/kubevirt/hyperconverged-cluster-operator/blob/master/docs/conditions.md
> Report unavailable when valiadation fails

- data/nmstate/001-rbac.yaml
- data/nmstate/002-crd.yaml
- data/nmstate/003-operator.yaml
- pkg/components/components.go
- test/check/check.go
It includes upgrade of nmstate to 0.0.8 and activation of
vlan_filtering for linux-bridges
> Bump nmstate to 0.6.0

- pkg/apply/apply.go
In older versions of the operator, we used daemon sets of type
'extensions/v1beta1', later we changed that to 'apps/v1'. Because of this
change, we are not able to seamlessly upgrade using only Update methods.
Following code handles this exception by deleting the old daemon set and
creating a new one.
This workaround should be dropped once we handle upgrades of each
component in their respective modules.
> fix upgrade of bridge-marker

- Makefile
- README.md
- manifests/cluster-network-addons/0.13.0/cluster-network-addons-operator.0.13.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.13.0/namespace.yaml
- manifests/cluster-network-addons/0.13.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.13.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.13.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.14.0.go
* Fixed upgrade from 0.7.0
* Bumped OVS CNI version to v0.7.0
> Release 0.13.0

- hack/generate-manifests.sh
- pkg/components/components.go
- tools/manifest-templator/manifest-templator.go
Fixes: https://github.com/kubevirt/cluster-network-addons-operator/issues/221
Signed-off-by: Ido Rosenzwig <irosenzw@redhat.com>
> Add operatorVersion for the CSV generator

- Makefile
- README.md
- manifests/cluster-network-addons/0.14.0/cluster-network-addons-operator.0.14.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.14.0/namespace.yaml
- manifests/cluster-network-addons/0.14.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.14.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.14.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.15.0.go
* add operator version to CSV generator
* reduce kubemacpool resource requirements
* drop Failing condition from pre-0.12.0 versions
> Release 0.14.0

- data/kubemacpool/003-deployment.yaml
- data/kubemacpool/004-pod_disruption_budget.yaml
- pkg/components/components.go
- test/releases/0.15.0.go
In the new version podDisruptionBudget and podAntiAffinity were added to kubemacpool.
> Bump kubemacpool version to v0.5.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.15.0/cluster-network-addons-operator.0.15.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.15.0/namespace.yaml
- manifests/cluster-network-addons/0.15.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.15.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.15.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.16.0.go
* bump kubemacpool to 0.5.0, includes stability improvements and bug fixes
> Release 0.15.0

- pkg/network/multus_test.go
- test/e2e/workflow/deployment_test.go
- test/e2e/workflow/recovery_test.go
> add Test-IDs

- Makefile
- README.md
- manifests/cluster-network-addons/0.16.0/cluster-network-addons-operator.0.16.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.16.0/namespace.yaml
- manifests/cluster-network-addons/0.16.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.16.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.16.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.17.0.go
* Update nmstate
* Update kubemacpool
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/239)
> Release 0.16.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.17.0/cluster-network-addons-operator.0.17.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.17.0/namespace.yaml
- manifests/cluster-network-addons/0.17.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.17.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.17.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.18.0.go
New kubemacpool version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/242)
> Release 0.17.0

- pkg/components/components.go
- tools/manifest-templator/manifest-templator.go
Let the user specify a custom image name
running the CSV genrator.
Fixes: https://bugzilla.redhat.com/1757798
> Custom image name in the CSV generator

- Makefile
- README.md
- manifests/cluster-network-addons/0.18.0/cluster-network-addons-operator.0.18.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.18.0/namespace.yaml
- manifests/cluster-network-addons/0.18.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.18.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.18.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.19.0.go
* Allow custom image names generated in CSV
* Add labels to kubemacpool deployments for easier filtering
> Release 0.18.0

- pkg/components/components.go
- test/releases/0.19.0.go
This PR bump the kubemacpool image version.
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/cluster-network-addons-operator/248)
> Bump kubemacpool version to v0.8.0

- data/nmstate/003-operator.yaml
- pkg/components/components.go
- test/releases/0.19.0.go
> bump nmstate to v0.10.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.19.0/cluster-network-addons-operator.0.19.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.19.0/namespace.yaml
- manifests/cluster-network-addons/0.19.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.19.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.19.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.20.0.go
* Bump kubemacpool to v0.8.0
* Bump kubernetes-nmstate to v0.11.0
> Release 0.19.0

- pkg/components/components.go
- test/releases/0.20.0.go
> bump knmstate to 0.12.0

- .gitignore
- Makefile
- automation/check-patch.packages
- cluster/clean.sh
- cluster/cli.sh
- cluster/down.sh
- cluster/gocli.sh
- cluster/kubevirtci.sh
- cluster/operator-install.sh
- cluster/operator-push.sh
- cluster/up.sh
- hack/functest.sh
Replace the custom local cluster solution with kubevirtci. This should
be easier to read and maintain.
> use kubevirtci's cluster-up script

- cluster/up.sh
- data/kubemacpool/003-deployment.yaml
- data/linux-bridge/0004-bridge-marker-daemonset.yaml
- data/linux-bridge/002-linux-bridge.yaml
- data/multus/002-multus.yaml
- data/nmstate/003-operator.yaml
- data/ovs/002-ovs-daemonset.yaml
Save some resources on our limited OKD clusters.
> use minimal resource requests

- Makefile
- README.md
- manifests/cluster-network-addons/0.20.0/cluster-network-addons-operator.0.20.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.20.0/namespace.yaml
- manifests/cluster-network-addons/0.20.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.20.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.20.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.21.0.go
* Always install cnv- prefixed binaries
* Use kubevirtci's cluster-up for CI
* Start testing on OKD
* Bump kubernetes-nmstate to 0.12.0
* Set resource request to all pods
> Release 0.20.0

- manifests/cluster-network-addons/0.21.0/cluster-network-addons-operator.0.21.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.21.0/operator.yaml
> Use correct nmstate version

- Makefile
- README.md
- manifests/cluster-network-addons/0.23.0/cluster-network-addons-operator.0.23.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.23.0/namespace.yaml
- manifests/cluster-network-addons/0.23.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.23.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.23.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.24.0.go
> Release 0.23.0

- pkg/components/components.go
- test/releases/0.24.0.go
> bump ovs-cni to v0.9.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.24.0/cluster-network-addons-operator.0.24.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.24.0/namespace.yaml
- manifests/cluster-network-addons/0.24.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.24.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.24.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.25.0.go
* Bump ovs-cni to v0.9.0, fixing marker on OVS-less nodes
> Release 0.24.0

- components.yaml
- data/nmstate/001-rbac.yaml
- data/nmstate/002-crd.yaml
- pkg/components/components.go
- test/releases/0.25.0.go
> bump knmstate to v0.13.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.25.0/cluster-network-addons-operator.0.25.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.25.0/namespace.yaml
- manifests/cluster-network-addons/0.25.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.25.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.25.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.26.0.go
* bump knmstate version to 0.13.0
* rename Multus DS to just "multus"
> Release 0.25.0

- pkg/controller/networkaddonsconfig/pod_controller.go
> Fix warning by adding comment to exported function

- components.yaml
- data/nmstate/002-crd.yaml
- data/nmstate/003-operator.yaml
> bump knmstate to 0.15.0

- components.yaml
- pkg/components/components.go
- test/releases/0.27.0.go
> pin kubemacpool to v0.8.1

- Makefile
- README.md
- manifests/cluster-network-addons/0.27.0/cluster-network-addons-operator.0.27.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.27.0/namespace.yaml
- manifests/cluster-network-addons/0.27.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.27.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.27.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.28.0.go
`./hack/release.sh 0.26.0 0.27.0 0.28.0 origin phoracek`
* kubernetes-nmstate 0.15.0
* kubemacpool v0.8.1
> Release 0.27.0

- data/nmstate/001-rbac.yaml
> knmstate: Add missing rbac for webhook

- components.yaml
- data/nmstate/003-operator.yaml
- pkg/components/components.go
- test/releases/0.28.0.go
> Bump knmstate to v0.15.1

- cluster/operator-push.sh
- cluster/up.sh
> Fix ocp make cluster-sync

- Makefile
- hack/bump-kubevirtci.sh
> Add make bump-kubevirtci target

- components.yaml
- data/nmstate/003-operator.yaml
- pkg/components/components.go
- test/releases/0.28.0.go
> Bump knmstate to 0.15.3

- components.yaml
- data/kubemacpool/kubemacpool.yaml
- pkg/components/components.go
- test/releases/0.28.0.go
> bump kubemacpool to 0.8.2

- Makefile
- README.md
- manifests/cluster-network-addons/0.27.2/cluster-network-addons-operator.0.27.2.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.27.2/namespace.yaml
- manifests/cluster-network-addons/0.27.2/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.27.2/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.27.2/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.27.2.go
* Bump knmstate to 0.15.3
* Bump kubemacpool to 0.8.2
> Release 0.27.2

- data/nmstate/002-crd.yaml
> expose knmstate object status

- Makefile
- README.md
- manifests/cluster-network-addons/0.27.3/cluster-network-addons-operator.0.27.3.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.27.3/namespace.yaml
- manifests/cluster-network-addons/0.27.3/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.27.3/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.27.3/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.27.3.go
* fix status column on knmstate CRs
> Release 0.27.3

- data/nmstate/003-operator.yaml
> drop knmstate webhook

- Makefile
- README.md
- manifests/cluster-network-addons/0.27.4/cluster-network-addons-operator.0.27.4.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.27.4/namespace.yaml
- manifests/cluster-network-addons/0.27.4/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.27.4/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.27.4/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.27.4.go
* drop knmstate webhook manifest
> Release 0.27.4

- pkg/network/multus.go
> rename multus daemon set in variable namespace

- Makefile
- README.md
- manifests/cluster-network-addons/0.29.0/cluster-network-addons-operator.0.29.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.29.0/namespace.yaml
- manifests/cluster-network-addons/0.29.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.29.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.29.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.29.0.go
- version/description
- version/version.go
Bump versions of dependencies and add release automation.
> Release 0.29.0

- automation/check-patch.e2e-lifecycle-k8s.sh
- automation/check-patch.e2e-lifecycle-okd.sh
- automation/check-patch.e2e-workflow-k8s.sh
- automation/check-patch.e2e-workflow-okd.sh
- automation/check-patch.setup.sh
- version/version.go
The release script used a wrong setup.sh script.
> fix automated release

- automation/check-patch.setup.sh
> include .git while copying to TMP_PROJECT_PATH

- Makefile
- README.md
- manifests/cluster-network-addons/0.30.0/cluster-network-addons-operator.0.30.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.30.0/namespace.yaml
- manifests/cluster-network-addons/0.30.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.30.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.30.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.30.0.go
- version/description
- version/version.go
> Release 0.30.0

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
> bump ovs cni to 0.11.0

- components.yaml
- data/nmstate/003-operator.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
> bump knmstate to 0.17.0

- Makefile
- README.md
- automation/check-patch.e2e-lifecycle-k8s.sh
- manifests/cluster-network-addons/0.31.0/cluster-network-addons-operator.0.31.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.31.0/namespace.yaml
- manifests/cluster-network-addons/0.31.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.31.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.31.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.31.0.go
- version/description
- version/version.go
> Release 0.31.0

- components.yaml
- data/kubemacpool/kubemacpool.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
> bump kubemacpool to 0.8.3

- components.yaml
- data/kubemacpool/kubemacpool.yaml
- pkg/components/components.go
- test/releases/0.28.0.go
> [release-0.27] bump kubemacpool to 0.8.3

- Makefile
- README.md
- manifests/cluster-network-addons/0.27.5/cluster-network-addons-operator.0.27.5.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.27.5/namespace.yaml
- manifests/cluster-network-addons/0.27.5/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.27.5/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.27.5/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.27.5.go
* drop limitation for component resources
* bump kubemacpool to 0.8.3
> Release 0.27.5

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
> Bump multus to 3.4.1

- Makefile
- README.md
- manifests/cluster-network-addons/0.32.0/cluster-network-addons-operator.0.32.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.32.0/namespace.yaml
- manifests/cluster-network-addons/0.32.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.32.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.32.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.32.0.go
- version/description
- version/version.go
> Release 0.32.0

- components.yaml
- pkg/components/components.go
- test/check/check.go
- test/releases/0.28.0.go
> bump knmstate to 0.15.4

- Makefile
- README.md
- manifests/cluster-network-addons/0.27.6/cluster-network-addons-operator.0.27.6.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.27.6/namespace.yaml
- manifests/cluster-network-addons/0.27.6/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.27.6/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.27.6/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.27.6.go
* bump kubemacpool to 0.8.3
* bump kubernetes-nmstate to 0.15.4
> Release 0.27.6

- Makefile
- README.md
- manifests/cluster-network-addons/0.27.7/cluster-network-addons-operator.0.27.7.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.27.7/namespace.yaml
- manifests/cluster-network-addons/0.27.7/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.27.7/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.27.7/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.27.7.go
* bump knmstate to v0.15.5
* drop ownership of CRDs
> Release 0.27.7

- components.yaml
- data/nmstate/000-ns.yaml
- data/nmstate/001-rbac.yaml
- data/nmstate/003-operator.yaml
- pkg/components/components.go
- pkg/network/nmstate.go
- test/releases/99.0.0.go
> bump kubernetes-nmstate to 0.18.0

- hack/components.sh
Since these operations will be needed for all components, it is worth abstracting them.    
Depends on: https://github.com/kubevirt/cluster-network-addons-operator/pull/366
> move component helpers into functions

- Makefile
- README.md
- manifests/cluster-network-addons/0.34.0/cluster-network-addons-operator.0.34.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.34.0/namespace.yaml
- manifests/cluster-network-addons/0.34.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.34.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.34.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.34.0.go
- version/description
- version/version.go
Bugs:
* knmstate: fix Namespace variable in templates (#369)
* move component helpers into functions (#367)
* clone components instead of go get (#366)
> Release 0.34.0

- components.yaml
- data/nmstate/001-rbac.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
> bump kubernetes-nmstate to 0.19.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.35.0/cluster-network-addons-operator.0.35.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.35.0/namespace.yaml
- manifests/cluster-network-addons/0.35.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.35.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.35.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.35.0.go
- version/description
- version/version.go
> Release 0.35.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.35.1/cluster-network-addons-operator.0.35.1.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.35.1/namespace.yaml
- manifests/cluster-network-addons/0.35.1/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.35.1/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.35.1/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.35.1.go
- version/description
- version/version.go
> Release 0.35.1

- Makefile
- README.md
- manifests/cluster-network-addons/0.36.0/cluster-network-addons-operator.0.36.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.36.0/namespace.yaml
- manifests/cluster-network-addons/0.36.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.36.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.36.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.36.0.go
- version/description
- version/version.go
> Release 0.36.0

- Makefile
> Use correct github path for github-release

- pkg/apply/merge.go
- pkg/apply/merge_test.go
The code that reconcile CABundle at webhookconfiguration was covering only the
case when webhookcofiguration is updated but not when CABundle is updated by a
rotation or created after a webhook delete.
> Cover all use cases at caBundle

- test/check/check.go
- test/check/components.go
This PR add checks in e2e tests to ensure deletion and deployment of Secrets and MutationWebhookConfiguration objects
> Ensure components objects deletion and creation at e2e tests

- components.yaml
- data/kubemacpool/kubemacpool.yaml
- hack/components.sh
- pkg/components/components.go
- test/check/components.go
- test/e2e/workflow/deployment_test.go
- test/releases/99.0.0.go
This PR supersedes #377, #386, #395 Kubemacpool bump
```release-note
Bump kubemacpool to v0.13.0
```
> Bump kubemacpool v0.13.0

- automation/check-patch.e2e-lifecycle-k8s.sh
- automation/check-patch.e2e-workflow-k8s.sh
- cluster/kubevirtci.sh
Signed-off-by: Or Mergi <ormergi@redhat.com>
This PR bumps kubevirtci version
```release-note
NONE
```
> Bump kubevirtci

- Makefile
- manifests/cluster-network-addons/0.38.0/cluster-network-addons-operator.0.38.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.38.0/namespace.yaml
- manifests/cluster-network-addons/0.38.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.38.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.38.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.38.0.go
- version/description
- version/version.go
> Release 0.38.0

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
We haven't updated the linux-bridge CNI in quite some time. Let's fix it.
```release-note
Linux bridge CNI was set to 0.8.6
```
> bump linux-bridge to 0.8.6

- components.yaml
- data/ovs/002-ovs-daemonset.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
Bump OVS CNI to v0.12.0. This new version is pinned to Kubernetes 0.18
```release-note
Pin OVS CNI v0.12.0
```
> bump ovs-cni 0.12.0

- components.yaml
- data/kubemacpool/kubemacpool.yaml
- pkg/components/components.go
- pkg/controller/statusmanager/status_manager.go
- test/check/check.go
- test/releases/99.0.0.go
bump kubemacpool to v0.14.3
```release-note
kubemacpool v0.14.3
```
> bump kubemacpool to v0.14.4

- Makefile
- manifests/cluster-network-addons/0.39.1/cluster-network-addons-operator.0.39.1.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.39.1/namespace.yaml
- manifests/cluster-network-addons/0.39.1/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.39.1/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.39.1/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.39.1.go
- version/description
- version/version.go
```release-note
Release 0.39.1
```
> Release 0.39.1

- Makefile
- manifests/cluster-network-addons/0.39.2/cluster-network-addons-operator.0.39.2.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.39.2/namespace.yaml
- manifests/cluster-network-addons/0.39.2/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.39.2/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.39.2/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.39.2.go
- version/description
- version/version.go
Release 0.39.2 with important KMP fixes.
```release-note
NONE
```
> Release 0.39.2

- Makefile
- automation/check-patch.e2e-lifecycle-k8s.sh
- automation/check-patch.e2e-workflow-k8s.sh
- automation/check-patch.setup.sh
- go.mod
- go.sum
- test/e2e/lifecycle/main_test.go
- test/e2e/workflow/main_test.go
- vendor/kubevirt.io/qe-tools/LICENSE
- vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md
- vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go
- vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go
- vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go
- vendor/modules.txt
It dumps the test results at CI to a junit xml, this make possible for prow to parse it and show a table with results making easier to pin-point what tests are failing.
```release-note
NONE
```
> Junit report

- components.yaml
- data/kubemacpool/kubemacpool.yaml
- pkg/components/components.go
- test/e2e/lifecycle/upgrade_test.go
- test/releases/99.0.0.go
It uses a controller based cert-manager that reconcile TLS
if it's broken.
```release-note
Bump kubemacpool to 0.15.0
```
> Bump kubemacpool to v0.15.0

- test/check/check.go
CNAO is missing important info to debug test failures, adding the description
give us more clues.
```release-note
NONE
```
> Add describe-all to test checks

- Makefile
- manifests/cluster-network-addons/0.39.3/cluster-network-addons-operator.0.39.3.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.39.3/namespace.yaml
- manifests/cluster-network-addons/0.39.3/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.39.3/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.39.3/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.39.3.go
- version/description
- version/version.go
Bugs:
* Do not trim the version exposed in CR (#466)
This bug is preventing upgrades in HCO.
```release-note
NONE
```
> Release 0.39.3

- Makefile
- hack/components/bump-linux-bridge.sh
Currently cnao only bumps linux-bridge manually.
Let's add a script to do it for us.
This PR is a subset of an older PR #363 
```release-note
NONE
```
> adding linux-bridge bump script

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
It mostly contains some stabilization fixes and improvements in test
infrastructure.
```release-note
Bump KubeMacPool to v0.16.0
```
> Bump KubeMacPool to v0.16.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.40.0/cluster-network-addons-operator.0.40.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.40.0/namespace.yaml
- manifests/cluster-network-addons/0.40.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.40.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.40.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.40.0.go
- version/description
- version/version.go
> Release 0.40.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.40.1/cluster-network-addons-operator.0.40.1.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.40.1/namespace.yaml
- manifests/cluster-network-addons/0.40.1/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.40.1/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.40.1/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.40.1.go
- version/description
- version/version.go
Features:
* Add bridge-marker bump script (#458)
* Add ovs-cni bump script (#457)
* Add multus bump script (#456)
Bugs:
* Add kubernetes-nmstate openshift scc manifests (#475)
* use kustomize version used on kmp (#477)
```release-note
NONE
```
> Release 0.40.1

- pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
- pkg/controller/statusmanager/status_manager.go
Second attempt to fix the infamous #451 
Added generation field to StatusManager, which is set in Reconcile and used in SetFromPods to 
verify that we're checking tha current networkAddonsConfig before setting status to Available.
This is a follow-up to #474
```release-note
none
```
> Check SetFromPods has current networkAddonsConfig generation

- components.yaml
- data/kubemacpool/kubemacpool.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
The kubemacpool v0.18.0 include some manager pod environment variable to control the
certificates rotation behaviour.
```release-note
Bump kubemacpool to v0.18.0 
```
> Bump kubemacpool to v0.18.0

- automation/check-patch.e2e-lifecycle-k8s.sh
- manifests/cluster-network-addons/0.27.7/cluster-network-addons-operator.0.27.7.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.27.7/namespace.yaml
- manifests/cluster-network-addons/0.27.7/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.27.7/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.27.7/operator.yaml
- test/releases/0.27.7.go
Use the last z-stream release of that branch to test the real upgrade
flow. Somebody can upgrade from any of the z-stream releases, but in
order to save resources, we will test only the latest one.
```release-note
Test upgrades from 0.27.7 z-stream instead of 0.27.0
```
> test upgrades from 0.27.7 instead of 0.27.0

- automation/check-patch.e2e-lifecycle-k8s.sh
- manifests/cluster-network-addons/0.39.3/cluster-network-addons-operator.0.39.3.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.39.3/namespace.yaml
- manifests/cluster-network-addons/0.39.3/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.39.3/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.39.3/operator.yaml
- test/releases/0.39.3.go
Use the last z-stream release of that branch to test the real upgrade
flow. Somebody can upgrade from any of the z-stream releases, but in
order to save resources, we will test only the latest one.
```release-note
Test upgrades from 0.39.3 instead of 0.39.0
```
> Test upgrades from 0.39.3 instead of 0.39.0

- automation/check-patch.e2e-kubemacpool-functests.sh
- automation/check-patch.setup.sh
- automation/components-functests.setup.sh
- hack/deploy-kubevirt.sh
This PR adds new test lane, KubeMacPool functional tests on a cluster with latest changes on CNAO,
this also adds the infrastructure that enable one create such automation for any other CNAO component e.g: NMstate
Project-Infra prow job for this lane PR https://github.com/kubevirt/project-infra/pull/457
```release-note
NONE
```
> Automation: KubeMacPool functests on CNAO lane

- pkg/network/self_sign_configuration_test.go
This convert all of the SelfSignedCertificate to ginkgo table so all the tests there are done the same way.
```release-note
NONE
```
> Convert the rest of the SelfSignedConfiguration test to table

- Makefile
- manifests/cluster-network-addons/0.39.4/cluster-network-addons-operator.0.39.4.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.39.4/namespace.yaml
- manifests/cluster-network-addons/0.39.4/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.39.4/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.39.4/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.39.4.go
- version/description
- version/version.go
> Release 0.39.4

- Makefile
- README.md
- manifests/cluster-network-addons/0.41.0/cluster-network-addons-operator.0.41.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.41.0/namespace.yaml
- manifests/cluster-network-addons/0.41.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.41.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.41.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.41.0.go
- version/description
- version/version.go
> Release 0.41.0

- components.yaml
- data/nmstate/operator.yaml
- pkg/components/components.go
- pkg/network/nmstate.go
- test/releases/99.0.0.go
```release-note
Bump knmstate to v0.29.0
```
> Bump kubernetes-nmstate to v0.29.0

- components.yaml
- data/kubemacpool/kubemacpool.yaml
- hack/components/bump-kubemacpool.sh
- pkg/components/components.go
- test/releases/99.0.0.go
Some fixes at bump-kubemacpool scripts are included, there is new kustomize patches
to be applied related to opt-in kubemacpool
```release-note
Bump kubemacpool to 0.20.0
```
> Bump kubemacpool to v0.20.0

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
```release-note
Bump Linux Bridge CNI to v0.8.7
```
> Bump Linux Bridge CNI to v0.8.7

- Makefile
- README.md
- manifests/cluster-network-addons/0.42.0/cluster-network-addons-operator.0.42.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.42.0/namespace.yaml
- manifests/cluster-network-addons/0.42.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.42.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.42.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.42.0.go
- version/description
- version/version.go
> Release 0.42.0

- pkg/eventemitter/eventemitter.go
fixed a typo in the Available event message.
Signed-off-by: alonSadan <asadan@redhat.com>
```release-note
NONE
```
> events: fix typo in available event

- OWNERS
> Add Ram to approvers, Alon with Radim to reviewers

- README.md
Let's reflect the upgrade from v1alpha1 to v1 in the readme.
```release-note
NONE
```
> Bump NAC version advertised in the README

- test/operations/operations.go
After calling .Delete on NetworkAddonsConfig it takes some time to be really deleted
this add a Eventually after call delete that check if NAC has being really deleted so
we don't pollute other tests.
```release-note
NONE
```
> test: Ensure NAC does not exists eventually after delete

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
```release-note
Bump ovs-cni to v0.13.0
```
> Bump ovs-cni to v0.13.0

- Makefile
- manifests/cluster-network-addons/0.42.1/cluster-network-addons-operator.0.42.1.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.42.1/namespace.yaml
- manifests/cluster-network-addons/0.42.1/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.42.1/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.42.1/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.42.1.go
- version/description
- version/version.go
> Release 0.42.1

- test/e2e/workflow/validation_test.go
This is an manual cherry-pick of #573 
```release-note
NONE
```
> [release-0.42] refactor fix of flaky validation test

- components.yaml
- pkg/components/components.go
> Bump macvtap-cni to v0.4.0

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
> Bump bridge-marker to v0.4.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.42.2/cluster-network-addons-operator.0.42.2.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.42.2/namespace.yaml
- manifests/cluster-network-addons/0.42.2/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.42.2/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.42.2/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.42.2.go
- version/description
- version/version.go
Release 0.42.2
```release-note
Release 0.42.2
```
> Release 0.42.2

- components.yaml
- tools/bumper/bumper.go
This PR fixed a bug in bumper script update to components.yaml
- **bumper, Fix update of component in components.yaml**
Currently the yaml is not really changed
as we are not updating the real items when iteration, but their copy instance.
Lets fix this by updating the real items.
Also, once the components.yaml is changed the components are reformatted.
So Let's align to the way updateComponentsYaml updates it.
```release-note
NONE
```
> bumper, Fix update of component in components.yaml

- components.yaml
- data/nmstate/nmstate.io_nodenetworkconfigurationenactments_crd.yaml
- data/nmstate/nmstate.io_nodenetworkconfigurationpolicies_crd.yaml
- data/nmstate/nmstate.io_nodenetworkstates_crd.yaml
- data/nmstate/operator.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
```release-note
Bump kubernetes-nmstate component to v0.32.0
```
> Bump kubernetes-nmstate component to v0.32.0

- components.yaml
- data/multus/001-multus.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
```release-note
Bump multus to v3.4.2
```
> Bump multus to v3.4.2

- README.md
Currently the README file is mentioning the d/s project openshift.
We want to keep u/s repo clean from that.
Removed openshift mentions from README.
```release-note
NONE
```
> readme, Remove openshift remarks from CNAO repo

- pkg/components/components.go
This PR adds pod description to CNAO pod
```release-note
NONE
```
> add pod description to CNAO pod

- pkg/components/components.go
Currently the crd lacks the validation schema of
placementConfiguration. This is because the crd
is not automatically generated at the moment.
Fixed placementConfiguration validation schema.
This PR mimics the output of the auto-generated crd, as displayed in this [PR](https://github.com/kubevirt/cluster-network-addons-operator/pull/577)
```release-note
NONE
```
> crd, Fix placementConfiguration validation schema

- Makefile
- manifests/cluster-network-addons/0.42.3/cluster-network-addons-operator.0.42.3.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.42.3/namespace.yaml
- manifests/cluster-network-addons/0.42.3/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.42.3/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.42.3/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.42.3.go
- version/description
- version/version.go
```release-note
Release 0.42.3
```
> Release 0.42.3

- components.yaml
- data/linux-bridge/003-bridge-marker.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
bump bridge-marker to 0.5.0
```release-note
bump bridge-marker to 0.5.0
```
> bump bridge-marker to 0.5.0

- automation/check-patch.e2e-nmstate-functests.sh
This PR adds a script that runs nmstate e2e test on CNAO cluster
```release-note
NONE
```
> tier1, Add kubernetes nmstate tier1 automation test

- .github/workflows/component-bumper.yml
- tools/bumper/README.md
- tools/bumper/bumper.go
- tools/bumper/cnao_repo_commands.go
This reverts commit #648 which broke bumper run.
```release-note
NONE
```
> Revert "bumper, Make base-branch configurable (#648)"

- .github/workflows/component-bumper.yml
- tools/bumper/README.md
- tools/bumper/bumper.go
- tools/bumper/cnao_repo_commands.go
This PR is re-inserting the changes inserted in #648 and reverted on #654 , with a slight change not break the bumper gitAction job.
```release-note
NONE
```
> Bumper make base-branch configurable

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
The release not from kubernetes-nmstate [1]
[1] https://github.com/nmstate/kubernetes-nmstate/releases/tag/v0.31.1
```release-note
Bump kubernetes-nmstate to 0.31.1
```
> Bump kubernetes-nmstate to v0.31.1

- components.yaml
- data/kubemacpool/kubemacpool.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
bump kubemacpool to v0.20.3
```release-note
bump kubemacpool to v0.20.3
```
> bump kubemacpool to v0.20.3

- Makefile
- manifests/cluster-network-addons/0.42.4/cluster-network-addons-operator.0.42.4.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.42.4/namespace.yaml
- manifests/cluster-network-addons/0.42.4/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.42.4/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.42.4/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.42.4.go
- version/description
- version/version.go
> Release 0.42.4

- README.md
update placement configuration chapter on
README for day2 changes
```release-note
NONE
```
> placement-configurqation, update README.md

- .travis.yml
- hack/release.sh
To reduce the number of system we use let's move the release process
totally to prow.
```release-note
NONE
```
> Use prow to push container at release

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
bump kubemacpool to v0.20.4
```release-note
bump kubemacpool to v0.20.4
```
> bump kubemacpool to v0.20.4

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
bump nmstate to v0.37.0
```release-note
bump nmstate to v0.37.0
```
> bump nmstate to v0.37.0

- tools/bumper/bumper.go
This PR is opened in relation to a issue #693 opened due to knmstate bump fail that caused the bumper to stop bumping.
- **bumper, Change bumper fail policy**
Currently, the bumper script will fail upon the first bump failure.
We want to be able to run the bumper on all components even if one
component bump is broken.
The new behavior is that all found bumps will occur, and in the end if at least one
component failed to bump - the job will exit with error.
```release-note
NONE
```
> bumper, Change bumper fail policy

- Makefile
- README.md
- manifests/cluster-network-addons/0.44.1/cluster-network-addons-operator.0.44.1.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.44.1/namespace.yaml
- manifests/cluster-network-addons/0.44.1/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.44.1/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.44.1/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.44.1.go
- version/description
- version/version.go
Release 0.44.1
```release-note
Release 0.44.1
```
> Release 0.44.1

- Makefile
- README.md
- manifests/cluster-network-addons/0.45.0/cluster-network-addons-operator.0.45.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.45.0/namespace.yaml
- manifests/cluster-network-addons/0.45.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.45.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.45.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.45.0.go
- version/description
- version/version.go
release 0.45.0
```release-note
NONE
```
> Release 0.45.0

- test/e2e/lifecycle/deployment_test.go
Before applying any networkaddonsconfig the operator has to be in ready
estate.
```release-note
NONE
```
> Check cnao readiness at lifecycle deployment test

- Makefile
- README.md
- manifests/cluster-network-addons/0.44.2/cluster-network-addons-operator.0.44.2.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.44.2/namespace.yaml
- manifests/cluster-network-addons/0.44.2/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.44.2/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.44.2/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/e2e/lifecycle/deployment_test.go
- test/releases/0.44.2.go
- version/description
- version/version.go
release 0.44.2
```release-note
NONE
```
> Release 0.44.2

- automation/check-patch.e2e-lifecycle-k8s.sh
- automation/check-patch.e2e-workflow-k8s.sh
- automation/check-patch.setup.sh
- test/e2e/lifecycle/main_test.go
- test/e2e/workflow/main_test.go
- test/reporter/reporter.go
- test/reporter/writers.go
When CNAO CI finish there is no useful artifacts to do forensics on
them, this change add a custom ginkgo reporter that will store the CNAO
pods logs into spearate files at artifacts directory.
```release-note
NONE
```
> Add e2e tests custom reporter

- hack/components/bump-multus.sh
- pkg/components/components.go
- test/releases/99.0.0.go
We are hiting rate limit from docker.io, this change build and push the multus
container to quay.io.
```release-note
Move multus container to quay.io
```
> Build and push multus container to quay.io

- Makefile
- README.md
- manifests/cluster-network-addons/0.46.0/cluster-network-addons-operator.0.46.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.46.0/namespace.yaml
- manifests/cluster-network-addons/0.46.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.46.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.46.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.46.0.go
- version/description
- version/version.go
Release 0.46.0
```release-note
NONE
```
> Release 0.46.0

- components.yaml
- hack/components/bump-linux-bridge.sh
- pkg/components/components.go
- test/releases/99.0.0.go
This is an manual cherry-pick of #772 
```release-note
Bump CNI plugins to 74a6b2
```
> [release-0.44] Bump CNI plugins version

- test/check/check.go
This PR adds a pod status print when status checks fail.
- **ci, add pod status when ci tests fail**
Currently when CNAO is failing in tests that check desired status, we describe
all CNAO related components.
Added a pods status print to make it easier to see the big picture.
```release-note
NONE
```
> ci, Add pod status to fail test logs

- Makefile
- README.md
- manifests/cluster-network-addons/0.48.0/cluster-network-addons-operator.0.48.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.48.0/namespace.yaml
- manifests/cluster-network-addons/0.48.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.48.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.48.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.48.0.go
- version/description
- version/version.go
Release 0.48.0
```release-note
NONE
```
> Release 0.48.0

- test/check/check.go
Depending on the CNAO version when components are deployed some of then
update the secrets and they cannot be reconciled or deleted, so they are
still alive after components removal, this change adapt the e2e tests to
it.
```release-note
NONE
```
> Skip secret leftover check if not needed

- README.md
Clarify general purpose of Infra and Workload categories
```release-note
NONE
```
> Clarify general purpose of Infra and Workload categories

- Makefile
- README.md
- manifests/cluster-network-addons/0.50.0/cluster-network-addons-operator.0.50.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.50.0/namespace.yaml
- manifests/cluster-network-addons/0.50.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.50.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.50.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.50.0.go
- version/description
- version/version.go
Release 0.50.0
```release-note
NONE
```
> Release 0.50.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.51.0/cluster-network-addons-operator.0.51.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.51.0/namespace.yaml
- manifests/cluster-network-addons/0.51.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.51.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.51.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.51.0.go
- version/description
- version/version.go
> Release 0.51.0

- build/operator/Dockerfile
The yum update && yum clean all steps were not actually completing. The
command was being run together, and needed the command separator.
Signed-off-by: Brad P. Crochet <brad@redhat.com>
```release-note
NONE
```
> Correct the Dockerfile at yum update

- components.yaml
- data/kubemacpool/kubemacpool.yaml
- hack/components/bump-kubemacpool.sh
- pkg/components/components.go
- test/check/components.go
- test/e2e/workflow/deployment_test.go
- test/releases/99.0.0.go
```release-note
Bump kubemacpool to v0.24.0
```
> Bump kubemacpool to v0.24.0

- Makefile
- README.md
- automation/check-patch.e2e-bridge-marker-functests.sh
- manifests/cluster-network-addons/0.52.0/cluster-network-addons-operator.0.52.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.52.0/namespace.yaml
- manifests/cluster-network-addons/0.52.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.52.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.52.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.52.0.go
- version/description
- version/version.go
Release 0.52.0
```release-note
NONE
```
> Release 0.52.0

- .github/workflows/component-bumper-master.yml
- .github/workflows/component-bumper-release-0.42.yml
- .github/workflows/component-bumper-release-0.44.yml
Run autobumper every hour
```release-note
NONE
```
> Run autobumper every hour

- Makefile
- README.md
- manifests/cluster-network-addons/0.53.0/cluster-network-addons-operator.0.53.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.53.0/namespace.yaml
- manifests/cluster-network-addons/0.53.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.53.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.53.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.53.0.go
- version/description
- version/version.go
Release 0.53.0
```release-note
NONE
```
> Release 0.53.0

- .github/workflows/component-bumper-release-0.53.yml
This workflow will follow bumps needed in release-0.53
```release-note
NONE
```
> auto-bumper, Add new stable branch release-0.53 workflow

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
bump kubemacpool to v0.26.1
```release-note
bump kubemacpool to v0.26.1
```
> bump kubemacpool to v0.26.1

- Makefile
- README.md
- manifests/cluster-network-addons/0.54.0/cluster-network-addons-operator.0.54.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.54.0/namespace.yaml
- manifests/cluster-network-addons/0.54.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.54.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.54.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.54.0.go
- version/description
- version/version.go
Release 0.54.0
```release-note
Release 0.54.0
```
> Release 0.54.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.53.1/cluster-network-addons-operator.0.53.1.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.53.1/namespace.yaml
- manifests/cluster-network-addons/0.53.1/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.53.1/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.53.1/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.53.1.go
- version/description
- version/version.go
Release 0.53.1
```release-note
Release 0.53.1
```
> Release 0.53.1

- components.yaml
As part of making the community more welcoming we have rename the
kubernetes-nmstate default branch to 'main'.
```release-note
NONE
```
> Use new default knmstate branch 'main'

- components.yaml
The repo main branch was renamed from `master` to `main`.
```release-note
NONE
```
> macvtap-cni: update repo main branch

- components.yaml
- tools/bumper/parser_test.go
The project was migrated from kubevirt under
https://github.com/k8snetworkplumbingwg.
```release-note
NONE
```
> Change OVS CNI source to NPWG org

- components.yaml
This PR updates knmstate main branch on components.yaml
```release-note
NONE
```
> [release-0.53] Update knmstate main branch

- Makefile
- manifests/cluster-network-addons/0.42.5/cluster-network-addons-operator.0.42.5.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.42.5/namespace.yaml
- manifests/cluster-network-addons/0.42.5/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.42.5/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.42.5/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.42.5.go
- version/description
- version/version.go
Release 0.42.5
```release-note
Release 0.42.5
```
> Release 0.42.5

- Makefile
- README.md
- manifests/cluster-network-addons/0.44.4/cluster-network-addons-operator.0.44.4.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.44.4/namespace.yaml
- manifests/cluster-network-addons/0.44.4/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.44.4/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.44.4/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.44.4.go
- version/description
- version/version.go
Release 0.44.4
```release-note
Release 0.44.4
```
> Release 0.44.4

- Makefile
- README.md
- manifests/cluster-network-addons/0.55.0/cluster-network-addons-operator.0.55.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.55.0/namespace.yaml
- manifests/cluster-network-addons/0.55.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.55.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.55.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.55.0.go
- version/description
- version/version.go
Release 0.55.0
```release-note
Release 0.55.0
```
> Release 0.55.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.53.2/cluster-network-addons-operator.0.53.2.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.53.2/namespace.yaml
- manifests/cluster-network-addons/0.53.2/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.53.2/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.53.2/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.53.2.go
- version/description
- version/version.go
Release 0.53.2
```release-note
Release 0.53.2
```
> Release 0.53.2

- Makefile
- README.md
- manifests/cluster-network-addons/0.44.5/cluster-network-addons-operator.0.44.5.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.44.5/namespace.yaml
- manifests/cluster-network-addons/0.44.5/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.44.5/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.44.5/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.44.5.go
- version/description
- version/version.go
Release 0.44.5
```release-note
NONE
```
> Release 0.44.5

- components.yaml
> Change ovs-cni repo to k8snetworkplumbinggw

- Makefile
- README.md
- manifests/cluster-network-addons/0.53.3/cluster-network-addons-operator.0.53.3.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.53.3/namespace.yaml
- manifests/cluster-network-addons/0.53.3/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.53.3/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.53.3/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.53.3.go
- version/description
- version/version.go
Release 0.53.3
```release-note
Release 0.53.3
```
> Release 0.53.3

- Makefile
- README.md
- manifests/cluster-network-addons/0.56.0/cluster-network-addons-operator.0.56.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.56.0/namespace.yaml
- manifests/cluster-network-addons/0.56.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.56.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.56.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.56.0.go
- version/description
- version/version.go
Release 0.56.0
```release-note
Release 0.56.0
```
> Release 0.56.0

- components.yaml
Master has turned main.
```release-note
NONE
```
> Follow bridge-marker's renamed branch

- components.yaml
Master turned into main.
```release-note
NONE
```
> Follow the renamed branch of OVS CNI

- components.yaml
> [0.42] Follow main branch in bridge marker

- components.yaml
> [0.53] Follow main branches on marker and ovs cni

- components.yaml
> [0.44] Follow main branch on marker and ovs cni

- components.yaml
This PR updates kubemacpool branch to main
```release-note
NONE
```
> components, Update kubemacpool branch to main

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
release-0.53: bump nmstate to 0.47.1
```release-note
knm 0.47.1
```
> release-0.53: bump nmstate to 0.47.1

- Makefile
- README.md
- manifests/cluster-network-addons/0.53.4/cluster-network-addons-operator.0.53.4.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.53.4/namespace.yaml
- manifests/cluster-network-addons/0.53.4/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.53.4/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.53.4/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.53.4.go
- version/description
- version/version.go
Release 0.53.4
```release-note
NONE
```
> Release 0.53.4

- Makefile
- README.md
- manifests/cluster-network-addons/0.57.0/cluster-network-addons-operator.0.57.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.57.0/namespace.yaml
- manifests/cluster-network-addons/0.57.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.57.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.57.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.57.0.go
- version/description
- version/version.go
Release 0.57.0
```release-note
Release 0.57.0
```
> Release 0.57.0

- components.yaml
This is a manual cherry-pick of #902
```release-note
NONE
```
> [release-0.42] components, Update multus repo url

- .github/workflows/component-bumper-main.yml
Following the change of default branch from master to main,
we are also updating the default branch related workflow
```release-note
NONE
```
> bumper, update default branch workflow

- Makefile
- README.md
- manifests/cluster-network-addons/0.53.5/cluster-network-addons-operator.0.53.5.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.53.5/namespace.yaml
- manifests/cluster-network-addons/0.53.5/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.53.5/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.53.5/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.53.5.go
- version/description
- version/version.go
> Release 0.53.5

- data/multus/001-multus.yaml
- hack/components/bump-multus.sh
Update multus resources section according
congested cluster simulation.
```release-note
None
```
> resources, Update multus resources section

- data/linux-bridge/002-linux-bridge.yaml
Validate with resources limit that those are sufficient
for normal use.
```release-note
None
```
> linux bridge, Update linux bridge minimum resources request

- README.md
- automation/check-patch.e2e-lifecycle-k8s.sh
- automation/check-patch.e2e-workflow-k8s.sh
- automation/components-functests.setup.sh
- cluster/cluster.sh
- cluster/up.sh
This PR updates the KBUEVIRTCI_TAG and updated the default provider to k8s-1.21
```release-note
NONE
```
> update default provider to k8s 1.21

- components.yaml
- data/macvtap/002-macvtap-daemonset.yaml
- pkg/components/components.go
> [release-0.53] macvtap, Bump to v0.5.1

- Makefile
- README.md
- manifests/cluster-network-addons/0.53.6/cluster-network-addons-operator.0.53.6.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.53.6/namespace.yaml
- manifests/cluster-network-addons/0.53.6/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.53.6/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.53.6/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.53.6.go
- version/description
- version/version.go
> Release 0.53.6

- pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
- tools/bumper/bumper.go
- tools/bumper/git_fakes.go
This PR fixes the output of `make-fmt`
```release-note
NONE
```
> fix make fmt outputs

- test/check/check.go
The CNAO Operator does not need to have the version label (it
already has it on annotation).
The reason CI passed up until now is that the deployment had no labels
and the test didn't fail this scenario.
Fixing to check only needed cases (when checking CNAO components' deployments)
and returning error if labels are non-existing.
```release-note
NONE
```
> checkForDeployment, don't check on CNAO operator itself

- cmd/manager/main.go
update deprecated AddToScheme function on openshift/api
to Install function
```release-note
NONE
```
> main, Update deprecated AddToScheme function

- Makefile
- README.md
- manifests/cluster-network-addons/0.44.6/cluster-network-addons-operator.0.44.6.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.44.6/namespace.yaml
- manifests/cluster-network-addons/0.44.6/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.44.6/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.44.6/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.44.6.go
- version/description
- version/version.go
Release 0.44.6
```release-note
Release 0.44.6
```
> Release 0.44.6

- Makefile
- README.md
- manifests/cluster-network-addons/0.53.7/cluster-network-addons-operator.0.53.7.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.53.7/namespace.yaml
- manifests/cluster-network-addons/0.53.7/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.53.7/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.53.7/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.53.7.go
- version/description
- version/version.go
> Release 0.53.7

- Makefile
- README.md
- manifests/cluster-network-addons/0.59.0/cluster-network-addons-operator.0.59.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.59.0/namespace.yaml
- manifests/cluster-network-addons/0.59.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.59.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.59.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.59.0.go
- version/description
- version/version.go
Release 0.59.0
```release-note
NONE
```
> Release 0.59.0

- components.yaml
- data/nmstate/operand/operator.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
The kubernetes-nmstate v0.54.0 was pointing to an out of main branch
commit id, this change point CNAO to the correct commit id.
```release-note
Point  kubernetes-nmstate to proper v0.54.0 commit id.
```
> Change kubernetes-nmstate commit

- components.yaml
- data/nmstate/operand/nmstate.io_nodenetworkconfigurationenactments.yaml
- data/nmstate/operand/nmstate.io_nodenetworkconfigurationpolicies.yaml
- data/nmstate/operand/nmstate.io_nodenetworkstates.yaml
- data/nmstate/operand/operator.yaml
- hack/components/bump-nmstate.sh
- pkg/components/components.go
- pkg/network/nmstate.go
- test/releases/99.0.0.go
This band is not needed for 0.58
This reverts commit c0344ed9e6ff38b946495e98d3f9113fd1b8a3e5.
```release-note
NONE
```
> Revert "bump nmstate to v0.54.0 (#1014)"

- Makefile
- README.md
- manifests/cluster-network-addons/0.58.2/cluster-network-addons-operator.0.58.2.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.58.2/namespace.yaml
- manifests/cluster-network-addons/0.58.2/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.58.2/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.58.2/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.58.2.go
- version/description
- version/version.go
> Release 0.58.2

- components.yaml
Pin knmstate to release branch 0.52
```release-note
NONE
```
> [release-0.58] Pin knmstate to release branch 0.52

- Makefile
- README.md
- manifests/cluster-network-addons/0.60.0/cluster-network-addons-operator.0.60.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.60.0/namespace.yaml
- manifests/cluster-network-addons/0.60.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.60.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.60.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.60.0.go
- version/description
- version/version.go
> Release 0.60.0

- pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
- pkg/controller/networkaddonsconfig/pod_controller.go
- pkg/controller/statusmanager/status_manager.go
This is a manual cherry-pick of https://github.com/kubevirt/cluster-network-addons-operator/pull/1032
```release-note
NONE
```
> [release-0.58] status_manger, Reduce number of status update API calls

- cluster/up.sh
Adds NetworkManager-ovs package so that nmstatectl can configure ovs networking 
```release-note
NONE
```
> Add Networkmanager-ovs to support ovs configuration for nmstate

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
This PR reverts #1065
```release-note
NONE
```
> Revert "bump ovs-cni to v0.26.0 (#1065)"

- Makefile
- README.md
- manifests/cluster-network-addons/0.61.0/cluster-network-addons-operator.0.61.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.61.0/namespace.yaml
- manifests/cluster-network-addons/0.61.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.61.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.61.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.61.0.go
- version/description
- version/version.go
> Release 0.61.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.62.0/cluster-network-addons-operator.0.62.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.62.0/namespace.yaml
- manifests/cluster-network-addons/0.62.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.62.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.62.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.62.0.go
- version/description
- version/version.go
Release 0.62.0
```release-note
NONE
```
> Release 0.62.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.58.4/cluster-network-addons-operator.0.58.4.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.58.4/namespace.yaml
- manifests/cluster-network-addons/0.58.4/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.58.4/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.58.4/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.58.4.go
- version/description
- version/version.go
Release 0.58.4
```release-note
NONE
```
> Release 0.58.4

- Makefile
- README.md
- manifests/cluster-network-addons/0.53.9/cluster-network-addons-operator.0.53.9.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.53.9/namespace.yaml
- manifests/cluster-network-addons/0.53.9/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.53.9/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.53.9/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.53.9.go
- version/description
- version/version.go
> Release 0.53.9

- hack/components/bump-nmstate.sh
knmstate: Fix CRs path
```release-note
NONE
```
> knmstate: Fix CRs path

- Makefile
- README.md
- manifests/cluster-network-addons/0.53.10/cluster-network-addons-operator.0.53.10.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.53.10/namespace.yaml
- manifests/cluster-network-addons/0.53.10/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.53.10/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.53.10/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.53.10.go
- version/description
- version/version.go
> Release 0.53.10

- Makefile
- README.md
- manifests/cluster-network-addons/0.58.5/cluster-network-addons-operator.0.58.5.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.58.5/namespace.yaml
- manifests/cluster-network-addons/0.58.5/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.58.5/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.58.5/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.58.5.go
- version/description
- version/version.go
> Release 0.58.5

- Makefile
- README.md
- manifests/cluster-network-addons/0.63.0/cluster-network-addons-operator.0.63.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.63.0/namespace.yaml
- manifests/cluster-network-addons/0.63.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.63.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.63.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.63.0.go
- version/description
- version/version.go
Release 0.63.0
```release-note
NONE
```
> Release 0.63.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.64.0/cluster-network-addons-operator.0.64.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.64.0/namespace.yaml
- manifests/cluster-network-addons/0.64.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.64.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.64.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.64.0.go
- version/description
- version/version.go
Release 0.64.0
```release-note
NONE
```
> Release 0.64.0

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- automation/check-patch.e2e-nmstate-functests.sh
- pkg/apis/networkaddonsoperator/shared/networkaddonsconfig_types.go
- pkg/components/components.go
- pkg/network/placement_configuration.go
- pkg/network/placement_configuration_test.go
- test/e2e/lifecycle/deployment_test.go
- test/e2e/lifecycle/upgrade_test.go
- test/releases/releases.go
- tools/bumper/README.md
- tools/bumper/bumper.go
- tools/bumper/cnao_repo_commands_test.go
- tools/bumper/component_commands_test.go
- tools/bumper/git_fakes.go
As part of removing offending language this change do the following:
- master branch -> main branch
- master node -> control-plane node
```release-note
NONE
```
> language: Replace master with main/control-plane

- Makefile
- README.md
- manifests/cluster-network-addons/0.65.0/cluster-network-addons-operator.0.65.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.65.0/namespace.yaml
- manifests/cluster-network-addons/0.65.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.65.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.65.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.65.0.go
- version/description
- version/version.go
Release 0.65.0
```release-note
NONE
```
> Release 0.65.0

- Makefile
- README.md
- manifests/cluster-network-addons/0.65.1/cluster-network-addons-operator.0.65.1.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.65.1/namespace.yaml
- manifests/cluster-network-addons/0.65.1/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.65.1/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.65.1/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.65.1.go
- version/description
- version/version.go
Release 0.65.1
```release-note
NONE
```
> Release 0.65.1

- pkg/network/nmstate.go
This change ensures that nmstate handler pods have the
`kubernetes.io/os: linux` node selector.
```release-note
add kubernetes.io/os=linux nodeSelector to nmstate handler pods by default.
```
> Add default linux OS nodeSelector to nmstate handlers

- Makefile
- README.md
- manifests/cluster-network-addons/0.53.11/cluster-network-addons-operator.0.53.11.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.53.11/namespace.yaml
- manifests/cluster-network-addons/0.53.11/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.53.11/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.53.11/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.53.11.go
- version/description
- version/version.go
Release 0.53.11
```release-note
NONE
```
> Release 0.53.11

- Makefile
- README.md
- manifests/cluster-network-addons/0.65.2/cluster-network-addons-operator.0.65.2.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.65.2/namespace.yaml
- manifests/cluster-network-addons/0.65.2/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.65.2/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.65.2/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.65.2.go
- version/description
- version/version.go
Release 0.65.2
```release-note
NONE
```
> Release 0.65.2

- Makefile
- README.md
- manifests/cluster-network-addons/0.58.6/cluster-network-addons-operator.0.58.6.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.58.6/namespace.yaml
- manifests/cluster-network-addons/0.58.6/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.58.6/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.58.6/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.58.6.go
- version/description
- version/version.go
```release-note
bump nmstate to v0.52.11
```
> Release 0.58.6

- cluster/up.sh
Looks like NetworkManager 1.36 has some issues related to nmstate, this
change pin it to 1.34
```release-note
NONE
```
> deps: Ping NetworkManager to 1.34

- automation/check-patch.e2e-lifecycle-k8s.sh
For the sake of saving time on regular PR test runs, we should limit the
versions we test upgrade from to versions released under HCO.
```release-note
NONE
```
> Update list of released versions for upgrade test

- components.yaml
Follow knmstate release branch
```release-note
NONE
```
> 0.65, components: Follow knmstate release branch

- components.yaml
Before you click the 'Create pull request' make sure that:
- This PR introduces a single feature of fix, just one
- This PR does not leave the main branch broken
- Every commit in this PR has a commit message explaining what do you change,
why and what is the outcome
- If your change introduces a complex concept or a change to user interaction
with the project or the application, make sure to document it
If you don't comply with these rules, you waste your energy, time of reviewers
and cause suffering of future generations.
-->
This reverts commit 79bbb94b2c33e3cbdd7d6778c26cd7a6afa47edb.
```release-note
NONE
```
> Revert "0.65, components: Follow knmstate release branch (#1148)"

- components.yaml
At main branch we should receive new tags from main branch at
components with the autobumper.
```release-note
NONE
```
> components: Mark all of them as tagged

- components.yaml
Follow KMP release branch
```release-note
NONE
```
> [release-0.65] components: Follow KMP release branch

- .github/workflows/component-bumper-release-0.65.yaml
bumper: Add auto bump for release-0.65
```release-note
NONE
```
> bumper: Add auto bump for release-0.65

- .github/workflows/component-bumper.yaml
- pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
The autobumper was referencing the non existent env BASE_BRANCH
The autobumper was referencing the non existent env BASE_BRANCH
```release-note
NONE
```
> actions: Remove BASE_BRANCH

- .github/workflows/component-bumper.yaml
actions: Fix autobumper typo
```release-note
NONE
```
> actions: Fix autobumper typo

- .github/workflows/component-bumper.yaml
- pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
This reverts commit aaef587ae4ccbdb7a24bb3bcb91724c469bc38ae.
While fixing autobumper github actions some wip for the controller get merged.
```release-note
NONE
```
> Revert "actions: Remove BASE_BRANCH"

- pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
Trying to fix github actions autobumper a wip for the controller zip in.
This change revert that controller change.
```release-note
NONE
```
> controller: Go back to nmstate-op deployments

- .github/workflows/component-bumper.yaml
To allow to run autobumper manually this change add the
workflow_distpatcher event.
```release-note
NONE
```
> bumper: Add github workflow_dispatcher

- components.yaml
The containernetworking/plugins repo has no tags at the pinned commit or
any of the future commits, let's just pin it to static.
```release-note
NONE
```
> components: Mark linux-bridge autobumper to static

- .github/workflows/prepare-version.yaml
It was missing the dollar symbol
```release-note
NONE
```
> actions: Fix prepare version distpatcher

- Makefile
- RELEASE.md
- hack/prepare-release.sh
- hack/release-notes.tmpl
- hack/release.sh
- hack/render-release-notes.sh
- hack/versions.sh
- version/description
Right now the release notes comes from the commits, but the info needed
is the release-note mark from PRs since users decide if they want that
info to appear that the release notes or not.
```release-note
NONE
```
> 0.65, infra: Use PRs to compose release notes

- Makefile
- RELEASE.md
- hack/prepare-release.sh
- hack/release-notes.tmpl
- hack/release.sh
- hack/render-release-notes.sh
- hack/versions.sh
- version/description
Right now the release notes comes from the commits, but the info needed
is the release-note mark from PRs since users decide if they want that
info to appear that the release notes or not.
```release-note
NONE
```
> 0.53, infra: Use PRs to compose release notes

- test/e2e/workflow/deployment_test.go
Added test of transition of NMState deployment from CNAO
to nmstate-operator.
```release-note
NONE
```
> e2e: test nmstate switch from CNAO to nmstate-operator

- test/e2e/workflow/deployment_test.go
> [release-0.65] e2e: test nmstate switch from CNAO to nmstate-operator

- README.md
- automation/check-patch.e2e-lifecycle-k8s.sh
- automation/check-patch.e2e-workflow-k8s.sh
- automation/components-functests.setup.sh
- cluster/cluster.sh
CNAO is testing towards k8s-1.21 we should go to the latest k8s version
at main.
```release-note
NONE
```
> kubevirtci: Bump to k8s-1.23

- automation/check-patch.e2e-multus-functests.sh
This PR adds a new test for the multus component, in which the pod's default gateway
is overridden to be featured on the secondary interface.
Depends-on: #1219
```release-note
NONE
```
> Test new multus features

- Makefile
- automation/check-patch.e2e-monitoring-k8s.sh
- cluster/up.sh
- go.mod
- go.sum
- pkg/components/components.go
- test/e2e/monitoring/alerts_test.go
- test/e2e/monitoring/main_test.go
- test/e2e/monitoring/prometheus_utils.go
- test/kubectl/kubectl.go
- test/operations/operations.go
- vendor/github.com/jpillora/backoff/LICENSE
- vendor/github.com/jpillora/backoff/README.md
- vendor/github.com/jpillora/backoff/backoff.go
- vendor/github.com/mwitkow/go-conntrack/.gitignore
- vendor/github.com/mwitkow/go-conntrack/.travis.yml
- vendor/github.com/mwitkow/go-conntrack/LICENSE
- vendor/github.com/mwitkow/go-conntrack/README.md
- vendor/github.com/mwitkow/go-conntrack/dialer_reporter.go
- vendor/github.com/mwitkow/go-conntrack/dialer_wrapper.go
- vendor/github.com/mwitkow/go-conntrack/listener_reporter.go
- vendor/github.com/mwitkow/go-conntrack/listener_wrapper.go
- vendor/github.com/prometheus/client_golang/api/client.go
- vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go
- vendor/github.com/prometheus/common/config/config.go
- vendor/github.com/prometheus/common/config/http_config.go
- vendor/golang.org/x/oauth2/clientcredentials/clientcredentials.go
- vendor/modules.txt
This PR adds a monitoring lane to CNAO.
It also adds e2e tests to check CnaoDown alert
a followup PR is planned to introduce the tests using https.
PR relies on https://github.com/kubevirt/cluster-network-addons-operator/pull/1258 (first commit)
```release-note
NONE
```
> e2e, alerts, Add monitoring lane and tests

- components.yaml
The linux bridge CNI master branch has being renamed to main branch.
```release-note
Use main branch for linux-bridge CNI.
```
> linux-bridge: Move to main branch

- data/kubemacpool/kubemacpool.yaml
- hack/components/bump-kubemacpool.sh
> TLS: Move tls env vard to mac-controller-mgr

- Makefile
- pkg/controller/statusmanager/status_manager.go
This PR makes sure that future PRs cannot insert format issues to the repo.
```release-note
NONE
```
> format, Fix format check

- Makefile
- pkg/controller/statusmanager/status_manager.go
This PR reverts #1305 
```release-note
NONE
```
> Revert "Merge pull request #1305 from RamLavi/fix_format_check"

- pkg/components/components.go
With the current code, generated CRD would contain trailing spaces and
that would fail release unit tests lane.
```release-note
NONE
```
> Remove trailing spaces from CRD

- automation/check-patch.e2e-lifecycle-k8s.sh
- manifests/cluster-network-addons/0.53.10/cluster-network-addons-operator.0.53.10.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.53.10/namespace.yaml
- manifests/cluster-network-addons/0.53.10/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.53.10/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.53.10/operator.yaml
- manifests/cluster-network-addons/0.58.6/cluster-network-addons-operator.0.58.6.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.58.6/namespace.yaml
- manifests/cluster-network-addons/0.58.6/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.58.6/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.58.6/operator.yaml
- manifests/cluster-network-addons/0.65.6/cluster-network-addons-operator.0.65.6.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.65.6/namespace.yaml
- manifests/cluster-network-addons/0.65.6/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.65.6/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.65.6/operator.yaml
- test/releases/0.53.10.go
- test/releases/0.58.6.go
- test/releases/0.65.6.go
lifecycle test between supported stable branches to main branch were not
updated, and so did not run. 
This PR is updating tests accordingly.
```release-note
NONE
```
> e2e/lifecycle, Update tests for stable branches

- .github/workflows/component-bumper.yaml
- .github/workflows/prepare-version.yaml
- .github/workflows/test-release-notes.yaml
This PR adds the new stable branch to gitActions workflows
```release-note
NONE
```
> gitActions, workflows, Update new branch release-0.76

- .github/workflows/prepare-release-branch.yaml
- Makefile
- hack/update-workflows-branches.sh
Currently creating release branch requires several operations by the
maintainer. This workflow automates some of these operations:
- create a new branch
- update components.yaml
- update workflows
```release-note
NONE
```
> release-branch, Create a workflow

- Makefile
- README.md
- cluster/cluster.sh
- hack/components/bump-linux-bridge.sh
- hack/components/docker-utils.sh
- hack/components/yaml-utils.sh
- hack/prom-rule-ci/verify-rules.sh
Support (rootfull) podman OCI
Auto detect running OCI
Bump kubevirtci to have podman support
```release-note
None
```
> oci: Support podman

- hack/release.sh
This PR fixes #1301 
Files are not uploaded when the release scripts runs.
This is is probably due to a race between the creation
of the release and the manifest being accesible to upload.
Adding an eventually routine to aid the upload.
```release-note
NONE
```
> hack/release, Introduce eventually to resource upload

- test/e2e/monitoring/rules_test.go
This PR adds new test cases for CNAO alert definitions. We expect to see `summary`, `severity`, `kubernetes_operator_part_of` and `kubernetes_operator_component` for each alert. Those fields must not be empty and some must have specific values.
Signed-off-by: assafad <aadmi@redhat.com>
```release-note
None
```
> Add sanity tests for CNAO alerts

- hack/components/bump-multus.sh
This PR fixed bump-multus script due to changes made on multus repo
```release-note
NONE
```
> bump-multus, Fix ds location

- data/monitoring/prom-rule.yaml
- hack/prom-rule-ci/prom-rules-tests.yaml
Signed-off-by: Simone Tiraboschi <stirabos@redhat.com>
Web browsers are becoming increasingly vocal about
unencrypted links, let's move to
https to prevent unnecessary noise.
Only http -> https
```release-note
NONE
```
> Use https on runbooks URLs

- pkg/controller/statusmanager/status_manager.go
/bug 
For OCP 4.11 CNAO does not support NMState anymore at its networkaddonsconfig, the expected behaviour is that if the user has used the old nmstate (by populating some NNCPs) and it has not installed KNO for CNAO to replace old kubernetes-nmstate it has to fail the upgrade. This change add the missing part about checking NNCPs.
Closes https://bugzilla.redhat.com/show_bug.cgi?id=2126537
```release-note
Check NNCPs before failing on OCP 4.10 -> 4.11 upgrade.
```
> nmstate, upgrade: Check nncp before failing

- Makefile
- README.md
- manifests/cluster-network-addons/0.80.0/cluster-network-addons-operator.0.80.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.80.0/namespace.yaml
- manifests/cluster-network-addons/0.80.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.80.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.80.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.80.0.go
- version/version.go
Release v0.80.0
```release-note
NONE
```
> [main] Release v0.80.0

- pkg/network/placement_configuration.go
- pkg/network/placement_configuration_test.go
See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.
```release-note
Note
```
> stop using beta.kubernetes.io/arch

- components.yaml
The statically referenced commit is now included in released versions of the plugins project. This patch switches the update policy to "tagged", to follow the latest stable releases automatically.
```release-note
NONE
```
> Follow latest CNI plugins releases

- components.yaml
- hack/components/bump-multus.sh
- pkg/components/components.go
- test/releases/99.0.0.go
Signed-off-by: Miguel Duarte Barroso <mdbarroso@redhat.com>
```release-note
```
> multus, static policy: do not follow tagged multus versions

- Makefile
- README.md
- components.yaml
- hack/components/bump-multus.sh
- manifests/cluster-network-addons/0.81.0/cluster-network-addons-operator.0.81.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.81.0/namespace.yaml
- manifests/cluster-network-addons/0.81.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.81.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.81.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- pkg/components/components.go
- test/releases/0.81.0.go
- test/releases/99.0.0.go
- version/version.go
Release a version of CNAO featuring multus-v4 (thick plugin architecture) plus the `multus-dynamic-networks` [controller](https://github.com/maiqueb/multus-dynamic-networks-controller).
Depends-on: #1441 
```release-note
NONE
```
> Release 0.81.0 release multus dynamic networks

- data/kube-secondary-dns/secondarydns.yaml
- hack/components/bump-kube-secondary-dns.sh
- pkg/network/kube_secondary_dns_controller.go
- test/e2e/workflow/deployment_test.go
In order to allow HCO control the KSD placement,
add it to the KSD spec.
```release-note
None
```
> ksd: Add Placement support

- go.mod
- go.sum
- vendor/modules.txt
Address https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-4238
```release-note
NONE
```
> Pin goutils to v1.1.1

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
KSD: Bump to v0.0.10
```release-note
bump ksd to v0.0.10
```
> KSD: Bump to v0.0.10

- .github/workflows/prepare-version.yaml
> actions: Add release-0.85

- components.yaml
This patch makes the component follow new tags and auto-bump.
```release-note
NONE
```
> Follow tagged bridge CNI releases

- tools/metricsdocs/metricsdocs.go
- tools/metricsdocs/metricsdocs_test.go
- tools/prom-metrics-collector/metrics_collector.go
This PR fixes an fmt issues on the tools folder
To be clear - This folder is not used as part of the production operation of CNAO.
changed are auto created by `make fmt vet`
```release-note
NONE
```
> tools: Fix fmt issues

- .github/workflows/check_hashicorp_modules.yaml
- hack/check_hashicorp.sh
It allows running the file locally.
```release-note
None
```
> check hashicorp: Extract to a file

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
> [release-0.89] components: Bump multus-dynamic-networks to v0.3.0

- components.yaml
- data/multus-dynamic-networks-controller/000-controller.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
> [release-0.85] components: Bump multus-dynamic-networks to v0.3.0

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
components: Bump multus-dynamic-networks to v0.3.1
```release-note
None
```
> [release-0.89] components: Bump multus-dynamic-networks to v0.3.1

- automation/check-patch.e2e-ovs-cni-functests.sh
We decided to skip them when running via CNAO.
```release-note
None
```
> ovs: Skip flaky ovs-mirror tests

- automation/release.sh
Reverts kubevirt/cluster-network-addons-operator#1701
> [release-0.89] Revert "[release-0.89] automation/release.sh: Temporarily disable release script"

- go.mod
- go.sum
- vendor/modules.txt
CVE-2023-27561, CVE-2023-28642
```release-note
None
```
> CVE-2023-27561: Bump github.com/opencontainers/runc

- go.mod
- go.sum
- vendor/modules.txt
CVE-2023-27561, CVE-2023-28642
```release-note
None
```
> [release-0.89] CVE-2023-27561: Bump github.com/opencontainers/runc

- go.mod
- go.sum
- vendor/modules.txt
CVE-2023-27561, CVE-2023-28642
```release-note
None
```
> [release-0.85] CVE-2023-27561: Bump github.com/opencontainers/runc

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
Manual cherry-pick of https://github.com/kubevirt/cluster-network-addons-operator/pull/1725
```release-note
None
```
> [release-0.85] bump multus-dynamic-networks to v0.3.2

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
> [release-0.79] Bump bridge-marker to 0.11.1

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
> [release-0.89] Bump bridge-marker to 0.11.1

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
> [release-0.85] Bump bridge-marker to 0.11.1

- hack/checkmod.sh
Script helps in checking which branches should be updated, given a package to search for.
```release-note
None
```
> CVEs: Introduce check mod script

- test/releases/releases.go
`RELEASES_SELECTOR` might have version that don't exist assert it has only existing versions, 
so we won't have typo or select non available releases.
```release-note
None
```
> test/releases: Validate RELEASES_SELECTOR

- hack/install-go.sh
Go 1.21 now uses x.y.z notion.
https://tip.golang.org/doc/go1.21#:~:text=Go%201.21%20introduces%20a%20small,release%20is%20now%20Go%201.
Lets just install the latest.
Note that it is expected the go.mod lang level will be kept behind. If needed we can change the mechanism, for example freeze a version whenever updating go.mod lang level.
```release-note
None
```
> go: Update script to install latest go

- tools/manifest-templator/manifest-templator.go
Now that the new ones are used, we can delete the old ones.
```release-note
None
```
> manifest-templator: Cleanup old var names

- .github/workflows/kubevirt-ipam-controller.yaml
This way we won't need to change the manifests when branching.
```release-note
None
```
> git actions, ipam: Run on all branches

- .github/workflows/kubevirt-ipam-controller.yaml
> [release-0.95] git actions: Update IPAM lane to run branch

- .github/workflows/kubevirt-ipam-controller.yaml
- .gitignore
- automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh
Ease debugging of IPAM CI errors.
Also collect logs when running locally, even after the temp folder is deleted.
Injected an error to check it works, example
https://github.com/kubevirt/cluster-network-addons-operator/actions/runs/10453035964?pr=1876
Created in order to find issues such as https://github.com/kubevirt/cluster-network-addons-operator/issues/1857
```release-note
None
```
> git actions, ipam: Add logs collecting upon e2e errors

- .github/workflows/kubevirt-ipam-controller.yaml
- .gitignore
- automation/check-patch.e2e-kubevirt-ipam-controller-functests.sh
Due to https://github.com/actions/upload-artifact/issues/602
Hidden folders are skipped.
We are using .output, so it was skipped and artifacts were not collected in case of an error.
Need https://github.com/kubevirt/cluster-network-addons-operator/pull/1887
```release-note
None
```
> ipam: Fix artifacts collecting

- hack/install-go.sh
This commit is a step towards enabling builds for different architectures.
**What this PR does / why we need it**: s390x enablement
```release-note NONE
```
> feat: enable download of go client for host arch

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
Manual cherry-pick of #1961 
```release-note
NONE
```
> [release-0.97] components/multus-dynamic-networks: Pin to v0.3.4

- renovate.json
We saw that enabling for all branches at once,
is harder to maintain.
Lets enable it only for main.
It will allow us to do stuff in controlled manner.
```release-note
None
```
> renovate: Enable only for main branch

- hack/checkmod.sh
> checkmod: Update supported releases

- components.yaml
> [release-0.93] Follow the stable branch of ovs-cni

- components.yaml
> [release-0.91] Follow the stable branch of ovs-cni

- components.yaml
> [release-0.95] Follow the stable branch of ovs-cni

- components.yaml
> [release-0.97] Follow the stable branch of ovs-cni

- components.yaml
- pkg/components/components.go
- test/releases/99.0.0.go
cherry-pick of #2187 
```release-note
NONE
```
> [release-0.97] bump bridge-marker to 0.12.3

- Makefile
See https://github.com/kubevirt/cluster-network-addons-operator/pull/2120 for more info.
Note that in this PR the check was moved to the end of "make vendor",
so it will detect problems before creating the PR.
```release-note
None
```
> [release-0.97] Makefile: Enforce max allowed version

- Makefile
- go.mod
Also updated go version to adhere the max allowed version on this branch, v1.21
```release-note
None
```
> [release-0.93] makefile: Introduce go version enforcement

- Makefile
Assertion was moved to the end of make vendor,
this way, in case a make vendor violates the condition, it will be detected already locally, before creating the PR.
```release-note
None
```
> [release-0.95] makefile: Fix max go version enforcement

- Makefile
See https://github.com/kubevirt/cluster-network-addons-operator/pull/2120 for more info. 
Note that in this PR the check was moved to the end of `make vendor`,
so it will detect problems before creating the PR.
```release-note
None
```
> Makefile: Enforce max allowed version

- Makefile
> [release-0.91] makefile: Introduce go version enforcement

- Makefile
> [release-0.89] makefile: Introduce go version enforcement

- Makefile
- go.mod
Basically we can use go v1.19 in the branch, question if we want to change it for this old branch.
```release-note
None
```
> [release-0.79] makefile: Introduce go version enforcement

- automation/test-nightly-build.sh
This PR adds a nightly script, that will be run by project-infra.
```release-note
NONE
```
> automation: Add workflow nightly script

- pkg/apply/merge.go
- pkg/apply/merge_test.go
- pkg/controller/networkaddonsconfig/networkaddonsconfig_controller.go
This PR fixes small cases where the error was not needed or not handled at all.
```release-note
NONE
```
> pkg: Handle unhandled errors

- test/check/check.go
- test/e2e/workflow/deployment_test.go
manual cherry-pick of #2195
```release-note
NONE
```
> [release 0.93] e2e/workflow: Fix race waiting for components

- automation/test-nightly-build.sh
The nightly build pushes the wrong manifest files to the remote storage: it pushes the manifests of the latest release instead of the ones from the nightly build.
This PR fixes the issue by using
`make docker-build-operator docker-push-operator` instead of `cluster-operator-push`, that hard codes the image registry to a registry in a local kubevirtci cluster.
Also, the nightly build "version" is now with the value of the image tag, so the manifests will be unique, and visually linked to the image.
```release-note
None
```
> Fix the nightly build test

- Makefile
- README.md
- manifests/cluster-network-addons/0.100.0-rc0/cluster-network-addons-operator.0.100.0-rc0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.100.0-rc0/namespace.yaml
- manifests/cluster-network-addons/0.100.0-rc0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.100.0-rc0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.100.0-rc0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.100.0-rc0.go
- version/version.go
Release v0.100.0-rc0
```release-note
NONE
```
> [main] Release v0.100.0-rc0

- tools/manifest-templator/manifest-templator.go
The 'make check' runs go vet which fails with the following error:
tools/manifest-templator/manifest-templator.go:297:14: non-constant format string in call to fmt.Printf
Replace with Print() because no string formatting is needed.
```release-note
NONE
```
> manifest-templator: Use valid string format

- Makefile
- README.md
- manifests/cluster-network-addons/0.100.0/cluster-network-addons-operator.0.100.0.clusterserviceversion.yaml
- manifests/cluster-network-addons/0.100.0/namespace.yaml
- manifests/cluster-network-addons/0.100.0/network-addons-config-example.cr.yaml
- manifests/cluster-network-addons/0.100.0/network-addons-config.crd.yaml
- manifests/cluster-network-addons/0.100.0/operator.yaml
- manifests/cluster-network-addons/cluster-network-addons.package.yaml
- test/releases/0.100.0.go
- version/version.go
This is a manual release PR for v0.100.0
```release-note
Release v0.100.0
```
> [main] Release v0.100.0

- automation/check-patch.e2e-kubemacpool-functests.sh
Currently tier kubemacpool test is skipping the tests according to the opt mode set on the kubemacpool bumper script.
Using programmatic skip is not a good practice, as it is easy to assume tests passed when they were actually skipped, and the current approach of flexibly skipping according to the bumper script makes it worse. We should explicitly state what the tests should run by using ginkgo label filtering.
Following a [PR](https://github.com/k8snetworkplumbingwg/kubemacpool/pull/568) on KMP that adds ginkgo labels for opt-mode cases, this PR is replacing ginkgo label filtering to predictably state the tests expected to run.
```release-note
NONE
```
> tier1/kubemacpool: Replace ginkgo skip with label filtering
